"""Pre-build: gzip data/{index.html,style.css,ui.js} into web_ui_gz.h.

Architecture (since 2026-04-28 split): the UI lives across three editor-
friendly files instead of a 5000-LOC monolith. Each is gzipped at compile
time and emitted as a separate PROGMEM array. Web routes serve them at:
  /            -> WEB_INDEX_HTML_GZ      (skeleton — head + body shell)
  /style.css   -> WEB_STYLE_CSS_GZ        (all CSS)
  /ui.js       -> WEB_UI_JS_GZ            (all JS — single file pending
                                           per-tab split in a later session)

Browser pulls them as three separate cached resources — first paint is
faster (parser doesn't block on the JS), and any update to one file
invalidates only that resource on reload.

Generated header:
  const uint8_t  WEB_INDEX_HTML_GZ[]   PROGMEM = {...};
  const size_t   WEB_INDEX_HTML_GZ_LEN;
  const uint8_t  WEB_STYLE_CSS_GZ[]    PROGMEM = {...};
  const size_t   WEB_STYLE_CSS_GZ_LEN;
  const uint8_t  WEB_UI_JS_GZ[]        PROGMEM = {...};
  const size_t   WEB_UI_JS_GZ_LEN;
"""
import gzip
import os

Import("env")  # noqa: F821

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
OUT = os.path.join(PROJECT_DIR, "src", "web", "web_ui_gz.h")

# (source path relative to data/, C symbol prefix). Order is the order they
# appear in the generated header.
ASSETS = [
    ("index.html", "WEB_INDEX_HTML"),
    ("style.css",  "WEB_STYLE_CSS"),
    ("ui.js",      "WEB_UI_JS"),
]


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def emit_array(name, gz):
    out = [f"const uint8_t {name}_GZ[] PROGMEM = {{"]
    for i in range(0, len(gz), 16):
        chunk = gz[i:i+16]
        out.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    out.append("};")
    out.append(f"const size_t {name}_GZ_LEN = {len(gz)};")
    return "\n".join(out)


def main():
    sections = ["// AUTO-GENERATED by scripts/gzip_web_ui.py — do not edit.",
                "// Sources under data/. Each is gzipped (level 9) and emitted as a separate",
                "// PROGMEM array, served by independent HTTP routes for browser caching.",
                "#pragma once",
                "#include <Arduino.h>",
                ""]
    summary = []
    for rel, prefix in ASSETS:
        src = os.path.join(PROJECT_DIR, "data", rel)
        if not os.path.isfile(src):
            raise RuntimeError(f"missing {src}")
        raw = read_bytes(src)
        gz = gzip.compress(raw, compresslevel=9)
        sections.append(f"// {rel}: {len(raw)} B raw -> {len(gz)} B gzip "
                        f"({len(gz)*100/len(raw):.1f}%)")
        sections.append(emit_array(prefix, gz))
        sections.append("")
        summary.append(f"{rel}={len(raw)}->{len(gz)}")
    header = "\n".join(sections)

    # Skip rewrite if identical (prevents unnecessary relink).
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as f:
            if f.read() == header:
                print(f"[gzip_web_ui] unchanged {' '.join(summary)}")
                return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"[gzip_web_ui] {' '.join(summary)}")


main()
