"""Pre-build: extract HTML from src/web/web_ui.cpp, gzip it, generate web_ui_gz.h.

Reads the raw-string literal between R"HTML(...)HTML" in web_ui.cpp,
compresses with max gzip, emits src/web/web_ui_gz.h with:
  - const uint8_t WEB_INDEX_HTML_GZ[] PROGMEM = {...};
  - const size_t WEB_INDEX_HTML_GZ_LEN;

web_server.cpp serves it via AsyncWebServerResponse with Content-Encoding: gzip.
This shrinks 78KB HTML to ~15KB over the wire — 5x faster on WiFi.
"""
import gzip
import os
import re

Import("env")  # noqa: F821

SRC = os.path.join(env["PROJECT_DIR"], "src", "web", "web_ui.cpp")  # noqa: F821
OUT = os.path.join(env["PROJECT_DIR"], "src", "web", "web_ui_gz.h")  # noqa: F821


def extract_html(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    matches = re.findall(r'R"HTML\((.*?)\)HTML"', text, re.DOTALL)
    if not matches:
        raise RuntimeError("raw-string HTML literal not found in web_ui.cpp")
    # Pick the longest match — guards against short literals in comments
    longest = max(matches, key=len)
    return longest.encode("utf-8")


def generate_header(raw):
    gz = gzip.compress(raw, compresslevel=9)
    lines = ["// AUTO-GENERATED by scripts/gzip_web_ui.py — do not edit.",
             "#pragma once",
             "#include <Arduino.h>",
             "",
             f"// Original: {len(raw)} bytes  Gzipped: {len(gz)} bytes  Ratio: {len(gz)*100/len(raw):.1f}%",
             "const uint8_t WEB_INDEX_HTML_GZ[] PROGMEM = {"]
    for i in range(0, len(gz), 16):
        chunk = gz[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t WEB_INDEX_HTML_GZ_LEN = {len(gz)};")
    lines.append("")
    return "\n".join(lines), len(raw), len(gz)


def main():
    raw = extract_html(SRC)
    header, orig_sz, gz_sz = generate_header(raw)

    # Skip rewrite if output is identical (avoids forcing relink)
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as f:
            if f.read() == header:
                print(f"[gzip_web_ui] unchanged ({orig_sz}B -> {gz_sz}B)")
                return

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"[gzip_web_ui] {SRC} -> {OUT}  ({orig_sz}B -> {gz_sz}B, {gz_sz*100/orig_sz:.1f}%)")


main()
