"""Inject FW_VERSION + force consumers to rebuild when it changes.

Historically we used `-DFW_VERSION=\"...\"` as a build flag, but
PlatformIO's incremental-build cache doesn't recompile translation
units just because a -D macro value changed — so after `git commit`
the firmware binary kept the old commit sha until some file that
includes the OTA info endpoint was edited.

Fix: write the version into a generated header (`src/core/build_info.h`).
The build system sees a real file change and recompiles every
translation unit that #include's it — reliably picking up every commit.

Priority:
  1. PLATFORMIO_BUILD_FLAGS contains FW_VERSION (CI sets this) -> use it.
  2. Current commit has an annotated tag -> use it.
  3. Fallback -> "dev-<short-sha>" or "dev".
"""
import os
import subprocess
from pathlib import Path

Import("env")  # noqa: F821  (injected by PlatformIO)


def _git(args):
    try:
        return subprocess.check_output(
            ["git"] + args,
            stderr=subprocess.DEVNULL,
            cwd=env["PROJECT_DIR"],  # noqa: F821
        ).decode().strip()
    except Exception:
        return ""


def _detect_version():
    env_flags = os.environ.get("PLATFORMIO_BUILD_FLAGS", "")
    if "FW_VERSION" in env_flags:
        for frag in env_flags.split():
            if "FW_VERSION=" in frag:
                return frag.split("=", 1)[1].strip('"\\')
        return None
    tag = _git(["describe", "--tags", "--exact-match"])
    if tag:
        return tag
    sha = _git(["rev-parse", "--short", "HEAD"])
    return f"dev-{sha}" if sha else "dev"


def _write_if_changed(path: Path, content: str) -> bool:
    """Only write when content differs — preserves mtime when nothing changed
    so PIO doesn't do a spurious full rebuild on every pio run."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


version = _detect_version()
if version:
    project_dir = Path(env["PROJECT_DIR"])  # noqa: F821
    header = project_dir / "src" / "core" / "build_info.h"
    content = (
        "// Auto-generated by scripts/inject_version.py — do not edit.\n"
        "// Regenerated whenever the git version changes, so every\n"
        "// translation unit that #include's this re-compiles.\n"
        "#pragma once\n"
        f'#define FW_VERSION "{version}"\n'
    )
    changed = _write_if_changed(header, content)
    # Keep the -D flag too for back-compat with any TU that doesn't #include.
    env.Append(BUILD_FLAGS=[f'-DFW_VERSION=\\"{version}\\"'])  # noqa: F821
    print(f"[inject_version] FW_VERSION = {version} ({'rewrote' if changed else 'unchanged'} {header.relative_to(project_dir)})")
