#pragma once
#include <Arduino.h>

// HTML/CSS/JS for web UI (embedded in PROGMEM)
extern const char WEB_INDEX_HTML[];
extern const size_t WEB_INDEX_HTML_LEN;

// Gzipped version — auto-generated by scripts/gzip_web_ui.py
// Served with Content-Encoding: gzip; ~4x smaller over the wire.
extern const uint8_t WEB_INDEX_HTML_GZ[];
extern const size_t WEB_INDEX_HTML_GZ_LEN;
