#include "web_server.h"
#include "web_ui.h"
#include "web_state.h"
#include "wifi_manager.h"
#include "pin_config.h"
#include <Wire.h>
#include "battery/dji_battery.h"
#include "battery/smbus.h"
#include "motor/dshot.h"
#include "motor/blheli_onewire.h"
#include "blheli/blheli_4way.h"
#include "servo/servo_pwm.h"
#include "bridge/esp_rom_flasher.h"
#include "bridge/firmware_unpack.h"
#include "crsf/crsf_service.h"
#include "crsf/crsf_config.h"
#include "core/usb_mode.h"
#include "core/pin_port.h"
#include "battery/battery_profiles.h"
#include "battery/dataflash_map.h"
#include "rc_sniffer/rc_sniffer.h"
#include "fpv/esc_telem.h"
#include "http/routes_flash.h"
#include "http/routes_ota.h"
#include "http/routes_battery.h"

extern "C" int cp2112_log_dump(char *out, int cap);
extern "C" uint32_t cp2112_log_seq();
extern "C" int cp2112_ep_info(char *out, int cap);

#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <AsyncTCP.h>
#include <ArduinoJson.h>
#include <Update.h>
#include <esp_ota_ops.h>
#include <HTTPClient.h>
#include <HTTPUpdate.h>
#include <WiFiClientSecure.h>

// Build info header is generated by scripts/inject_version.py at every
// `pio run` — include it so this TU rebuilds whenever the git sha changes.
#if __has_include("core/build_info.h")
#  include "core/build_info.h"
#endif
#ifndef FW_VERSION
#define FW_VERSION "dev"
#endif
#ifndef GITHUB_REPO
#define GITHUB_REPO ""
#endif

// OTA pull state — moved to src/web/http/routes_ota.cpp

static AsyncWebServer *s_server = nullptr;
static AsyncWebSocket *s_ws = nullptr;
static bool s_running = false;
static uint32_t s_lastBroadcast = 0;

// Guards the shared `String` fields in the clone-research endpoints
// (s_brute.hits, s_macResp.hits / baselineHex, s_logger.entries). The
// Arduino String class is not thread-safe — a background FreeRTOS task
// appends while the HTTP status handler reads .c_str(), so we need a lock
// to avoid use-after-free if the producer reallocates mid-read.

static void handleWsMsg(AsyncWebSocketClient *client, uint8_t *data, size_t len) {
    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, data, len);
    if (err) return;

    const char* cmd = doc["cmd"];
    if (!cmd) return;

    // State-only commands: update shared state under lock, nothing else.
    // Hardware side-effects happen in later blocks AFTER the lock is dropped.
    enum ServoHwAction { SH_NONE, SH_SET_PULSE, SH_SET_FREQ, SH_STOP, SH_START_SWEEP };
    ServoHwAction servoHw = SH_NONE;
    int servoHwArg = 0;

    {
        WebState::Lock lock;

        if (strcmp(cmd, "servo") == 0) {
            int us = constrain((int)(doc["us"] | 1500), 100, 20000);
            WebState::servo.pulseUs = us;
            WebState::servo.active = true;
            WebState::servo.sweep = false;  // manual move cancels sweep
            if (WebState::servo.observedMinUs == 0 || us < WebState::servo.observedMinUs)
                WebState::servo.observedMinUs = us;
            if (us > WebState::servo.observedMaxUs) WebState::servo.observedMaxUs = us;
            servoHw = SH_SET_PULSE; servoHwArg = us;
        } else if (strcmp(cmd, "servoFreq") == 0) {
            int hz = doc["hz"] | 50;
            if (hz != WebState::servo.freq) {
                WebState::servo.freq = hz;
                servoHw = SH_SET_FREQ; servoHwArg = hz;
            }
        } else if (strcmp(cmd, "servoStop") == 0) {
            WebState::servo.active = false;
            WebState::servo.sweep = false;
            servoHw = SH_STOP;
        } else if (strcmp(cmd, "servoSweep") == 0) {
            bool on = doc["on"] | false;
            WebState::servo.sweep = on;
            if (on && !WebState::servo.active) {
                servoHw = SH_START_SWEEP; servoHwArg = WebState::servo.freq;
                WebState::servo.active = true;
            }
        } else if (strcmp(cmd, "servoSweepCfg") == 0) {
            int mn = doc["minUs"] | WebState::servo.sweepMinUs;
            int mx = doc["maxUs"] | WebState::servo.sweepMaxUs;
            int pr = doc["periodMs"] | WebState::servo.sweepPeriodMs;
            WebState::servo.sweepMinUs = constrain(mn, 500, 2500);
            WebState::servo.sweepMaxUs = constrain(mx, 500, 2500);
            if (WebState::servo.sweepMaxUs <= WebState::servo.sweepMinUs)
                WebState::servo.sweepMaxUs = WebState::servo.sweepMinUs + 100;
            WebState::servo.sweepPeriodMs = constrain(pr, 200, 20000);
        } else if (strcmp(cmd, "servoMarkMin") == 0) {
            WebState::servo.markedMinUs = WebState::servo.pulseUs;
        } else if (strcmp(cmd, "servoMarkMax") == 0) {
            WebState::servo.markedMaxUs = WebState::servo.pulseUs;
        } else if (strcmp(cmd, "servoResetMarks") == 0) {
            WebState::servo.markedMinUs = 0;
            WebState::servo.markedMaxUs = 0;
            WebState::servo.observedMinUs = 0;
            WebState::servo.observedMaxUs = 0;
        } else if (strcmp(cmd, "servoApplyMarks") == 0) {
            if (WebState::servo.markedMinUs > 0 && WebState::servo.markedMaxUs > WebState::servo.markedMinUs) {
                WebState::servo.sweepMinUs = WebState::servo.markedMinUs;
                WebState::servo.sweepMaxUs = WebState::servo.markedMaxUs;
            }
        } else if (strcmp(cmd, "motorArm") == 0) {
            WebState::motor.armRequest = true;
        } else if (strcmp(cmd, "motorDisarm") == 0) {
            WebState::motor.disarmRequest = true;
        } else if (strcmp(cmd, "throttle") == 0) {
            int req = constrain((int)(doc["value"] | 0), 0, 2000);
            if (req > WebState::motor.maxThrottle) req = WebState::motor.maxThrottle;
            WebState::motor.throttle = req;
        } else if (strcmp(cmd, "dshotSpeed") == 0) {
            WebState::motor.dshotSpeed = doc["speed"] | 300;
        } else if (strcmp(cmd, "motorBeep") == 0) {
            int b = doc["n"] | 1;
            if (b < 1 || b > 5) b = 1;
            WebState::motor.beepCmd = b;
            WebState::motor.beepRequest = true;
        } else if (strcmp(cmd, "motorMaxThrottle") == 0) {
            int v = constrain((int)(doc["value"] | 2000), 100, 2000);
            WebState::motor.maxThrottle = v;
            if (WebState::motor.throttle > v) WebState::motor.throttle = v;
        } else if (strcmp(cmd, "motorDirCW") == 0) {
            WebState::motor.dirCwRequest = true;
        } else if (strcmp(cmd, "motorDirCCW") == 0) {
            WebState::motor.dirCcwRequest = true;
        } else if (strcmp(cmd, "motor3DOn") == 0) {
            WebState::motor.mode3DOnRequest = true;
        } else if (strcmp(cmd, "motor3DOff") == 0) {
            WebState::motor.mode3DOffRequest = true;
        }
    }  // lock released

    // Hardware side effects (lock released — these can block or call
    // PinPort::acquire without deadlocking).
    switch (servoHw) {
        case SH_SET_PULSE:   ServoPWM::setPulse(servoHwArg); break;
        case SH_SET_FREQ:    ServoPWM::setFrequency(servoHwArg); break;
        case SH_STOP:        ServoPWM::stop(); break;
        case SH_START_SWEEP: ServoPWM::start(SIGNAL_OUT, servoHwArg); break;
        case SH_NONE:        break;
    }
}

static void onWsEvent(AsyncWebSocket *server, AsyncWebSocketClient *client,
                      AwsEventType type, void *arg, uint8_t *data, size_t len) {
    if (type == WS_EVT_CONNECT) {
        Serial.printf("[WS] client #%u connected\n", client->id());
    } else if (type == WS_EVT_DISCONNECT) {
        Serial.printf("[WS] client #%u disconnected\n", client->id());
    } else if (type == WS_EVT_DATA) {
        AwsFrameInfo *info = (AwsFrameInfo*)arg;
        if (info->final && info->index == 0 && info->len == len && info->opcode == WS_TEXT) {
            handleWsMsg(client, data, len);
        }
    }
}

static void broadcastTelemetry() {
    if (s_ws->count() == 0) return;

    // Battery data
    BatteryInfo info = DJIBattery::readAll();
    JsonDocument doc;
    doc["type"] = "batt";
    doc["connected"] = info.connected;
    if (info.connected) {
        doc["devType"] = (int)info.deviceType;  // 0=none,1=DJI,2=generic SBS
        doc["voltage"] = info.voltage_mV;
        doc["current"] = info.current_mA;
        doc["avgCurrent"] = info.avgCurrent_mA;
        doc["temp"] = info.temperature_C;
        doc["soc"] = info.stateOfCharge;
        doc["absSOC"] = info.absoluteSOC;
        doc["soh"] = info.stateOfHealth;
        doc["remain"] = info.remainCapacity_mAh;
        doc["full"] = info.fullCapacity_mAh;
        doc["design"] = info.designCapacity_mAh;
        doc["designV"] = info.designVoltage_mV;
        doc["cycles"] = info.cycleCount;
        doc["status"] = info.batteryStatus;
        doc["statusDecoded"] = DJIBattery::decodeBatteryStatus(info.batteryStatus);
        doc["sn"] = info.serialNumber;
        doc["mfgDate"] = info.manufactureDate;
        doc["mfr"] = info.manufacturerName;
        doc["dev"] = info.deviceName;
        doc["chem"] = info.chemistry;
        doc["cellCount"] = info.cellCount;

        // Time estimates
        doc["rte"] = info.runTimeToEmpty_min;
        doc["ate"] = info.avgTimeToEmpty_min;
        doc["ttf"] = info.timeToFull_min;
        doc["chgI"] = info.chargingCurrent_mA;
        doc["chgV"] = info.chargingVoltage_mV;

        // DJI-specific
        if (info.deviceType == DEV_DJI_BATTERY) {
            if (info.djiSerial.length() > 0) doc["djiSN"] = info.djiSerial;
            doc["djiPF2"] = info.djiPF2;
        }

        // Cells (sync if available)
        JsonArray cells = doc["cells"].to<JsonArray>();
        for (int i = 0; i < info.cellCount; i++) {
            uint16_t v = info.daStatus1Valid ? info.cellVoltSync[i] : info.cellVoltage[i];
            cells.add(v);
        }
        doc["cellsSync"] = info.daStatus1Valid;
        doc["packV"] = info.packVoltage;

        // Extended status
        doc["safetyStatus"] = info.safetyStatus;
        doc["pfStatus"] = info.pfStatus;
        doc["operationStatus"] = info.operationStatus;
        doc["manufacturingStatus"] = info.manufacturingStatus;
        doc["sealed"] = info.sealed;
        doc["hasPF"] = info.hasPF;

        // Decoded
        doc["pfDecoded"] = DJIBattery::decodePFStatus(info.pfStatus);
        doc["safetyDecoded"] = DJIBattery::decodeSafetyStatus(info.safetyStatus);
        doc["opDecoded"] = DJIBattery::decodeOperationStatus(info.operationStatus);
        doc["mfgDecoded"] = DJIBattery::decodeManufacturingStatus(info.manufacturingStatus);

        // Chip/model
        doc["chipType"] = info.chipType;
        doc["fwVer"] = info.firmwareVersion;
        doc["hwVer"] = info.hardwareVersion;
        doc["model"] = DJIBattery::modelName(info.model);
        doc["needsKey"] = DJIBattery::modelNeedsDjiKey(info.model);
    }
    String msg;
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // System info
    doc.clear();
    doc["type"] = "sys";
    doc["ip"] = WifiManager::getIP();
    doc["uptime"] = millis();
    doc["heap"] = ESP.getFreeHeap();
    doc["clients"] = s_ws->count();
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // Motor status
    doc.clear();
    doc["type"] = "motor";
    doc["armed"] = WebState::motor.armed;
    doc["throttle"] = WebState::motor.throttle;
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // Flash status
    doc.clear();
    doc["type"] = "flash";
    doc["size"] = WebState::flashState.fw_size;
    doc["in_progress"] = WebState::flashState.in_progress;
    doc["progress"] = WebState::flashState.progress_pct;
    doc["stage"] = WebState::flashState.stage;
    doc["result"] = WebState::flashState.lastResult;
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // CRSF telemetry (if enabled)
    if (WebState::crsf.enabled && CRSFService::isRunning()) {
        const auto &st = CRSFService::state();
        doc.clear();
        doc["type"] = "crsf";
        doc["enabled"] = true;
        doc["connected"] = st.connected;
        doc["frames"] = st.total_frames;
        doc["badCrc"] = st.bad_crc;

        // Link stats
        if (st.link.valid) {
            JsonObject link = doc["link"].to<JsonObject>();
            link["rssi1"] = (int8_t)st.link.uplink_rssi1 * -1;
            link["rssi2"] = (int8_t)st.link.uplink_rssi2 * -1;
            link["lq"]    = st.link.uplink_link_quality;
            link["snr"]   = st.link.uplink_snr;
            link["rf"]    = st.link.rf_mode;
            link["power"] = st.link.uplink_tx_power;
            link["dlRssi"] = (int8_t)st.link.downlink_rssi * -1;
            link["dlLq"] = st.link.downlink_link_quality;
        }

        // Battery telemetry
        if (st.battery.valid) {
            JsonObject b = doc["battery"].to<JsonObject>();
            b["v"]    = st.battery.voltage_dV / 10.0f;
            b["i"]    = st.battery.current_dA / 10.0f;
            b["mah"]  = st.battery.capacity_mAh;
            b["pct"]  = st.battery.remaining_pct;
        }

        // GPS
        if (st.gps.valid) {
            JsonObject g = doc["gps"].to<JsonObject>();
            g["lat"] = st.gps.latitude_e7 / 1e7;
            g["lon"] = st.gps.longitude_e7 / 1e7;
            g["spd"] = st.gps.speed_cms / 27.78f; // cm/s → km/h
            g["hdg"] = st.gps.heading_cd / 100.0f;
            g["alt"] = (int)st.gps.altitude_m - 1000;
            g["sats"] = st.gps.satellites;
        }

        // Attitude
        if (st.attitude.valid) {
            JsonObject a = doc["att"].to<JsonObject>();
            a["p"] = st.attitude.pitch_10krad / 174.53f; // rad*10000 → degrees
            a["r"] = st.attitude.roll_10krad  / 174.53f;
            a["y"] = st.attitude.yaw_10krad   / 174.53f;
        }

        if (st.mode.valid) doc["mode"] = st.mode.name;

        // Channels
        if (st.channels.valid) {
            JsonArray ch = doc["ch"].to<JsonArray>();
            for (int i = 0; i < 16; i++) ch.add(st.channels.ch[i]);
        }

        // Device info
        const auto &dev = CRSFConfig::deviceInfo();
        if (dev.valid) {
            JsonObject d = doc["device"].to<JsonObject>();
            d["name"]   = dev.name;
            d["fw"]     = dev.sw_ver;
            d["hw"]     = dev.hw_ver;
            d["serial"] = dev.serial;
            d["fields"] = dev.field_count;
        }

        // Parameters
        if (CRSFConfig::paramCount() > 0) {
            JsonArray params = doc["params"].to<JsonArray>();
            for (int i = 0; i < CRSFConfig::paramCount(); i++) {
                const auto &p = CRSFConfig::param(i);
                if (!p.complete) continue;
                if (p.hidden) continue;  // skip debug/internal entries
                JsonObject o = params.add<JsonObject>();
                o["id"]     = p.id;
                o["parent"] = p.parent_id;
                o["type"]   = p.type;
                o["name"]   = p.name;
                o["unit"]   = p.unit;
                if (p.type == 9) {  // TEXT_SELECTION
                    o["opts"] = p.options;
                    o["idx"]  = p.option_index;
                } else if (p.type == 10 || p.type == 12) {  // STRING/INFO
                    o["value"] = p.value_text;
                } else if (p.type == 11) {  // FOLDER
                    // no value
                } else if (p.type == 13) {  // COMMAND
                    // ELRS lifecycle: status + info, rendered as state-aware button(s).
                    o["status"]  = p.value_num;   // 0=READY,2=PROG,3=CONFIRM_NEEDED,...
                    o["timeout"] = p.max_val;     // in 10ms units
                    o["info"]    = p.value_text;
                } else {
                    o["value"] = p.value_num;
                    o["min"] = p.min_val;
                    o["max"] = p.max_val;
                }
            }
        }

        msg = "";
        serializeJson(doc, msg);
        s_ws->textAll(msg);
    }
}

// Flash progress callback (called from flasher)

// Execute flashing (called from main loop when flash_request = true)

void WebServer::start() {
    if (s_running) return;

    s_server = new AsyncWebServer(80);
    RoutesFlash::registerRoutesFlash(s_server);
    RoutesOta::registerRoutesOta(s_server);
    RoutesBattery::registerRoutesBattery(s_server);
    s_ws = new AsyncWebSocket("/ws");
    s_ws->onEvent(onWsEvent);
    s_server->addHandler(s_ws);

    // Root — gzipped HTML from PROGMEM (~4x smaller over the wire)
    // Browser transparently decompresses via Content-Encoding: gzip.
    s_server->on("/", HTTP_GET, [](AsyncWebServerRequest *req) {
        AsyncWebServerResponse *r = req->beginResponse_P(
            200, "text/html", WEB_INDEX_HTML_GZ, WEB_INDEX_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "max-age=3600");
        req->send(r);
    });

    // Battery service actions

    // ===== Clone Explorer =====
    // Batch scan of SBS register space — reports which registers respond and what they return.
    // Runs mostly 0xFF-returning reads for sealed/non-existent regs; useful to find
    // vendor-specific regs on clone chips that don't implement TI MAC commands.

    // ===== Clone Deep Probe =====

    // Challenge Harvester — write value N times, record response after each write.
    // For studying pseudo-random challenge generators (e.g. reg 0xEE on PTL clone).
    //   GET /api/batt/clone/harvest?reg=0xEE&writeVal=0x0000&count=100&readLen=16
    // Returns compact JSON: [{"w":"0xNNNN","r":"hex"}, ...]

    // Raw block-write to any SBS register (bypasses the standard SMBus block format
    // which prepends a length byte). Use for clones that expect raw payload.
    //   POST reg=0xNN&data=HEX&len=N

    // PEC-enabled variant of SBS writes — some strict SMBus devices/clones
    // silently drop non-PEC writes. Retry unseal keys + anything else with PEC.
    //   POST reg=0xNN&type=word&value=0xNNNN
    //   POST reg=0xNN&type=block&data=HEX

    // =====================================================================
    // MAC Response Brute — different angle: TI-standard flow is
    //   writeWord(0x00, cmd); then readBlock(0x00) — reads cmd-specific data.
    // For each MAC value 0x0000..0xFFFF: write cmd, read block back from 0x00,
    // log ANY response whose content is non-default.
    // Default response is what we get with MAC 0x0000 (reading current cmd latch).
    // Any MAC returning DIFFERENT data = a real command that returns something.
    // =====================================================================

    // MAC Transition Brute — writes MAC_A, then MAC_B, reads between them.
    // Hypothesis: clone's "publish cell voltage" response only appears after
    // a TRANSITION between specific MAC values. Scan N combinations fast.
    //   GET /api/batt/clone/trans_brute?macA=0x0000&from=0x0000&to=0x00FF
    //       For each B in [from..to], sequence: write(A), read#1, write(B), read#2.
    //       Report only responses where bytes 2+ are non-0xFF.

    // Read reg 0x00 rapidly N times onboard, return only unique non-echo responses.
    //   GET /api/batt/clone/async_catch?count=1000&intervalUs=0
    // Broader transition brute — sweep both macA AND macB, catch all publish packets.
    // macA varies in small range while macB does full sweep. Logs every
    // distinct publish packet (by first 4 bytes after 81 F0 marker).
    //   GET /api/batt/clone/broad_brute?macA_from=0x0000&macA_to=0x0100&macA_step=0x10&macB_to=0x03FF

    // Inject frame test — write a 81F0-formatted frame to reg 0x44 (ManufacturerBlockAccess)
    // or arbitrary reg, then read back from 0x44 and 0x00 to see if the chip
    // interpreted it as a valid command.
    //   POST reg=0x44&frame=81F00001000012345678AABB

    // Persistent background publish logger — runs a low-priority task that
    // does a small transition-brute every pollSec seconds, captures any new
    // publish packet, logs to circular buffer for later download.
    //   POST /api/batt/clone/logger_start?pollSec=30
    //   GET  /api/batt/clone/logger_dump
    //   POST /api/batt/clone/logger_stop

    // DataFlash dump: sweep all DF addresses 0x4000-0x7FFF in ranges, try to read
    // each via MAC 0x44 (ManufacturerBlockAccess). Even if sealed, some DF areas
    // may be readable on clone chips (PTL may have incomplete seal enforcement).
    //   GET /api/batt/clone/dfdump?from=0x4000&to=0x40FF

    // SH366000 family commands test — PTL clone may use SH366000 silicon which
    // mimicks BQ40Z307 surface. These are non-TI MAC subcommands specific to SH.
    //   GET /api/batt/clone/sh366000_test

    // HMAC timing attack — measure response time for MAC 0x0000 challenge + HMAC.
    // If chip does non-constant-time HMAC verify, first-byte-wrong vs last-byte-wrong
    // will differ in timing. Report median and stddev of response delay per key.
    //   POST /api/batt/clone/timing_attack?samples=100

    // Periodic-publish watcher — poll reg 0x00 every intervalMs for count samples,
    // log any distinct packet seen. Good for catching time-based publishes.
    //   GET /api/batt/clone/watch?count=500&intervalMs=50

    // (Original synchronous brute retained for small ranges)
    // Brute-force writes to reg 0x00 (ManufacturerAccess) and monitor for
    // state changes in vendor regs.
    //   GET /api/batt/clone/mac_brute?from=0x0000&to=0x0010&probe=0xEE,0xF0

    // HMAC-SHA1 challenge-response unseal (newer bq40z30x firmware).
    // POST ?key=<64-hex-chars> (32 bytes)
    // Returns: {ok, challenge:hex, result:"Unsealed OK"/"Rejected"/...}

    // Diagnostic endpoint — raw SBS / MAC reads + arbitrary unseal keys.
    // Examples:
    //   /api/batt/diag?mac=0x0070                     -> MAC block read (ChemID)
    //   /api/batt/diag?sbs=0x20&type=string           -> ManufacturerName
    //   /api/batt/diag?sbs=0x54&type=dword            -> OperationStatus
    //   /api/batt/diag?unseal=0xABCD,0x1234           -> custom key pair
    s_server->on("/api/wifi/save", HTTP_POST, [](AsyncWebServerRequest *req) {},
        NULL,
        [](AsyncWebServerRequest *req, uint8_t *data, size_t len, size_t index, size_t total) {
            JsonDocument doc;
            deserializeJson(doc, data, len);
            const char* ssid = doc["ssid"];
            const char* pass = doc["pass"];
            if (!ssid) { req->send(400, "text/plain", "missing ssid"); return; }
            WifiManager::saveCredentials(ssid, pass ? pass : "");
            req->send(200, "text/plain", "Saved. Reboot to connect to: " + String(ssid));
        });

    s_server->on("/api/wifi/clear", HTTP_GET, [](AsyncWebServerRequest *req) {
        WifiManager::clearCredentials();
        req->send(200, "text/plain", "WiFi credentials cleared. Reboot to go to AP mode.");
    });

    // Async WiFi scan — start. Returns immediately; results polled via /scan_results.
    // Note: while scanning the AP radio briefly hops channels, so connected
    // clients see a ~1-3s hiccup but don't fully disconnect.
    s_server->on("/api/wifi/scan", HTTP_POST, [](AsyncWebServerRequest *req) {
        int16_t st = WiFi.scanComplete();
        if (st == WIFI_SCAN_RUNNING) {
            req->send(200, "text/plain", "scan already in progress");
            return;
        }
        // true=async, false=show_hidden
        int16_t n = WiFi.scanNetworks(true, false);
        if (n == WIFI_SCAN_FAILED) {
            req->send(500, "text/plain", "scan start failed");
            return;
        }
        req->send(200, "text/plain", "scan started");
    });

    s_server->on("/api/wifi/scan_results", HTTP_GET, [](AsyncWebServerRequest *req) {
        int16_t n = WiFi.scanComplete();
        JsonDocument doc;
        if (n == WIFI_SCAN_RUNNING) {
            doc["done"] = false;
        } else if (n == WIFI_SCAN_FAILED || n < 0) {
            doc["done"] = true;
            doc["nets"].to<JsonArray>();  // empty
        } else {
            doc["done"] = true;
            JsonArray nets = doc["nets"].to<JsonArray>();
            for (int i = 0; i < n; i++) {
                JsonObject o = nets.add<JsonObject>();
                o["ssid"] = WiFi.SSID(i);
                o["rssi"] = WiFi.RSSI(i);
                o["ch"]   = WiFi.channel(i);
                o["enc"]  = (WiFi.encryptionType(i) == WIFI_AUTH_OPEN) ? 0 : 1;
            }
            WiFi.scanDelete();  // free results after reporting
        }
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/status", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument doc;
        doc["mode"] = WifiManager::currentMode();
        doc["ssid"] = WifiManager::getSSID();
        doc["ip"] = WifiManager::getIP();
        doc["heap"] = ESP.getFreeHeap();
        doc["uptime"] = millis();
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    });

    // ELRS firmware upload
    // Max accepted firmware size (ELRS is ~400KB, headroom for big builds)
    static const size_t MAX_FW_SIZE = 2 * 1024 * 1024;

    // Diagnostic: heap + PSRAM + flash state. Helps isolate upload failures.
    s_server->on("/api/sys/mem", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument d;
        d["heap_free"]     = ESP.getFreeHeap();
        d["heap_min"]      = ESP.getMinFreeHeap();
        d["heap_total"]    = ESP.getHeapSize();
        d["psram_free"]    = ESP.getFreePsram();
        d["psram_total"]   = ESP.getPsramSize();
        d["psram_min"]     = ESP.getMinFreePsram();
        d["largest_block"] = ESP.getMaxAllocHeap();
        d["largest_psram"] = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
        d["flash_fw_size"] = WebState::flashState.fw_size;
        d["flash_fw_recv"] = WebState::flashState.fw_received;
        d["flash_fw_buf"]  = WebState::flashState.fw_data ? "allocated" : "null";
        d["flash_stage"]   = WebState::flashState.stage;
        d["flash_offset"]  = WebState::flashState.flash_offset;
        d["flash_progress"] = WebState::flashState.progress_pct;
        d["flash_in_progress"] = WebState::flashState.in_progress;
        d["flash_last_result"] = WebState::flashState.lastResult;
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // Start flashing (after upload)

    // GET /api/flash/status — lets the UI poll progress over HTTP without
    // relying on the WebSocket broadcast (which only runs every second and
    // only updates the main flash card's DOM ids).

    // ===== Receiver firmware DUMP (READ_FLASH via ROM bootloader) =====
    // Reads the attached ESP32-C3 / S2 / S3 receiver's SPI flash over UART1
    // through the same physical Port B pins that the upload flow uses.
    // User must have the receiver in DFU/bootloader mode (hold BOOT + power
    // cycle). Runs in a background task; poll status and then GET the
    // binary.

    // Erase a flash region on the attached RX (RX must be in ROM bootloader).
    // Intended use: wipe OTA-select sector to force boot into secondary app,
    // wipe NVS to factory-reset, etc. Caller MUST power-cycle the RX afterwards
    // (we leave the ROM in a "ready to reboot" state but don't send the reboot).

    // Fast flash-region integrity check. ROM computes MD5 over the
    // requested range and returns 16 raw bytes (or 32 ASCII hex from
    // some ROMs — ESPFlasher::spiFlashMd5 handles both). ~600x faster
    // than readback for verifying writes.
    //
    //  POST /api/flash/md5  form: offset=<hex>&size=<hex>
    //  -> {"md5": "ab12…", "offset": 0x10000, "size": 0x130000}
    // Synchronous small-region flash read. Returns hex (2 chars/byte) in the
    // response body. No background task, no polling — the entire read happens
    // inside the request handler so you can verify a freshly-flashed image
    // within a single DFU session (the async /api/flash/dump/* path requires
    // multiple round-trips and often loses DFU between them).
    //  POST /api/flash/read_bytes  form: offset=<hex>&size=<hex, max 2048>
    // Passive UART sniffer for RX boot diagnostics. Opens Serial1 at the
    // requested baud, reads bytes for `ms` milliseconds, returns hex + ASCII
    // rendering. Used to catch ESP-IDF ROM boot banner (74880 baud default
    // on ESP32-C3) or ELRS app-level output. Does NOT transmit — so RX is
    // undisturbed, user just power-cycles RX while we listen.
    //   POST /api/bridge/listen  form: baud=<int>&ms=<int, max 8000>

    // Erase a full partition by looping erase_region chunks. Use to wipe
    // the entire app1 (MILELRS) partition which is 1.88 MB — exceeds
    // the single-call 64 KB cap. Blocking, ~5-10 s total.
    //
    //  POST /api/flash/erase_partition  form: offset=<hex>&size=<hex>&chunk=0x10000

    // Chip detection — reads CHIP_DETECT_MAGIC_VALUE + MAC over the same
    // Port B UART. RX must be in ROM DFU (hold BOOT + power-cycle). Cheap
    // one-round-trip sanity check before any flash op.

    // Full dual-slot receiver identity in ONE DFU session. Chip info + OTADATA
    // + app0 scan + app1 scan. Frontend uses this to render the Receiver
    // overview + Slots cards without burning N separate DFU cycles.
    //   POST /api/elrs/receiver_info

    // Send MSP-over-CRSF "set RX WiFi mode" (MSP function 0x0E). Mirrors what
    // the ELRS Configurator / OpenTX Lua script sends. RX handler at
    // [rx_main.cpp:1228] defers by 500 ms then flips connectionState to
    // wifiUpdate → SoftAP "ExpressLRS RX" at 10.0.0.1.
    //
    // Actual packet layout derived from
    // [hardware/bayckrc_c3_dual/elrs_3_6_3_src/src/lib/Handset/CRSF.cpp:79]
    // (SetMspV2Request): the MSP header byte is 0x50 (NOT 0x30 as some 3rd-
    // party docs say), with length field being 2 bytes LE.
    //   Frame: C8 0B 7A EC EA  50 00 0E 00 00 00  <mspCRC>  <crsfCRC>
    //          addr len type dest orig  status flags func_lo func_hi len_lo len_hi  crc  crc
    //   mspCRC  = CRC8-DVB-S2(0xD5, init 0) over [flags..payload] i.e. bytes[1..5+0]
    //   crsfCRC = CRC8-DVB-S2(0xD5, init 0) over [type..mspCRC] i.e. frameSize-1 bytes
    //
    //   POST /api/elrs/enable_wifi  [form: inverted=0|1]

    // Exit stub / ROM cleanly — sends CMD_RUN_USER_CODE (0xD3).
    // Use this when RX is stuck in the in-app stub (from a prior CRSF-bl
    // trigger) or in ROM DFU and we want it to jump to the OTADATA-selected
    // app without requiring a physical power-cycle.

    // Send the CRSF "reboot to bootloader" command (the 5-byte "bl" frame
    // `EC 04 32 62 6C <crc>`). ELRS 3.x firmware on ESP32 handles this by
    // NOT rebooting to ROM — it enters an in-app esptool stub that speaks
    // the SYNC/FLASH_BEGIN/DATA/END/READ_FLASH/SPI_FLASH_MD5 protocol on
    // the SAME UART at the SAME baud. No hardware DFU, no power-cycle.
    //
    // After calling this: the plate must switch into ESPFlasher mode on
    // Port B UART without renegotiating baud. Then every existing flash /
    // dump / otadata endpoint just works.
    //
    // Works on vanilla ELRS 3.x AND MILELRS (MILELRS inherits the handler).

    // ===== OTADATA atomic select =====
    // ESP-IDF OTADATA record format (32 bytes):
    //   0..3  ota_seq      u32  (highest wins)
    //   4..23 seq_label    char[20]
    //   24..27 ota_state   u32  (0xFFFFFFFF = undefined = valid-on-next-boot)
    //   28..31 crc         u32  (crc32_le over ota_seq, init 0xFFFFFFFF)
    //
    // Active slot = (max_seq - 1) & 1. So:
    //   slot 0 requires max_seq ∈ {1, 3, 5, ...} (odd)
    //   slot 1 requires max_seq ∈ {2, 4, 6, ...} (even)
    //
    // Safe update algorithm: pick new_seq = max(seq0, seq1) + 1, bump parity
    // if needed, write the record to the sector that currently holds the
    // LOWER seq (alternating-sector write). RX must be in DFU mode.

    // Read current OTADATA state (RX must be in DFU).

    // ===== CRSF endpoints =====
    s_server->on("/api/crsf/start", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!PinPort::acquire(PinPort::PORT_B, PORT_UART, "crsf")) {
            req->send(409, "text/plain", "Port B busy — switch to UART in System → Port B Mode");
            return;
        }
        bool inv = req->hasParam("inverted") ? req->getParam("inverted")->value() == "1" : false;
        WebState::crsf.inverted = inv;
        CRSFService::begin(&Serial1,
                           PinPort::rx_pin(PinPort::PORT_B),
                           PinPort::tx_pin(PinPort::PORT_B),
                           420000, inv);
        CRSFConfig::init();
        WebState::crsf.enabled = true;
        req->send(200, "text/plain", inv ? "CRSF started (inverted)" : "CRSF started");
    });

    s_server->on("/api/crsf/state", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument d;
        d["running"]   = CRSFService::isRunning();
        if (CRSFService::isRunning()) {
            const auto &st = CRSFService::state();
            d["connected"]    = st.connected;
            d["total_frames"] = st.total_frames;
            d["bad_crc"]      = st.bad_crc;
            if (st.link.valid) {
                JsonObject l = d["link"].to<JsonObject>();
                l["rssi1"] = (int8_t)st.link.uplink_rssi1 * -1;
                l["lq"]    = st.link.uplink_link_quality;
                l["snr"]   = st.link.uplink_snr;
                l["rf"]    = st.link.rf_mode;
            }
            const auto &dev = CRSFConfig::deviceInfo();
            if (dev.valid) {
                JsonObject dv = d["device"].to<JsonObject>();
                dv["name"]   = dev.name;
                dv["fw"]     = dev.sw_ver;
                dv["hw"]     = dev.hw_ver;
                dv["serial"] = dev.serial;
                dv["fields"] = dev.field_count;
            }
        }
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/api/crsf/stop", HTTP_POST, [](AsyncWebServerRequest *req) {
        CRSFService::end();
        WebState::crsf.enabled = false;
        PinPort::release(PinPort::PORT_B);
        req->send(200, "text/plain", "CRSF stopped");
    });

    s_server->on("/api/crsf/ping", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        CRSFConfig::reset();
        CRSFConfig::requestDeviceInfo();
        req->send(200, "text/plain", "Ping sent");
    });

    s_server->on("/api/crsf/params", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        CRSFConfig::requestAllParameters();
        req->send(200, "text/plain", "Requesting parameters...");
    });

    // Blind param-read sweep for firmwares where DEVICE_INFO returns
    // field_count=0 (happens on some Bayck / fork ELRS builds). Iterates
    // IDs 1..max and sends a read request for each; params that reply get
    // cached in CRSFConfig.
    s_server->on("/api/crsf/read_params_blind", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        int maxId = req->hasParam("max", true)
            ? req->getParam("max", true)->value().toInt() : 30;
        if (maxId < 1) maxId = 1;
        if (maxId > 80) maxId = 80;
        // Space the reads 40 ms apart so we don't overrun the RX
        for (int id = 1; id <= maxId; id++) {
            CRSFService::sendParameterRead((uint8_t)id, 0);
            delay(40);
        }
        req->send(200, "text/plain", String("Sweep sent for IDs 1..") + maxId);
    });

    // List all cached params (filled by /api/crsf/params or /api/crsf/read_params_blind)
    s_server->on("/api/crsf/params_list", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument d;
        d["count"] = CRSFConfig::paramCount();
        JsonArray arr = d["params"].to<JsonArray>();
        for (int i = 1; i <= 80; i++) {
            const CRSFConfig::Param *p = CRSFConfig::paramById((uint8_t)i);
            if (!p || !p->complete) continue;
            JsonObject o = arr.add<JsonObject>();
            o["id"]        = p->id;
            o["parent_id"] = p->parent_id;
            o["type"]      = p->type;
            o["name"]      = p->name;
            o["value_num"] = p->value_num;
            if (p->value_text.length() > 0) o["value_text"] = p->value_text;
            if (p->unit.length() > 0)       o["unit"]       = p->unit;
            if (p->options.length() > 0)    o["options"]    = p->options;
            o["min"]       = p->min_val;
            o["max"]       = p->max_val;
            o["hidden"]    = p->hidden;
        }
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/api/crsf/write", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        if (!req->hasParam("id") || !req->hasParam("value")) {
            req->send(400, "text/plain", "missing id/value"); return;
        }
        uint8_t id = req->getParam("id")->value().toInt();
        String v = req->getParam("value")->value();
        const auto *p = CRSFConfig::paramById(id);
        if (!p) { req->send(404, "text/plain", "unknown param id"); return; }
        bool ok = CRSFConfig::writeParamAuto(id, v);
        if (!ok) {
            req->send(400, "text/plain", "param type not writable");
            return;
        }
        req->send(200, "text/plain", "OK");
    });

    s_server->on("/api/crsf/bind", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        CRSFService::cmdRxBind();
        req->send(200, "text/plain", "Bind command sent");
    });

    s_server->on("/api/crsf/wifi", HTTP_POST, [](AsyncWebServerRequest *req) {
        // ELRS exposes "Enable WiFi" as a PARAM_COMMAND on the receiver.
        // To trigger it we need the param tree loaded (via /api/crsf/params),
        // then write value=1 (click/start) to its id.
        if (!CRSFService::isRunning()) {
            req->send(400, "text/plain", "CRSF not running");
            return;
        }
        if (CRSFConfig::paramCount() == 0) {
            req->send(400, "text/plain", "Read parameters first (Read Params)");
            return;
        }
        const CRSFConfig::Param *p = CRSFConfig::findCommandParamByName("wifi");
        if (!p) {
            req->send(404, "text/plain", "WiFi command param not found — check RX firmware");
            return;
        }
        bool ok = CRSFConfig::writeParamByte(p->id, 1);  // 1 = start/click
        if (!ok) {
            req->send(500, "text/plain", "Failed to send param write");
            return;
        }
        String msg = "Triggered: ";
        msg += p->name;
        msg += " (id=" + String(p->id) + ")";
        req->send(200, "text/plain", msg);
    });

    s_server->on("/api/crsf/reboot", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!CRSFService::isRunning()) { req->send(400, "text/plain", "CRSF not running"); return; }
        CRSFService::cmdReboot();
        req->send(200, "text/plain", "Reboot command sent");
    });

    // Clear uploaded firmware

    // ===== OTA firmware update =====

    // Query GitHub releases/latest API; cache asset URL + tag for subsequent pull.

    // Start background download + flash from the previously checked asset URL.

    // ===== USB mode (descriptor selection) =====
    s_server->on("/api/usb/mode", HTTP_GET, [](AsyncWebServerRequest *req) {
        UsbDescriptorMode prefer = UsbMode::load();
        UsbDescriptorMode act    = UsbMode::active();
        JsonDocument j;
        j["active"]         = (int)act;
        j["active_name"]    = UsbMode::name(act);
        j["preferred"]      = (int)prefer;
        j["preferred_name"] = UsbMode::name(prefer);
        j["reboot_pending"] = (act != prefer);
        // Back-compat: older UI builds still read `current` / `current_name`.
        j["current"]        = (int)act;
        j["current_name"]   = UsbMode::name(act);
        JsonArray arr = j["modes"].to<JsonArray>();
        for (int i = 0; i <= USB_MODE_USB2I2C; i++) {
            JsonObject o = arr.add<JsonObject>();
            o["id"]   = i;
            o["name"] = UsbMode::name((UsbDescriptorMode)i);
        }
        String out; serializeJson(j, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/api/usb/mode", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!req->hasParam("mode", true)) {
            req->send(400, "text/plain", "Missing 'mode' form param");
            return;
        }
        int v = req->getParam("mode", true)->value().toInt();
        if (v < 0 || v > USB_MODE_USB2I2C) {
            req->send(400, "text/plain", "Invalid mode");
            return;
        }
        UsbMode::save((UsbDescriptorMode)v);
        req->send(200, "text/plain", "Saved. Reboot to apply.");
    });

    // Port B mode selector ------------------------------------------------
    s_server->on("/api/port/status", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument j;
        auto d = PinPort::def(PinPort::PORT_B);
        j["name"]       = d ? d->name : "B";
        j["pin_a"]      = d ? d->pin_a : -1;
        j["pin_b"]      = d ? d->pin_b : -1;
        PortMode cur    = PinPort::currentMode(PinPort::PORT_B);
        const char *ow  = PinPort::currentOwner(PinPort::PORT_B);
        j["mode"]       = (int)cur;
        j["mode_name"]  = PinPort::modeName(cur);
        j["owner"]      = ow ? ow : "";
        PortMode pref   = PinPort::preferredMode(PinPort::PORT_B);
        j["preferred"]  = (int)pref;
        j["preferred_name"] = PinPort::modeName(pref);
        JsonArray arr   = j["modes"].to<JsonArray>();
        for (int i = 0; i < (int)PORT_MODE_COUNT; i++) {
            JsonObject o = arr.add<JsonObject>();
            o["id"]   = i;
            o["name"] = PinPort::modeName((PortMode)i);
        }
        String out; serializeJson(j, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/api/port/preferred", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!req->hasParam("mode", true)) {
            req->send(400, "text/plain", "Missing 'mode' form param");
            return;
        }
        int v = req->getParam("mode", true)->value().toInt();
        if (v < 0 || v >= (int)PORT_MODE_COUNT) {
            req->send(400, "text/plain", "Invalid mode id");
            return;
        }
        PinPort::setPreferredMode(PinPort::PORT_B, (PortMode)v);
        // Also try to apply immediately: release current, re-acquire.
        // If a feature is actively using the port in a different mode,
        // release() will tear it down; the feature will notice on next loop.
        PinPort::release(PinPort::PORT_B);
        if ((PortMode)v != PORT_IDLE) {
            PinPort::acquire(PinPort::PORT_B, (PortMode)v, "boot");
        }
        req->send(200, "text/plain", "Saved");
    });

    s_server->on("/api/port/release", HTTP_POST, [](AsyncWebServerRequest *req) {
        PinPort::release(PinPort::PORT_B);
        req->send(200, "text/plain", "Released");
    });

    // Passive listener diagnostic — open UART at a requested baud, count
    // every byte that arrives in N ms, return a hex preview. Doesn't send
    // anything — just confirms whether the wire carries a signal at all.
    // Useful when autodetect says "no signal" and we want to distinguish
    // "nothing ever arrived" (wiring/power issue) from "arrived but didn't
    // look like what we expected".
    s_server->on("/api/port/probe_rx", HTTP_POST, [](AsyncWebServerRequest *req) {
        uint32_t baud = req->hasParam("baud", true)
            ? strtoul(req->getParam("baud", true)->value().c_str(), nullptr, 0) : 115200;
        uint32_t ms = req->hasParam("ms", true)
            ? strtoul(req->getParam("ms", true)->value().c_str(), nullptr, 0) : 1000;
        if (ms > 5000) ms = 5000;
        bool swap = req->hasParam("swap", true)
            ? req->getParam("swap", true)->value() == "1"
            : PinPort::swapped(PinPort::PORT_B);

        PinPort::setSwapped(PinPort::PORT_B, swap);
        PinPort::release(PinPort::PORT_B);
        if (!PinPort::acquire(PinPort::PORT_B, PORT_UART, "probe_rx")) {
            req->send(409, "text/plain", "Port B busy");
            return;
        }
        int rxPin = PinPort::rx_pin(PinPort::PORT_B);
        int txPin = PinPort::tx_pin(PinPort::PORT_B);
        Serial1.end();
        Serial1.begin(baud, SERIAL_8N1, rxPin, txPin);

        static uint8_t buf[512];
        size_t got = 0;
        uint32_t start = millis();
        while (millis() - start < ms && got < sizeof(buf)) {
            if (Serial1.available()) buf[got++] = (uint8_t)Serial1.read();
            else delay(1);
        }

        JsonDocument d;
        d["baud"]   = baud;
        d["ms"]     = ms;
        d["swap"]   = swap;
        d["rx_pin"] = rxPin;
        d["tx_pin"] = txPin;
        d["bytes"]  = got;
        // Preview first 64 bytes as hex
        String hex; hex.reserve(132);
        for (size_t i = 0; i < got && i < 64; i++) {
            char b[4]; snprintf(b, sizeof(b), "%02x", buf[i]); hex += b;
        }
        d["hex_preview"] = hex;
        // Count non-idle bytes (anything other than 0x00 or 0xFF)
        int interesting = 0;
        for (size_t i = 0; i < got; i++) if (buf[i] != 0x00 && buf[i] != 0xFF) interesting++;
        d["non_idle_count"] = interesting;

        PinPort::release(PinPort::PORT_B);
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // Manual swap override (advanced) — toggles PinPort pin_a/pin_b
    // assignment for I2C/UART and re-acquires if port is live.
    s_server->on("/api/port/swap", HTTP_POST, [](AsyncWebServerRequest *req) {
        bool swap = !PinPort::swapped(PinPort::PORT_B);
        if (req->hasParam("swap", true)) {
            swap = req->getParam("swap", true)->value() == "1";
        }
        PinPort::setSwapped(PinPort::PORT_B, swap);
        JsonDocument d;
        d["swapped"] = PinPort::swapped(PinPort::PORT_B);
        d["tx_pin"]  = PinPort::tx_pin(PinPort::PORT_B);
        d["rx_pin"]  = PinPort::rx_pin(PinPort::PORT_B);
        d["sda_pin"] = PinPort::sda_pin(PinPort::PORT_B);
        d["scl_pin"] = PinPort::scl_pin(PinPort::PORT_B);
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // Auto-detect wiring — tries both pin_a↔pin_b assignments and reports
    // which one produced a valid signal. Saves swap flag to NVS on success.
    //   signal=crsf   → listen for CRSF frame start 0xC8 @ 420000 8N1
    //   signal=sbus   → listen for SBUS start 0x0F @ 100000 8E2 inverted
    //   signal=ibus   → listen for iBus header 0x20,0x40 @ 115200 8N1
    //   signal=i2c    → I2C bus scan 0x08..0x77, success if ≥1 ACK
    //   signal=elrs_rom → ROM bootloader SYNC @ 115200 (user must hold BOOT)
    // Returns JSON with "swap_used", "detected", and the swap flag state.
    s_server->on("/api/port/autodetect", HTTP_POST, [](AsyncWebServerRequest *req) {
        String signal = req->hasParam("signal", true)
            ? req->getParam("signal", true)->value() : "crsf";

        auto tryOnce = [&](bool swap, unsigned long waitMs) -> bool {
            PinPort::setSwapped(PinPort::PORT_B, swap);
            PinPort::release(PinPort::PORT_B);

            if (signal == "i2c") {
                if (!PinPort::acquire(PinPort::PORT_B, PORT_I2C, "autodetect")) return false;
                Wire1.end();
                int sda = PinPort::sda_pin(PinPort::PORT_B);
                int scl = PinPort::scl_pin(PinPort::PORT_B);
                pinMode(sda, INPUT_PULLUP);
                pinMode(scl, INPUT_PULLUP);
                Wire1.begin(sda, scl);
                Wire1.setClock(100000);
                Wire1.setTimeOut(30);
                for (uint8_t addr = 0x08; addr <= 0x77; addr++) {
                    Wire1.beginTransmission(addr);
                    if (Wire1.endTransmission() == 0) return true;
                }
                return false;
            }

            // UART-based detection — pick baud/framing per signal.
            if (!PinPort::acquire(PinPort::PORT_B, PORT_UART, "autodetect")) return false;
            Serial1.end();
            int rxPin = PinPort::rx_pin(PinPort::PORT_B);
            int txPin = PinPort::tx_pin(PinPort::PORT_B);

            uint32_t baud; uint32_t cfg; bool invert;
            uint8_t syncByte1 = 0, syncByte2 = 0; bool needTwo = false;
            if (signal == "crsf") {
                baud = 420000; cfg = SERIAL_8N1; invert = false;
                syncByte1 = 0xC8;  // CRSF broadcast address
            } else if (signal == "sbus") {
                baud = 100000; cfg = SERIAL_8E2; invert = true;
                syncByte1 = 0x0F;
            } else if (signal == "ibus") {
                baud = 115200; cfg = SERIAL_8N1; invert = false;
                syncByte1 = 0x20; syncByte2 = 0x40; needTwo = true;
            } else if (signal == "elrs_rom") {
                // ROM bootloader doesn't emit unsolicited bytes. We send a SYNC
                // and wait for any response byte. A SYNC is 36 bytes with SLIP
                // framing; we'll crudely emit 0xC0 then flood 0x07 0x07 0x12 0x20
                // followed by 32× 0x55, then listen.
                baud = 115200; cfg = SERIAL_8N1; invert = false;
                syncByte1 = 0x00; // any byte counts
            } else {
                baud = 420000; cfg = SERIAL_8N1; invert = false; syncByte1 = 0xC8;
            }

            Serial1.begin(baud, cfg, rxPin, txPin, invert);

            if (signal == "elrs_rom") {
                // emit SYNC framing
                static const uint8_t syncPayload[] = {0x07, 0x07, 0x12, 0x20};
                Serial1.write((uint8_t)0xC0);
                Serial1.write((uint8_t)0x00);       // direction
                Serial1.write((uint8_t)0x08);       // SYNC cmd
                Serial1.write((uint8_t)36); Serial1.write((uint8_t)0);  // size LE
                Serial1.write((uint8_t)0); Serial1.write((uint8_t)0);   // cksum x4 (ignored by ROM for SYNC)
                Serial1.write((uint8_t)0); Serial1.write((uint8_t)0);
                Serial1.write(syncPayload, sizeof(syncPayload));
                for (int i = 0; i < 32; i++) Serial1.write((uint8_t)0x55);
                Serial1.write((uint8_t)0xC0);
                Serial1.flush();
            }

            uint32_t start = millis();
            bool sawFirst = false;
            while (millis() - start < waitMs) {
                if (!Serial1.available()) { delay(2); continue; }
                uint8_t b = (uint8_t)Serial1.read();
                if (signal == "elrs_rom") {
                    // Any non-0xC0-only byte = bootloader replied
                    if (b != 0xC0) return true;
                }
                if (!needTwo) {
                    if (b == syncByte1) return true;
                } else {
                    if (!sawFirst) { sawFirst = (b == syncByte1); }
                    else if (b == syncByte2) return true;
                    else sawFirst = (b == syncByte1);
                }
            }
            return false;
        };

        bool origSwap = PinPort::swapped(PinPort::PORT_B);
        unsigned long perSideMs = 1500;

        bool okDirect = tryOnce(false, perSideMs);
        bool okSwapped = false;
        if (!okDirect) {
            okSwapped = tryOnce(true, perSideMs);
        }

        // Leave the working swap (or revert to original if neither worked).
        bool detected = okDirect || okSwapped;
        bool finalSwap = okDirect ? false : (okSwapped ? true : origSwap);
        PinPort::setSwapped(PinPort::PORT_B, finalSwap);
        PinPort::release(PinPort::PORT_B);

        JsonDocument d;
        d["signal"]      = signal;
        d["detected"]    = detected;
        d["swap_used"]   = detected ? finalSwap : (bool)false;
        d["swapped_now"] = PinPort::swapped(PinPort::PORT_B);
        d["tx_pin"]      = PinPort::tx_pin(PinPort::PORT_B);
        d["rx_pin"]      = PinPort::rx_pin(PinPort::PORT_B);
        d["sda_pin"]     = PinPort::sda_pin(PinPort::PORT_B);
        d["scl_pin"]     = PinPort::scl_pin(PinPort::PORT_B);
        d["note"]        = detected
            ? (finalSwap ? "signal found with pins SWAPPED — flag persisted to NVS"
                         : "signal found with DIRECT pinout (no swap needed)")
            : "no signal detected in either pinout — check GND/power, or signal type";
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== Setup wizard — HOST / BRIDGE + device preset =====
    // One-shot configurator that derives both (USB descriptor) and
    // (Port B electrical mode) from the user's intent:
    //   device  ∈ {battery, receiver, motor, advanced}
    //   role    ∈ {host, bridge}
    // HOST   = the board itself talks to the device (CDC-only USB).
    // BRIDGE = PC talks to the device via the board as transparent proxy.
    //   - battery  → USB2I2C (CP2112 HID)
    //   - receiver → USB2TTL (CDC + UART pump)
    //   - advanced → USB2TTL
    //   - motor    → not supported (no PC-side toolchain for servo/DShot);
    //                UI doesn't expose this combo.

    auto setupStringsToPreset = [](const String &device, const String &role,
                                   UsbDescriptorMode &outUsb, PortMode &outPort,
                                   String &outErr) -> bool {
        bool bridge = (role == "bridge");
        if (device == "battery") {
            outUsb  = bridge ? USB_MODE_USB2I2C : USB_MODE_CDC;
            outPort = PORT_I2C;
        } else if (device == "receiver") {
            outUsb  = bridge ? USB_MODE_USB2TTL : USB_MODE_CDC;
            outPort = PORT_UART;
        } else if (device == "motor") {
            if (bridge) { outErr = "motor has no bridge mode"; return false; }
            outUsb  = USB_MODE_CDC;
            outPort = PORT_PWM;
        } else if (device == "advanced") {
            outUsb  = bridge ? USB_MODE_USB2TTL : USB_MODE_CDC;
            outPort = bridge ? PORT_UART : PORT_GPIO;
        } else if (device == "idle") {
            outUsb  = USB_MODE_CDC;
            outPort = PORT_IDLE;
        } else {
            outErr = "unknown device";
            return false;
        }
        return true;
    };

    auto presetToStrings = [](UsbDescriptorMode usb, PortMode port,
                              String &outDevice, String &outRole) {
        // Infer (device, role) from the raw pair. USB being CDC implies HOST.
        if (usb == USB_MODE_USB2I2C) {
            outDevice = "battery";  outRole = "bridge"; return;
        }
        if (usb == USB_MODE_USB2TTL) {
            // USB2TTL is shared by Receiver BRIDGE and Advanced BRIDGE; the
            // distinction is only UX sugar — we surface Receiver by default.
            outDevice = "receiver"; outRole = "bridge"; return;
        }
        // CDC — role is always HOST; device is derived from Port B.
        outRole = "host";
        switch (port) {
            case PORT_I2C:  outDevice = "battery";  break;
            case PORT_UART: outDevice = "receiver"; break;
            case PORT_PWM:  outDevice = "motor";    break;
            case PORT_GPIO: outDevice = "advanced"; break;
            case PORT_IDLE: outDevice = "idle";     break;
            default:        outDevice = "unknown";  break;
        }
    };

    s_server->on("/api/setup/status", HTTP_GET,
        [presetToStrings](AsyncWebServerRequest *req) {
            UsbDescriptorMode activeUsb = UsbMode::active();
            UsbDescriptorMode prefUsb   = UsbMode::load();
            PortMode activePort = PinPort::currentMode(PinPort::PORT_B);
            PortMode prefPort   = PinPort::preferredMode(PinPort::PORT_B);

            String activeDev, activeRole, prefDev, prefRole;
            presetToStrings(activeUsb, activePort, activeDev, activeRole);
            presetToStrings(prefUsb, prefPort, prefDev, prefRole);

            JsonDocument d;
            JsonObject a = d["active"].to<JsonObject>();
            a["device"]    = activeDev;
            a["role"]      = activeRole;
            a["usb"]       = UsbMode::name(activeUsb);
            a["port"]      = PinPort::modeName(activePort);
            a["owner"]     = PinPort::currentOwner(PinPort::PORT_B);

            JsonObject p = d["preferred"].to<JsonObject>();
            p["device"]    = prefDev;
            p["role"]      = prefRole;
            p["usb"]       = UsbMode::name(prefUsb);
            p["port"]      = PinPort::modeName(prefPort);

            d["reboot_pending"] = (activeUsb != prefUsb);

            String out; serializeJson(d, out);
            req->send(200, "application/json", out);
        });

    s_server->on("/api/setup/apply", HTTP_POST,
        [setupStringsToPreset](AsyncWebServerRequest *req) {
            if (!req->hasParam("device", true) || !req->hasParam("role", true)) {
                req->send(400, "text/plain", "Need form params 'device' and 'role'");
                return;
            }
            String device = req->getParam("device", true)->value();
            String role   = req->getParam("role", true)->value();
            UsbDescriptorMode usb;
            PortMode port;
            String err;
            if (!setupStringsToPreset(device, role, usb, port, err)) {
                req->send(400, "text/plain", err);
                return;
            }

            UsbDescriptorMode prevUsb = UsbMode::load();
            bool usbChanged = (usb != prevUsb);

            UsbMode::save(usb);
            PinPort::setPreferredMode(PinPort::PORT_B, port);

            // Apply Port B immediately (no reboot needed for Port B changes).
            PinPort::release(PinPort::PORT_B);
            if (port != PORT_IDLE) {
                PinPort::acquire(PinPort::PORT_B, port, "setup");
            }

            JsonDocument d;
            d["ok"]             = true;
            d["device"]         = device;
            d["role"]           = role;
            d["usb"]            = UsbMode::name(usb);
            d["port"]           = PinPort::modeName(port);
            d["reboot_needed"]  = usbChanged;
            d["reboot_reason"]  = usbChanged
                ? "USB descriptor fixed at boot — reboot to re-enumerate"
                : "";
            String out; serializeJson(d, out);
            req->send(200, "application/json", out);
        });

    s_server->on("/api/cp2112/log", HTTP_GET, [](AsyncWebServerRequest *req) {
        static char buf[4096];
        int n = cp2112_log_dump(buf, sizeof(buf));
        AsyncResponseStream *r = req->beginResponseStream("text/plain");
        r->printf("seq=%lu\n", (unsigned long)cp2112_log_seq());
        r->write((const uint8_t*)buf, n);
        req->send(r);
    });

    s_server->on("/api/cp2112/info", HTTP_GET, [](AsyncWebServerRequest *req) {
        char buf[128];
        cp2112_ep_info(buf, sizeof(buf));
        req->send(200, "text/plain", buf);
    });

    // SMBus transaction log (ring buffer)

    // I2C preflight diagnostics
    s_server->on("/api/i2c/preflight", HTTP_GET, [](AsyncWebServerRequest *req) {
        auto r = SMBus::preflight();
        JsonDocument d;
        d["sdaOk"] = r.sdaOk;
        d["sclOk"] = r.sclOk;
        d["busOk"] = r.busOk;
        d["batteryAck"] = r.batteryAck;
        d["devCount"] = r.devCount;
        JsonArray devs = d["devices"].to<JsonArray>();
        for (int i = 0; i < r.devCount && i < 8; i++)
            devs.add(String("0x") + String(r.devAddrs[i], HEX));
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== BLHeli 4way passthrough (TCP server on :4321) =====
    s_server->on("/api/esc/4way/start", HTTP_POST, [](AsyncWebServerRequest *req) {
        BLHeli4Way::start(SIGNAL_OUT);
        req->send(200, "text/plain", "4way server started on port 4321");
    });
    s_server->on("/api/esc/4way/stop", HTTP_POST, [](AsyncWebServerRequest *req) {
        BLHeli4Way::stop();
        req->send(200, "text/plain", "stopped");
    });
    s_server->on("/api/esc/4way/status", HTTP_GET, [](AsyncWebServerRequest *req) {
        const auto &st = BLHeli4Way::status();
        JsonDocument d;
        d["running"]         = BLHeli4Way::isRunning();
        d["connected"]       = st.clientConnected;
        d["commands"]        = st.commandsHandled;
        d["escReadBytes"]    = st.escReadBytes;
        d["escWriteBytes"]   = st.escWriteBytes;
        d["escErrors"]       = st.escErrors;
        d["lastCmdName"]     = st.lastCmdName;
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== BLHeli ESC probe (early / skeleton) =====
    s_server->on("/api/esc/probe", HTTP_POST, [](AsyncWebServerRequest *req) {
        BLHeliInfo info;
        bool ok = BLHeli::probeInfo(SIGNAL_OUT, &info, 2000);
        JsonDocument d;
        d["detected"] = info.detected;
        d["firmwareName"] = info.firmwareName;
        d["ok"] = ok;
        d["note"] = "Full BLHeli 4way passthrough not yet implemented — probe only checks presence";
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== Servo state + sweep recorder =====
    s_server->on("/api/servo/state", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument d;
        WebState::Lock lock;
        d["active"]        = WebState::servo.active;
        d["sweep"]         = WebState::servo.sweep;
        d["pulseUs"]       = WebState::servo.pulseUs;
        d["freq"]          = WebState::servo.freq;
        d["sweepMinUs"]    = WebState::servo.sweepMinUs;
        d["sweepMaxUs"]    = WebState::servo.sweepMaxUs;
        d["sweepPeriodMs"] = WebState::servo.sweepPeriodMs;
        d["markedMinUs"]   = WebState::servo.markedMinUs;
        d["markedMaxUs"]   = WebState::servo.markedMaxUs;
        d["observedMinUs"] = WebState::servo.observedMinUs;
        d["observedMaxUs"] = WebState::servo.observedMaxUs;
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== ESC Telemetry (KISS / BLHeli_32 10-byte frame on ELRS_RX UART) =====
    s_server->on("/api/esc/telem/start", HTTP_POST, [](AsyncWebServerRequest *req) {
        int poles = 14;
        if (req->hasParam("poles", true)) poles = req->getParam("poles", true)->value().toInt();
        if (poles < 2 || poles > 40) poles = 14;
        ESCTelem::start((uint8_t)poles);
        req->send(200, "text/plain", String("ESC telem started, polePairs=") + ESCTelem::polePairs());
    });
    s_server->on("/api/esc/telem/stop", HTTP_POST, [](AsyncWebServerRequest *req) {
        ESCTelem::stop();
        req->send(200, "text/plain", "stopped");
    });
    s_server->on("/api/esc/telem/state", HTTP_GET, [](AsyncWebServerRequest *req) {
        const auto &st = ESCTelem::state();
        JsonDocument d;
        d["running"]     = st.running;
        d["connected"]   = st.connected;
        d["frameCount"]  = st.frameCount;
        d["crcErrors"]   = st.crcErrors;
        d["frameRateHz"] = st.frameRateHz;
        d["polePairs"]   = ESCTelem::polePairs();
        if (st.frameCount > 0) {
            d["temp_c"]          = st.last.temp_c;
            d["voltage_V"]       = st.last.voltage_cV / 100.0f;
            d["current_A"]       = st.last.current_cA / 100.0f;
            d["consumption_mAh"] = st.last.consumption_mAh;
            uint32_t erpm = (uint32_t)st.last.erpm * 100;
            d["erpm"]            = erpm;
            uint8_t pp = ESCTelem::polePairs();
            d["rpm"]             = pp > 0 ? erpm / pp : 0;
        }
        d["maxTemp"]         = st.maxTemp;
        d["maxCurrent_A"]    = st.maxCurrent_cA / 100.0f;
        d["maxErpm"]         = (uint32_t)st.maxErpm * 100;
        d["peakVoltage_V"]   = st.peakVoltage_cV / 100.0f;
        d["minVoltage_V"]    = st.minVoltage_cV / 100.0f;
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // ===== RC Protocol Sniffer (SBUS / iBus / PPM) =====
    s_server->on("/api/rc/start", HTTP_POST, [](AsyncWebServerRequest *req) {
        if (!req->hasParam("proto", true)) { req->send(400, "text/plain", "need proto"); return; }
        String p = req->getParam("proto", true)->value();
        RCProto proto = RC_PROTO_NONE;
        if (p == "sbus") proto = RC_PROTO_SBUS;
        else if (p == "ibus") proto = RC_PROTO_IBUS;
        else if (p == "ppm")  proto = RC_PROTO_PPM;
        else if (p == "auto") { RCSniffer::autoDetect(); req->send(200, "text/plain",
            String("Auto-detected: ") + RCSniffer::protoName(RCSniffer::state().proto)); return; }
        else { req->send(400, "text/plain", "proto must be sbus/ibus/ppm/auto"); return; }
        RCSniffer::start(proto);
        req->send(200, "text/plain", String("Started ") + RCSniffer::protoName(proto));
    });

    s_server->on("/api/rc/stop", HTTP_POST, [](AsyncWebServerRequest *req) {
        RCSniffer::stop();
        req->send(200, "text/plain", "stopped");
    });

    s_server->on("/api/rc/state", HTTP_GET, [](AsyncWebServerRequest *req) {
        const auto &st = RCSniffer::state();
        JsonDocument d;
        d["proto"]        = RCSniffer::protoName(st.proto);
        d["running"]      = RCSniffer::isRunning();
        d["connected"]    = st.connected;
        d["channelCount"] = st.channelCount;
        d["frameCount"]   = st.frameCount;
        d["crcErrors"]    = st.crcErrors;
        d["frameRateHz"]  = st.frameRateHz;
        d["failsafe"]     = st.failsafe;
        d["lostFrame"]    = st.lostFrame;
        JsonArray ch = d["channels"].to<JsonArray>();
        for (uint8_t i = 0; i < st.channelCount && i < 16; i++) ch.add(st.channels[i]);
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    s_server->on("/api/i2c/scan", HTTP_GET, [](AsyncWebServerRequest *req) {
        // Scan 0x08..0x77 on Wire1 (battery bus)
        AsyncResponseStream *r = req->beginResponseStream("text/plain");
        int found = 0;
        for (uint8_t addr = 0x08; addr <= 0x77; addr++) {
            Wire1.beginTransmission(addr);
            uint8_t err = Wire1.endTransmission();
            if (err == 0) {
                r->printf("0x%02X  ACK\n", addr);
                found++;
            }
        }
        r->printf("--\nScanned 0x08..0x77, found %d device(s)\n", found);
        req->send(r);
    });

    s_server->on("/api/usb/reboot", HTTP_POST, [](AsyncWebServerRequest *req) {
        req->send(200, "text/plain", "Rebooting...");
        delay(200);
        ESP.restart();
    });

    // HTTP fallback for UI `send()` when the WebSocket is down. Accepts the
    // same JSON body that would be sent through WS and dispatches to the
    // shared handler. Prevents commands from silently 404-ing when the user
    // momentarily lost WS (mobile suspend, AP hop).
    s_server->on("/api/ws", HTTP_POST,
        [](AsyncWebServerRequest *req) {
            // Unused final handler — body is consumed in onBody below.
        },
        nullptr,
        [](AsyncWebServerRequest *req, uint8_t *data, size_t len, size_t index, size_t total) {
            if (index == 0 && len == total) {
                handleWsMsg(nullptr, data, len);
                req->send(200, "text/plain", "OK");
            } else if (total > 0 && index + len == total) {
                // Multi-chunk body — unlikely for WS commands (<1KB), but accept anyway.
                handleWsMsg(nullptr, data, len);
                req->send(200, "text/plain", "OK");
            }
        });

    s_server->onNotFound([](AsyncWebServerRequest *req) {
        req->send(404, "text/plain", "Not found");
    });

    s_server->begin();
    s_running = true;
    Serial.println("[Web] Server started on :80");
}

void WebServer::stop() {
    if (!s_running) return;
    if (s_server) { s_server->end(); delete s_server; s_server = nullptr; }
    if (s_ws) { delete s_ws; s_ws = nullptr; }
    s_running = false;
    Serial.println("[Web] Server stopped");
}

bool WebServer::isRunning() { return s_running; }

void WebServer::loop() {
    if (!s_running) return;

    // CRSF loop (parse incoming, handle params)
    if (CRSFService::isRunning()) {
        CRSFService::loop();
        CRSFConfig::loop();
    }

    uint32_t now = millis();
    if (now - s_lastBroadcast > 1000) {
        broadcastTelemetry();
        s_lastBroadcast = now;
        s_ws->cleanupClients();
    }

    // Execute flash request on a dedicated task. Running RoutesFlash::executeFlash() on
    // the main loop blocks every other main-loop consumer (CRSF, WS broadcast,
    // battery service) for ~3 minutes; worse, the idle-task watchdog on core 0
    // fired mid-flash and rebooted the plate. The dump path already uses a
    // task for the same reason.
    if (WebState::flashState.flash_request && !WebState::flashState.in_progress) {
        WebState::flashState.flash_request = false;
        xTaskCreate([](void *){
            RoutesFlash::executeFlash();
            vTaskDelete(nullptr);
        }, "elrs_flash", 8192, nullptr, 1, nullptr);
    }

    // Execute pending battery service actions from web thread
    if (WebState::battSvc.pending != WebState::BS_NONE) {
        bool ok = false;
        switch (WebState::battSvc.pending) {
            case WebState::BS_UNSEAL:  ok = DJIBattery::unseal(); break;
            case WebState::BS_CLEARPF: ok = DJIBattery::clearPFProper(); break;
            case WebState::BS_SEAL:    ok = DJIBattery::seal(); break;
            default: break;
        }
        WebState::battSvc.lastResult = ok ? "OK" : "FAILED";
        WebState::battSvc.pending = WebState::BS_NONE;
    }
}
