#include "web_ui.h"
#include "web_ui_gz.h"  // auto-generated by scripts/gzip_web_ui.py
#include <Arduino.h>

// NOTE: raw HTML below is the source for the gzip pre-build script
// (scripts/gzip_web_ui.py reads the raw-string literal from this file).
// At runtime we serve WEB_INDEX_HTML_GZ; the raw copy below is marked static
// so the linker dead-strips it from the final firmware (saves ~78KB flash).
__attribute__((unused)) static const char WEB_INDEX_HTML_RAW[] PROGMEM = R"HTML(<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FPV MultiTool</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='6' fill='%230f0f1e'/><path d='M18 3 L7 18 h6 l-3 11 L25 13 h-6 l3-10z' fill='%230cf'/></svg>">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: #0f0f1e; color: #e0e0e0;
  font-family: -apple-system,BlinkMacSystemFont,sans-serif;
  max-width: 1700px;      /* lets 3 card columns fit on 2K after container padding + grid gaps */
  margin: 0 auto;
  padding: clamp(8px, 2vw, 20px);
}
h1 {
  color: #0af;
  font-size: clamp(18px, 2.4vw, 26px);
  margin-bottom: 10px;
  text-align: center;
  padding: 0 90px;        /* keep title clear of the fixed #connStatus badge on narrow viewports */
}
.ws-tabs { display: flex; justify-content: center; gap: 6px; margin-bottom: 8px; }
.ws-tab { padding: 10px 20px; background: #12122a; border-radius: 8px 8px 0 0; cursor: pointer; font-size: 15px; font-weight: 600; user-select: none; color: #889; border-bottom: 2px solid transparent; }
.ws-tab.active { background: #1a1a2e; color: #0cf; border-bottom: 2px solid #0cf; }
.tabs { display: flex; justify-content: center; flex-wrap: wrap; gap: 4px; margin-bottom: 15px; }
.tab { padding: 10px 14px; background: #1a1a2e; border-radius: 6px; cursor: pointer; white-space: nowrap; font-size: 14px; user-select: none; }
.tab.active { background: #0066aa; color: #fff; }
/* Cards flow into multiple columns on wide screens, single column on phones.
   Tracks stretch with 1fr but each card is capped at 520px and centred inside its cell,
   so on 2K we get 3 readable columns instead of 2 bloated ones. */
.tab-content { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 420px), 1fr)); gap: 12px; align-items: start; justify-content: center; }
.card { background: #1a1a2e; border-radius: 8px; padding: 16px; min-width: 0; max-width: 520px; width: 100%; justify-self: center; }
.card h2 { color: #0cf; font-size: clamp(14px, 1.4vw, 17px); margin-bottom: 12px; }
.row { display: flex; justify-content: space-between; align-items: center; padding: 6px 0; border-bottom: 1px solid #222; }
.row:last-child { border-bottom: none; }
.label { color: #888; font-size: 13px; }
.value { color: #fff; font-size: 15px; font-weight: 600; }
.big { font-size: 32px; color: #0cf; text-align: center; margin: 10px 0; }
input[type=range] { width: 100%; margin: 8px 0; }
input[type=number], input[type=text], input[type=password] { width: 100%; padding: 8px; background: #0a0a14; border: 1px solid #333; border-radius: 4px; color: #fff; font-size: 14px; margin: 4px 0; }
button { padding: 10px 16px; background: #0066aa; color: #fff; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; margin: 4px 2px; }
button.danger { background: #aa2222; }
button.success { background: #22aa44; }
button:disabled { background: #444; cursor: not-allowed; }
.status { display: inline-block; padding: 4px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
.status.on { background: #2a4; color: #fff; }
.status.off { background: #666; color: #ccc; }
.status.warn { background: #c82; color: #fff; }
.bar { height: 20px; background: #0a0a14; border-radius: 4px; overflow: hidden; margin: 8px 0; }
.bar-fill { height: 100%; background: linear-gradient(90deg,#2a4,#0af); transition: width 0.2s; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
.warning { color: #f66; font-size: 12px; padding: 8px; background: #2a0a0a; border-radius: 4px; margin: 8px 0; }
.ok { color: #6f6; }
#connStatus { position: fixed; top: 10px; right: 10px; font-size: 12px; padding: 4px 8px; border-radius: 12px; z-index: 10; }
#connStatus.connected { background: #2a4; color: #fff; }
#connStatus.disconnected { background: #a42; color: #fff; }

/* Mobile responsive */
@media (max-width: 600px) {
  body { padding: 6px; }
  h1 { font-size: 16px; padding: 0 60px; margin-bottom: 6px; }
  .ws-tabs { gap: 2px; }
  .ws-tab { padding: 8px 12px; font-size: 13px; }
  .tabs { gap: 2px; }
  .tab { padding: 8px 10px; font-size: 12px; }
  .tab-content { grid-template-columns: 1fr !important; }
  .card { padding: 12px; max-width: 100% !important; }
  .card h2 { font-size: 14px; }
  .big { font-size: 26px; }
  .grid { grid-template-columns: 1fr 1fr; gap: 4px; }
  .row { padding: 4px 0; }
  .label { font-size: 12px; }
  .value { font-size: 13px; }
  button { padding: 8px 12px; font-size: 13px; }
  input[type=number], input[type=text], input[type=password] { font-size: 14px; }
  pre { font-size: 10px !important; max-height: 200px !important; }
}
</style>
</head>
<body>
<div id="connStatus" class="disconnected">...</div>
<h1>FPV MultiTool</h1>

<div class="ws-tabs" id="wsTabs">
  <div class="ws-tab active" onclick="showWorkspace('batt')">Battery Lab</div>
  <div class="ws-tab" onclick="showWorkspace('fpv')">FPV Tools</div>
  <div class="ws-tab" onclick="showWorkspace('sys')">System</div>
</div>

<div id="ws-batt">
  <div class="tabs">
    <div class="tab active" onclick="showTab('battery')">Battery</div>
  </div>
</div>
<div id="ws-fpv" style="display:none">
  <div class="tabs">
    <div class="tab active" onclick="showTab('servo')">Servo</div>
    <div class="tab" onclick="showTab('motor')">Motor</div>
    <div class="tab" onclick="showTab('elrs')">ELRS Flash</div>
    <div class="tab" onclick="showTab('crsf')">CRSF</div>
  </div>
</div>
<div id="ws-sys" style="display:none">
  <div class="tabs">
    <div class="tab active" onclick="showTab('sys')">System</div>
    <div class="tab" onclick="showTab('usb')">USB</div>
    <div class="tab" onclick="showTab('ota')">OTA</div>
  </div>
</div>

<!-- ===== SERVO ===== -->
<div id="tab-servo" class="tab-content" style="display:none">
  <div class="card">
    <h2>Servo Tester (GPIO 2)</h2>
    <div class="big" id="servoUs">1500 μs</div>
    <input type="range" id="servoSlider" min="500" max="2500" value="1500" step="10" oninput="onServo()">
    <div class="grid">
      <button onclick="setServo(500)">Min 500</button>
      <button onclick="setServo(1500)">Center</button>
    </div>
    <div class="grid">
      <button onclick="setServo(2500)">Max 2500</button>
      <button class="danger" onclick="servoStop()">STOP</button>
    </div>
    <div class="row"><span class="label">Frequency:</span>
      <span>
        <button onclick="setServoFreq(50)">50 Hz</button>
        <button onclick="setServoFreq(330)">330 Hz</button>
      </span>
    </div>
    <div class="row"><span class="label">Sweep mode:</span>
      <button onclick="toggleSweep()"><span id="sweepBtn">Start</span></button>
    </div>
  </div>
</div>

<!-- ===== MOTOR ===== -->
<div id="tab-motor" class="tab-content" style="display:none">
  <div class="card">
    <h2>Motor Tester DShot (GPIO 2)</h2>
    <div class="warning">⚠ СНИМИ ПРОПЕЛЛЕРЫ перед тестом!</div>
    <div class="row"><span class="label">Status:</span><span id="motorStatus" class="status off">DISARMED</span></div>
    <div class="row"><span class="label">Protocol:</span>
      <select id="dshotSpeed" onchange="setDshotSpeed()" style="padding:6px;background:#0a0a14;color:#fff;border:1px solid #333;">
        <option value="150">DShot150</option>
        <option value="300" selected>DShot300</option>
        <option value="600">DShot600</option>
      </select>
    </div>
    <div class="big"><span id="throttleVal">0</span> <span style="color:#888;font-size:18px">/ 2000</span></div>
    <div class="bar"><div class="bar-fill" id="throttleBar" style="width:0%"></div></div>
    <input type="range" id="throttleSlider" min="0" max="2000" value="0" disabled oninput="onThrottle()">
    <div class="grid">
      <button class="success" id="armBtn" onclick="motorArm()">ARM</button>
      <button class="danger" onclick="motorDisarm()">DISARM</button>
    </div>
    <div class="grid">
      <button onclick="motorBeep()">Beep ESC</button>
      <button onclick="setThrottle(0)">Zero</button>
    </div>
    <div style="margin-top:14px;padding-top:10px;border-top:1px solid #333;">
      <div class="row">
        <span class="label">Max throttle:</span>
        <span class="value"><span id="maxThrottleVal">2000</span> / 2000</span>
      </div>
      <input type="range" id="maxThrottleSlider" min="100" max="2000" step="100" value="2000" oninput="onMaxThrottle()">
      <div class="row" style="margin-top:8px"><span class="label">Direction (armed):</span></div>
      <div class="grid">
        <button onclick="motorDirCW()">Dir CW</button>
        <button onclick="motorDirCCW()">Dir CCW</button>
      </div>
      <div class="row" style="margin-top:8px"><span class="label">3D mode (armed):</span></div>
      <div class="grid">
        <button onclick="motor3DOn()">3D ON</button>
        <button onclick="motor3DOff()">3D OFF</button>
      </div>
    </div>
  </div>
</div>

<!-- ===== BATTERY ===== -->
<div id="tab-battery" class="tab-content">
  <div class="card">
    <h2>Smart Battery</h2>
    <div class="row">
      <span class="label">Connected:</span>
      <span>
        <span id="battConn" class="status off">NO</span>
        <span id="battDevType" class="status off" style="display:none">-</span>
        <span id="battSealStatus" class="status warn" style="display:none">SEALED</span>
      </span>
    </div>
    <div class="big" id="battSOC">-- %</div>
    <div class="bar"><div class="bar-fill" id="battBar" style="width:0%"></div></div>
    <div class="grid">
      <div class="row"><span class="label">Voltage:</span><span class="value" id="battVolt">-</span></div>
      <div class="row"><span class="label">Current:</span><span class="value" id="battCurr">-</span></div>
      <div class="row"><span class="label">Avg Current:</span><span class="value" id="battAvgCurr">-</span></div>
      <div class="row"><span class="label">Temp:</span><span class="value" id="battTemp">-</span></div>
      <div class="row"><span class="label">SOH:</span><span class="value" id="battSOH">-</span></div>
      <div class="row"><span class="label">Cycles:</span><span class="value" id="battCycle">-</span></div>
      <div class="row"><span class="label">Capacity:</span><span class="value" id="battCap">-</span></div>
      <div class="row"><span class="label">Design:</span><span class="value" id="battDesign">-</span></div>
    </div>
    <div class="grid" style="margin-top:8px">
      <div class="row"><span class="label">Time to empty:</span><span class="value" id="battTTE">-</span></div>
      <div class="row"><span class="label">Time to full:</span><span class="value" id="battTTF">-</span></div>
      <div class="row"><span class="label">Chg I/V:</span><span class="value" id="battChg">-</span></div>
      <div class="row"><span class="label">Status:</span><span class="value" id="battStatusBits">-</span></div>
    </div>
  </div>

  <div class="card">
    <h2>Cells (<span id="cellsSync">async</span>)</h2>
    <div id="cellsGrid"></div>
    <div class="row"><span class="label">Delta:</span><span class="value" id="cellDelta">-</span></div>
    <div class="row"><span class="label">Pack V (sync):</span><span class="value" id="packV">-</span></div>
  </div>

  <div class="card">
    <h2>Status</h2>
    <div class="row">
      <span class="label">Operation:</span>
      <span class="value" id="opStatus">-</span>
    </div>
    <div class="row" style="color:#555;font-size:10px;font-family:monospace"><span id="opDecoded">-</span></div>
    <div class="row">
      <span class="label">Safety:</span>
      <span class="value" id="safetyStatus" style="color:#6f6">-</span>
    </div>
    <div class="row" style="color:#555;font-size:10px;font-family:monospace"><span id="safetyDecoded">-</span></div>
    <div class="row">
      <span class="label">PF (Permanent Failure):</span>
      <span class="value" id="pfStatus">-</span>
    </div>
    <div class="row" style="font-size:10px;font-family:monospace"><span id="pfDecoded">-</span></div>
    <div class="row">
      <span class="label">Manufacturing:</span>
      <span class="value" id="mfgStatus">-</span>
    </div>
    <div class="row" style="color:#555;font-size:10px;font-family:monospace"><span id="mfgDecoded">-</span></div>
  </div>

  <div class="card">
    <h2>Battery Info</h2>
    <div class="row"><span class="label">Model:</span><span class="value" id="battModel" style="color:#f0f">-</span></div>
    <div class="row"><span class="label">Config:</span><span class="value" id="battConfig">-</span></div>
    <div class="row"><span class="label">Manufacturer:</span><span class="value" id="battMfr">-</span></div>
    <div class="row"><span class="label">Device:</span><span class="value" id="battDev">-</span></div>
    <div class="row"><span class="label">Chemistry:</span><span class="value" id="battChem">-</span></div>
    <div class="row"><span class="label">S/N / Date:</span><span class="value" id="battSN">-</span></div>
    <div class="row"><span class="label">DJI S/N:</span><span class="value" id="battDjiSN" style="display:none">-</span></div>
    <div class="row"><span class="label">Chip:</span><span class="value" id="battChip">-</span></div>
    <div class="row"><span class="label">FW / HW:</span><span class="value" id="battFwHw">-</span></div>
    <div id="keyWarning" class="warning" style="display:none">
      ⚠ Эта модель требует DJI per-pack ключ.<br>
      Публичные ключи отсутствуют. Unseal/Clear PF работать не будут.
    </div>
  </div>

  <div class="card">
    <h2>Service (advanced)</h2>
    <div class="warning">⚠ Требует unseal. Для Mavic 2+/Mavic 3/Mavic 4 ключи DJI не опубликованы.</div>
    <div class="grid">
      <button onclick="battAction('unseal')">Unseal</button>
      <button onclick="battAction('clearpf')">Clear PF</button>
    </div>
    <div class="grid">
      <button onclick="battAction('seal')">Seal</button>
      <button onclick="battAction('reset')">Soft Reset</button>
    </div>
    <button class="danger" onclick="battAction('fullservice')" style="width:100%;margin-top:4px;">Full Service (unseal + clear + seal)</button>
    <div id="battActionResult" style="margin-top:10px;color:#ff0"></div>
  </div>

  <div class="card">
    <h2>Unseal Wizard</h2>
    <div class="row"><span class="label">Profile:</span>
      <select id="unsealProfile" style="flex:1;background:#222;color:#fff;border:1px solid #555;padding:4px" onchange="loadProfile()"></select>
    </div>
    <div id="unsealKeyList" style="margin:8px 0;font-size:11px;color:#aaa"></div>
    <div class="grid">
      <button onclick="tryAllKeys()">Try All Keys</button>
      <button onclick="tryFasKeys()">Try FAS Keys</button>
    </div>
    <div style="margin-top:8px;font-size:12px">Manual key pair:</div>
    <div style="display:flex;gap:4px;margin-top:4px">
      <input id="unsealW1" placeholder="0x7EE0" style="flex:1;background:#222;color:#fff;border:1px solid #555;padding:4px;font-family:monospace">
      <input id="unsealW2" placeholder="0xCCDF" style="flex:1;background:#222;color:#fff;border:1px solid #555;padding:4px;font-family:monospace">
      <button onclick="tryManualKey()">Send</button>
    </div>
    <div id="unsealResult" style="margin-top:8px;color:#0f0;font-size:12px"></div>
  </div>

  <div class="card">
    <h2>MAC Command Runner</h2>
    <div style="display:flex;gap:4px">
      <select id="macSelect" style="flex:1;background:#222;color:#fff;border:1px solid #555;padding:4px;font-size:11px"></select>
      <button onclick="runMacCmd()">Execute</button>
    </div>
    <div id="macDesc" style="margin:4px 0;font-size:11px;color:#888"></div>
    <pre id="macResult" style="background:#000;color:#0f0;font-size:11px;padding:6px;margin:4px 0;max-height:120px;overflow:auto">(idle)</pre>
  </div>

  <div class="card" style="grid-column:1/-1;max-width:100%">
    <h2>Data Flash Editor (BQ9003/BQ40z307)</h2>
    <div class="warning">
      ⚠ Для чтения/записи Data Flash батарея должна быть <b>unsealed</b>.<br>
      Запись неправильных значений может вывести батарею из строя!
    </div>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin:8px 0">
      <button onclick="dfLoadMap()">Load Map</button>
      <button onclick="dfReadAll()" id="dfReadAllBtn" disabled>Read All Values</button>
      <button onclick="dfExport()" id="dfExportBtn" disabled>Export JSON</button>
      <span id="dfStatus" style="color:#888;font-size:12px;align-self:center"></span>
    </div>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin:4px 0;padding:6px;background:#12122a;border-radius:4px;align-items:center">
      <span style="color:#888;font-size:11px">Compare:</span>
      <label style="font-size:11px;cursor:pointer;color:#0af">
        Import A <input type="file" accept=".json" onchange="dfImportSnapshot(event, 'A')" style="display:none">
      </label>
      <label style="font-size:11px;cursor:pointer;color:#f0a">
        Import B <input type="file" accept=".json" onchange="dfImportSnapshot(event, 'B')" style="display:none">
      </label>
      <label style="font-size:11px"><input type="checkbox" id="dfCompareMode" onchange="dfFilterApply()"> Compare mode</label>
      <button onclick="dfUseCurrentAs('A')" style="font-size:11px;padding:3px 8px">A = current</button>
      <button onclick="dfUseCurrentAs('B')" style="font-size:11px;padding:3px 8px">B = current</button>
      <button onclick="dfClearSnapshots()" style="font-size:11px;padding:3px 8px">Clear</button>
      <span id="dfSnapshotStatus" style="color:#888;font-size:11px"></span>
    </div>
    <div id="dfFilter" style="display:none;margin:6px 0">
      <input id="dfSearch" type="text" placeholder="Filter by name..." oninput="dfFilterApply()" style="width:200px;background:#222;color:#fff;border:1px solid #555;padding:4px;font-size:12px">
      <label style="font-size:12px;margin-left:8px"><input type="checkbox" id="dfDiffOnly" onchange="dfFilterApply()"> Only changed</label>
    </div>
    <div id="dfTree" style="font-size:12px;max-height:500px;overflow:auto"></div>
  </div>

  <div class="card">
    <h2>I2C Diagnostics</h2>
    <div class="grid">
      <button onclick="i2cPreflight()">Preflight Check</button>
      <button onclick="i2cScan()">Full Bus Scan</button>
    </div>
    <pre id="preflightResult" style="background:#000;color:#0af;font-size:11px;padding:6px;margin:4px 0;display:none"></pre>
    <pre id="i2cScanResult" style="background:#000;color:#0af;font-size:11px;padding:6px;margin:4px 0;display:none"></pre>
  </div>

  <div class="card">
    <h2>SMBus Transaction Log</h2>
    <p style="color:#888;font-size:11px;margin:0 0 6px">
      Все I2C транзакции на шине батареи. Включи логирование, чтобы записывать.
    </p>
    <div style="display:flex;gap:8px;align-items:center">
      <button onclick="smbLogToggle()" id="smbLogToggleBtn">Enable Logging</button>
      <button onclick="smbLogRefresh()">Refresh</button>
      <button onclick="smbLogExport()">Export .txt</button>
      <label><input type="checkbox" id="smbLogAuto" onchange="smbLogAutoToggle()"> Auto 1s</label>
    </div>
    <pre id="smbLog" style="background:#000;color:#0f0;font-size:11px;padding:8px;margin:6px 0;max-height:300px;overflow:auto;white-space:pre-wrap">(logging off)</pre>
  </div>

  <div class="card">
    <h2>SMBus Console</h2>
    <div style="display:flex;gap:4px;flex-wrap:wrap">
      <input id="smbAddr" value="0x0B" placeholder="addr" style="width:50px;background:#222;color:#fff;border:1px solid #555;padding:4px;font-family:monospace">
      <select id="smbOp" style="background:#222;color:#fff;border:1px solid #555;padding:4px">
        <option value="readWord">Read Word</option>
        <option value="readBlock">Read Block</option>
        <option value="writeWord">Write Word</option>
        <option value="writeBlock">Write Block</option>
        <option value="macBlockRead">MAC Block Read</option>
        <option value="macCmd">MAC Command</option>
      </select>
      <input id="smbReg" placeholder="reg 0x00" style="width:60px;background:#222;color:#fff;border:1px solid #555;padding:4px;font-family:monospace">
      <input id="smbData" placeholder="data (hex)" style="flex:1;min-width:80px;background:#222;color:#fff;border:1px solid #555;padding:4px;font-family:monospace">
      <button onclick="smbExec()">Send</button>
    </div>
    <pre id="smbResult" style="background:#000;color:#0f0;font-size:11px;padding:6px;margin:4px 0;max-height:200px;overflow:auto">(idle)</pre>
    <div style="display:flex;gap:4px;margin-top:4px">
      <button onclick="battSnapshot()">Snapshot JSON</button>
    </div>
  </div>
</div>

<!-- ===== ELRS FLASH ===== -->
<div id="tab-elrs" class="tab-content" style="display:none">
  <div class="card">
    <h2>ELRS Receiver Flasher</h2>
    <div class="warning">
      <b>Инструкция:</b><br>
      1. Подключи приёмник: <b>RX→GPIO43, TX→GPIO44, GND, 5V</b><br>
      2. Переведи приёмник в <b>DFU режим</b> (зажми кнопку на нём и подай питание)<br>
      3. Загрузи .bin файл ниже и нажми Flash
    </div>
    <div class="row"><span class="label">Firmware (.bin / .bin.gz / .elrs):</span></div>
    <input type="file" id="fwFile" accept=".bin,.gz,.elrs" onchange="onFwSelect()" style="margin:8px 0; width:100%;">
    <div class="row"><span class="label">Размер:</span><span class="value" id="fwSize">-</span></div>
    <div class="row"><span class="label">Статус:</span><span class="value" id="flashStage">idle</span></div>
    <div class="bar"><div class="bar-fill" id="flashBar" style="width:0%;background:#fa0"></div></div>
    <div class="grid">
      <button class="success" id="uploadBtn" onclick="uploadFw()" disabled>Upload</button>
      <button id="flashBtn" onclick="startFlash()" disabled>Flash!</button>
    </div>
    <button class="danger" onclick="clearFw()" style="width:100%;margin-top:4px;">Clear</button>
    <div id="flashResult" style="margin-top:10px; color:#0f0;"></div>
  </div>
</div>

<!-- ===== CRSF ===== -->
<div id="tab-crsf" class="tab-content" style="display:none">
  <div class="card">
    <h2>CRSF / ELRS Telemetry</h2>
    <div class="warning">
      Подключи RX/TX приёмника к GPIO44/43 (ESP UART), 5V, GND.<br>
      Для инвертированного CRSF (F3/F4 FC) поставь галку.
    </div>
    <div class="row">
      <span class="label">Status:</span>
      <span>
        <span id="crsfStatus" class="status off">OFF</span>
        <span id="crsfConnected" class="status off">NO LINK</span>
      </span>
    </div>
    <div class="row">
      <span class="label">Inverted:</span>
      <span><input type="checkbox" id="crsfInverted"></span>
    </div>
    <div class="grid">
      <button class="success" onclick="crsfStart()">Start</button>
      <button class="danger" onclick="crsfStop()">Stop</button>
    </div>
  </div>

  <div class="card">
    <h2>Link Stats</h2>
    <div class="row"><span class="label">Uplink RSSI:</span><span class="value" id="crsfRssi">- dBm</span></div>
    <div class="row"><span class="label">Link Quality:</span><span class="value" id="crsfLQ">- %</span></div>
    <div class="bar"><div class="bar-fill" id="crsfLqBar" style="width:0%"></div></div>
    <div class="row"><span class="label">SNR:</span><span class="value" id="crsfSnr">- dB</span></div>
    <div class="row"><span class="label">RF Mode:</span><span class="value" id="crsfRf">-</span></div>
    <div class="row"><span class="label">TX Power:</span><span class="value" id="crsfPower">-</span></div>
    <div class="row"><span class="label">Downlink:</span><span class="value" id="crsfDl">-</span></div>
    <div class="row"><span class="label">Frames/Errors:</span><span class="value" id="crsfFrames">0 / 0</span></div>
  </div>

  <div class="card">
    <h2>Channels</h2>
    <div id="channelsGrid"></div>
  </div>

  <div class="card">
    <h2>FC Telemetry</h2>
    <div class="row"><span class="label">Flight Mode:</span><span class="value" id="crsfMode">-</span></div>
    <div class="row"><span class="label">Battery:</span><span class="value" id="crsfBatt">-</span></div>
    <div class="row"><span class="label">Attitude:</span><span class="value" id="crsfAtt">-</span></div>
    <div class="row"><span class="label">GPS:</span><span class="value" id="crsfGPS">-</span></div>
  </div>

  <div class="card">
    <h2>Device Info</h2>
    <div class="row"><span class="label">Name:</span><span class="value" id="crsfDevName">-</span></div>
    <div class="row"><span class="label">FW:</span><span class="value" id="crsfDevFw">-</span></div>
    <div class="row"><span class="label">Serial:</span><span class="value" id="crsfDevSerial">-</span></div>
    <div class="row"><span class="label">Parameters:</span><span class="value" id="crsfDevFields">-</span></div>
    <div class="grid">
      <button onclick="crsfPing()">Ping Device</button>
      <button onclick="crsfReadParams()">Read Params</button>
    </div>
  </div>

  <div class="card">
    <h2>Parameters</h2>
    <div id="crsfParams">No parameters loaded. Click "Read Params" above.</div>
  </div>

  <div class="card">
    <h2>Commands</h2>
    <div class="warning">⚠ Команды шлются на приёмник по адресу 0xEC</div>
    <div class="grid">
      <button class="danger" onclick="crsfBind()">Bind Mode</button>
      <button class="danger" onclick="crsfReboot()">Reboot RX</button>
    </div>
    <div class="warning" style="margin-top:10px;">
      Для смены <b>bind phrase</b> — запусти WiFi mode на приёмнике,
      подключись к его AP <code>ExpressLRS RX</code> (pass <code>expresslrs</code>)
      и открой <code>http://10.0.0.1</code>. Требует сначала <b>Read Params</b>.
    </div>
    <div class="grid">
      <button onclick="crsfEnterWifi()">Enter WiFi Update Mode</button>
    </div>
    <div id="crsfCmdResult" style="margin-top:10px;color:#ff0;"></div>
  </div>
</div>

<!-- ===== SYSTEM ===== -->
<div id="tab-sys" class="tab-content" style="display:none">
  <div class="card">
    <h2>System Info</h2>
    <div class="row"><span class="label">IP:</span><span class="value" id="sysIP">-</span></div>
    <div class="row"><span class="label">Uptime:</span><span class="value" id="sysUptime">-</span></div>
    <div class="row"><span class="label">Free heap:</span><span class="value" id="sysHeap">-</span></div>
    <div class="row"><span class="label">WiFi clients:</span><span class="value" id="sysClients">-</span></div>
  </div>
  <div class="card">
    <h2>WiFi Config</h2>
    <div style="margin-bottom:8px">
      <button onclick="scanWifi()" id="wifiScanBtn">Scan networks</button>
      <span id="wifiScanStatus" style="color:#888;margin-left:8px;font-size:12px"></span>
    </div>
    <div id="wifiScanList" style="margin-bottom:10px"></div>
    <div class="label">SSID:</div>
    <input type="text" id="wifiSSID" placeholder="your WiFi name">
    <div class="label">Password:</div>
    <input type="password" id="wifiPASS" placeholder="password">
    <button onclick="saveWifi()">Save & Connect STA</button>
    <button class="danger" onclick="clearWifi()">Clear (back to AP)</button>
  </div>
</div>

<div id="tab-usb" class="tab-content" style="display:none">
  <div class="card">
    <h2>USB Mode</h2>
    <p style="color:#888;font-size:12px;margin:4px 0 10px">
      Переключает USB-дескриптор платы. <b>Требует перезагрузки</b>.<br>
      • <b>CDC</b> — стандартный USB Serial (прошивка, отладка).<br>
      • <b>USB2TTL</b> — CDC + прозрачный мост на аппаратный UART1.<br>
      • <b>USB2I2C</b> — эмулятор CP2112 HID (DJI Battery Killer, bqStudio, SMBus-инструменты).
    </p>
    <div class="row"><span class="label">Текущий:</span><span class="value" id="usbCurrent">-</span></div>
    <div id="usbModes" style="margin-top:10px;display:flex;flex-direction:column;gap:6px"></div>
    <div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap">
      <button onclick="usbRefresh()">Refresh</button>
      <button onclick="usbApply()" id="usbApplyBtn">Save</button>
      <button class="danger" onclick="usbReboot()">Save &amp; Reboot</button>
    </div>
    <div id="usbMsg" style="margin-top:10px;color:#0f0"></div>
    <p style="color:#f80;font-size:11px;margin:12px 0 0">
      ⚠ В режиме <code>USB2I2C</code> USB-Serial отключается —
      прошивка только через <b>OTA</b> вкладку или физический UART0.
    </p>
  </div>
  <div class="card">
    <h2>CP2112 transaction log</h2>
    <p style="color:#888;font-size:11px;margin:4px 0 8px">
      Каждая транзакция шины от USB2I2C. Колонки: <code>ms dir s=slave7 err=wireErr r=reqLen g=gotLen data…</code>
    </p>
    <pre id="cpLog" style="background:#000;color:#0f0;font-size:11px;padding:8px;max-height:360px;overflow:auto;white-space:pre-wrap;word-break:break-all">(idle)</pre>
    <div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center">
      <button onclick="cpLogRefresh()">Refresh</button>
      <button onclick="cpLogExport()">Export .txt</button>
      <label><input type="checkbox" id="cpLogAuto" checked onchange="cpLogAutoToggle()"> Auto-refresh 1s</label>
      <span id="cpLogStats" style="color:#888;font-size:11px"></span>
    </div>
  </div>
</div>

<div id="tab-ota" class="tab-content" style="display:none">
  <div class="card">
    <h2>OTA Update</h2>
    <div class="row"><span class="label">FW version:</span><span class="value" id="otaFwVer">-</span></div>
    <div class="row"><span class="label">Running:</span><span class="value" id="otaRunning">-</span></div>
    <div class="row"><span class="label">Next slot:</span><span class="value" id="otaNext">-</span></div>
    <div class="row"><span class="label">App size:</span><span class="value" id="otaAppSize">-</span></div>
    <div class="row"><span class="label">Free:</span><span class="value" id="otaFree">-</span></div>
    <div class="row"><span class="label">SDK:</span><span class="value" id="otaSdk">-</span></div>
    <button onclick="otaRefresh()">Refresh info</button>
  </div>
  <div class="card">
    <h2>GitHub releases</h2>
    <div class="row"><span class="label">Repo:</span><span class="value" id="otaRepo">-</span></div>
    <div class="row"><span class="label">Latest:</span><span class="value" id="otaLatest">-</span></div>
    <div class="row"><span class="label">Status:</span><span class="value" id="otaCompare">-</span></div>
    <div style="margin-top:8px">
      <button onclick="otaCheck()" id="otaCheckBtn">Проверить обновления</button>
      <button onclick="otaPull()" id="otaPullBtn" disabled>Установить из GitHub</button>
    </div>
    <div class="row" style="margin-top:10px"><span class="label">Progress:</span><span class="value" id="otaPullStage">-</span></div>
    <div class="bar"><div class="bar-fill" id="otaPullBar" style="width:0%;background:#0af"></div></div>
    <p style="color:#888;font-size:11px;margin:8px 0 0">
      Для онлайн-апдейта плата должна быть в STA-режиме (подключена к WiFi с интернетом).
    </p>
  </div>
  <div class="card">
    <h2>Upload firmware.bin</h2>
    <p style="color:#888;font-size:12px;margin:4px 0 10px">
      PlatformIO: <code>.pio/build/esp32s3/firmware.bin</code>.
      Плата перезагрузится автоматически после прошивки.
    </p>
    <input type="file" id="otaFile" accept=".bin">
    <div class="row"><span class="label">Статус:</span><span class="value" id="otaStage">idle</span></div>
    <div class="bar"><div class="bar-fill" id="otaBar" style="width:0%;background:#0af"></div></div>
    <div style="margin-top:10px">
      <button id="otaBtn" onclick="otaUpload()">Upload & Flash</button>
      <button class="danger" onclick="otaAbort()">Abort</button>
    </div>
    <div id="otaResult" style="margin-top:10px;color:#0f0;word-break:break-word"></div>
  </div>
</div>

<script>
let ws = null, wsOk = false;

function connStatus(ok) {
  wsOk = ok;
  const el = document.getElementById('connStatus');
  el.className = ok ? 'connected' : 'disconnected';
  el.textContent = ok ? '● Connected' : '● Disconnected';
}

function connect() {
  ws = new WebSocket(`ws://${location.host}/ws`);
  ws.onopen = () => connStatus(true);
  ws.onclose = () => { connStatus(false); setTimeout(connect, 2000); };
  ws.onerror = () => ws.close();
  ws.onmessage = (e) => {
    try { handleMsg(JSON.parse(e.data)); } catch(err) {}
  };
}

function send(obj) {
  if (ws && wsOk) ws.send(JSON.stringify(obj));
  else fetch('/api', {method:'POST', body:JSON.stringify(obj)});
}

let _curWs = 'batt';
const _wsDefTab = {batt:'battery', fpv:'servo', sys:'sys'};

function showWorkspace(ws) {
  _curWs = ws;
  document.querySelectorAll('.ws-tab').forEach(e => e.classList.remove('active'));
  event.target.classList.add('active');
  ['batt','fpv','sys'].forEach(w => {
    document.getElementById('ws-'+w).style.display = w === ws ? '' : 'none';
  });
  // Activate the first tab in this workspace
  const wsEl = document.getElementById('ws-'+ws);
  const tabs = wsEl.querySelectorAll('.tab');
  tabs.forEach(t => t.classList.remove('active'));
  if (tabs[0]) tabs[0].classList.add('active');
  showTab(_wsDefTab[ws]);
}

function showTab(name) {
  document.querySelectorAll('.tab-content').forEach(e => e.style.display = 'none');
  document.getElementById('tab-'+name).style.display = '';
  // Mark active tab within current workspace
  const wsEl = document.getElementById('ws-'+_curWs);
  if (wsEl) wsEl.querySelectorAll('.tab').forEach(e => e.classList.remove('active'));
  if (typeof event !== 'undefined' && event && event.target && event.target.classList) event.target.classList.add('active');
  if (name === 'ota') otaRefresh();
  if (name === 'usb') { usbRefresh(); cpLogRefresh(); cpLogAutoToggle(); }
  if (name === 'battery') { loadProfiles(); loadMacCatalog(); }
}

// === SERVO ===
function onServo() {
  const us = +document.getElementById('servoSlider').value;
  document.getElementById('servoUs').textContent = us + ' μs';
  send({cmd:'servo', us});
}
function setServo(us) {
  document.getElementById('servoSlider').value = us;
  onServo();
}
function setServoFreq(hz) { send({cmd:'servoFreq', hz}); }
function servoStop() { send({cmd:'servoStop'}); }
let sweeping = false;
function toggleSweep() {
  sweeping = !sweeping;
  document.getElementById('sweepBtn').textContent = sweeping ? 'Stop' : 'Start';
  send({cmd:'servoSweep', on: sweeping});
}

// === MOTOR ===
let armed = false;
function motorArm() {
  send({cmd:'motorArm'});
}
function motorDisarm() {
  send({cmd:'motorDisarm'});
  document.getElementById('throttleSlider').value = 0;
  onThrottle();
}
function onThrottle() {
  const t = +document.getElementById('throttleSlider').value;
  document.getElementById('throttleVal').textContent = t;
  document.getElementById('throttleBar').style.width = (t/2000*100) + '%';
  send({cmd:'throttle', value: t});
}
function setThrottle(v) { document.getElementById('throttleSlider').value = v; onThrottle(); }
function setDshotSpeed() {
  send({cmd:'dshotSpeed', speed: +document.getElementById('dshotSpeed').value});
}
function motorBeep() { send({cmd:'motorBeep'}); }
function onMaxThrottle() {
  const v = +document.getElementById('maxThrottleSlider').value;
  document.getElementById('maxThrottleVal').textContent = v;
  const slider = document.getElementById('throttleSlider');
  slider.max = v;
  if (+slider.value > v) { slider.value = v; onThrottle(); }
  send({cmd:'motorMaxThrottle', value: v});
}
function motorDirCW()  { if (confirm('Set direction CW (normal)? ESC must be armed.'))  send({cmd:'motorDirCW'}); }
function motorDirCCW() { if (confirm('Set direction CCW (reverse)? ESC must be armed.')) send({cmd:'motorDirCCW'}); }
function motor3DOn()   { if (confirm('Enable 3D mode? ESC must be armed.'))  send({cmd:'motor3DOn'}); }
function motor3DOff()  { if (confirm('Disable 3D mode? ESC must be armed.')) send({cmd:'motor3DOff'}); }

// === BATTERY ===
function battAction(action) {
  const confirmMsgs = {
    unseal:      'Unseal battery? Tries TI default key.\nMavic 2+/3/4 will likely fail (no public key).',
    clearpf:     'Clear Permanent Failure flags?\nBattery MUST be unsealed first.\nOperation can take 2-3 seconds.',
    seal:        'Seal battery (lock config)?',
    reset:       'Send soft reset to BMS?',
    fullservice: 'FULL SERVICE: unseal + clear PF + seal.\nPotentially destructive. Continue only if you know what you are doing.'
  };
  if (confirmMsgs[action] && !confirm(confirmMsgs[action])) return;
  document.getElementById('battActionResult').textContent = '...';
  fetch('/api/batt?action='+action).then(r=>r.text()).then(t=>{
    document.getElementById('battActionResult').textContent = t;
  });
}

// === BATTERY LAB ===
let _profiles = [], _macCatalog = [];

function loadProfiles() {
  fetch('/api/batt/profiles').then(r=>r.json()).then(p=>{
    _profiles = p;
    const sel = document.getElementById('unsealProfile');
    sel.innerHTML = '';
    p.forEach((pr,i) => { const o = document.createElement('option'); o.value=i; o.textContent=pr.name; sel.appendChild(o); });
    loadProfile();
  });
}
function loadProfile() {
  const p = _profiles[document.getElementById('unsealProfile').value];
  if (!p) return;
  const el = document.getElementById('unsealKeyList');
  el.innerHTML = '<b>Unseal:</b> ' + p.unsealKeys.map(k=>k.w1+'/'+k.w2+' ('+k.desc+')').join(', ')
    + '<br><b>FAS:</b> ' + p.fasKeys.map(k=>k.w1+'/'+k.w2+' ('+k.desc+')').join(', ');
}
function tryAllKeys() {
  const p = _profiles[document.getElementById('unsealProfile').value];
  if (!p) return;
  const el = document.getElementById('unsealResult');
  el.textContent = 'Trying...';
  let chain = Promise.resolve();
  p.unsealKeys.forEach(k => {
    chain = chain.then(() => fetch('/api/batt/diag?unseal='+k.w1+','+k.w2).then(r=>r.json()).then(j=>{
      el.textContent += '\n' + k.desc + ': ' + j.result + (j.sealed ? ' (still sealed)' : ' UNSEALED!');
      if (!j.sealed) throw 'done';
    }));
  });
  chain.catch(e=>{ if (e!=='done') el.textContent += '\nError: '+e; });
}
function tryFasKeys() {
  const p = _profiles[document.getElementById('unsealProfile').value];
  if (!p) return;
  const el = document.getElementById('unsealResult');
  el.textContent = 'Trying FAS...';
  let chain = Promise.resolve();
  p.fasKeys.forEach(k => {
    chain = chain.then(() => fetch('/api/batt/diag?unseal='+k.w1+','+k.w2).then(r=>r.json()).then(j=>{
      el.textContent += '\n' + k.desc + ': ' + j.result;
    }));
  });
  chain.catch(e=>{ el.textContent += '\nError: '+e; });
}
function tryManualKey() {
  const w1 = document.getElementById('unsealW1').value || '0';
  const w2 = document.getElementById('unsealW2').value || '0';
  const el = document.getElementById('unsealResult');
  el.textContent = 'Sending ' + w1 + '/' + w2 + '...';
  fetch('/api/batt/diag?unseal='+w1+','+w2).then(r=>r.json()).then(j=>{
    el.textContent = j.result + ' | sealed=' + j.sealed + ' | opStatus=' + j.opStatus;
  });
}

function loadMacCatalog() {
  fetch('/api/batt/mac_catalog').then(r=>r.json()).then(c=>{
    _macCatalog = c;
    const sel = document.getElementById('macSelect');
    sel.innerHTML = '';
    c.forEach(m => {
      const o = document.createElement('option');
      o.value = m.sub; o.textContent = m.sub + ' ' + m.name + (m.destructive ? ' [!]' : '');
      o.dataset.desc = m.desc; o.dataset.rlen = m.rlen; o.dataset.destructive = m.destructive;
      sel.appendChild(o);
    });
    sel.onchange = () => {
      const opt = sel.selectedOptions[0];
      document.getElementById('macDesc').textContent = opt ? opt.dataset.desc : '';
    };
    sel.onchange();
  });
}
function runMacCmd() {
  const sel = document.getElementById('macSelect');
  const opt = sel.selectedOptions[0];
  if (!opt) return;
  if (opt.dataset.destructive === 'true' && !confirm(opt.dataset.desc + '\nThis is destructive. Continue?')) return;
  const sub = opt.value;
  const rlen = parseInt(opt.dataset.rlen);
  const el = document.getElementById('macResult');
  el.textContent = 'Executing ' + sub + '...';
  if (rlen > 0) {
    fetch('/api/batt/diag?mac=' + sub).then(r=>r.json()).then(j=>{
      el.textContent = 'MAC ' + sub + ' => len=' + j.len + '\nhex: ' + j.hex + '\nascii: ' + j.ascii;
    });
  } else {
    fetch('/api/smbus/xact?addr=0x0B&op=macCmd&data=' + sub).then(r=>r.json()).then(j=>{
      el.textContent = 'MAC ' + sub + ' => ' + (j.ok ? 'OK' : 'FAIL');
    });
  }
}

function smbExec() {
  const addr = document.getElementById('smbAddr').value;
  const op = document.getElementById('smbOp').value;
  const reg = document.getElementById('smbReg').value;
  const data = document.getElementById('smbData').value;
  const el = document.getElementById('smbResult');
  el.textContent = 'Sending...';
  let url = '/api/smbus/xact?addr='+addr+'&op='+op+'&reg='+reg;
  if (data) url += '&data='+encodeURIComponent(data);
  fetch(url).then(r=>r.json()).then(j=>{
    el.textContent = JSON.stringify(j, null, 2);
  });
}
// === DATA FLASH EDITOR ===
let _dfMap = [], _dfValues = {}, _dfSnapA = null, _dfSnapB = null;

function dfLoadMap() {
  document.getElementById('dfStatus').textContent = 'Loading map...';
  fetch('/api/batt/df/map').then(r=>r.json()).then(m=>{
    _dfMap = m;
    document.getElementById('dfReadAllBtn').disabled = false;
    document.getElementById('dfFilter').style.display = '';
    document.getElementById('dfStatus').textContent = m.length + ' entries loaded';
    dfRenderTree();
  });
}

function dfReadAll() {
  const btn = document.getElementById('dfReadAllBtn');
  btn.disabled = true;
  document.getElementById('dfStatus').textContent = 'Reading all DF values...';
  fetch('/api/batt/df/readall').then(r=>r.json()).then(vals=>{
    _dfValues = {};
    vals.forEach(v => { _dfValues[v.addr] = v; });
    btn.disabled = false;
    document.getElementById('dfExportBtn').disabled = false;
    let ok = 0, fail = 0, diff = 0;
    vals.forEach(v => { if (v.ok) { ok++; if (v.diff) diff++; } else fail++; });
    document.getElementById('dfStatus').textContent = 'Read: ' + ok + ' ok, ' + fail + ' fail, ' + diff + ' differ from default';
    dfRenderTree();
  }).catch(e => {
    btn.disabled = false;
    document.getElementById('dfStatus').textContent = 'Error: ' + e;
  });
}

function _dfSnapVal(snap, addr) {
  if (!snap) return null;
  const row = snap.find(r => r.addr === addr);
  if (!row || row.current === null || row.current === undefined) return null;
  return row.current;
}

function dfRenderTree() {
  const search = (document.getElementById('dfSearch')?.value || '').toLowerCase();
  const diffOnly = document.getElementById('dfDiffOnly')?.checked;
  const compareMode = document.getElementById('dfCompareMode')?.checked;
  const hasA = !!_dfSnapA, hasB = !!_dfSnapB;

  // Group by category -> subcategory
  const groups = {};
  _dfMap.forEach((e, idx) => {
    const v = _dfValues[e.addr];
    const a = hasA ? _dfSnapVal(_dfSnapA, e.addr) : null;
    const b = hasB ? _dfSnapVal(_dfSnapB, e.addr) : null;
    const fullName = (e.cat + ' ' + e.sub + ' ' + e.field).toLowerCase();
    if (search && !fullName.includes(search)) return;
    // In compare mode: only show rows where A and B differ
    if (compareMode && hasA && hasB && a === b) return;
    if (diffOnly && !compareMode && (!v || !v.diff)) return;
    const key = e.cat;
    if (!groups[key]) groups[key] = {};
    if (!groups[key][e.sub]) groups[key][e.sub] = [];
    groups[key][e.sub].push({...e, idx, v, a, b});
  });

  let html = '';
  if (compareMode && (hasA || hasB)) {
    html += '<div style="color:#888;font-size:11px;margin:4px 0">';
    html += '<span style="color:#0af">A</span> = imported snapshot A, ';
    html += '<span style="color:#f0a">B</span> = imported snapshot B. ';
    html += 'Yellow = differs.';
    html += '</div>';
  }
  for (const cat in groups) {
    html += '<div style="margin-top:8px;border-left:3px solid #55a;padding-left:8px">';
    html += '<div style="color:#8af;font-weight:bold;margin-bottom:4px">' + cat + '</div>';
    for (const sub in groups[cat]) {
      html += '<div style="color:#aaa;margin:4px 0 2px 8px;font-size:11px">▸ ' + sub + '</div>';
      html += '<table style="width:100%;border-collapse:collapse;margin-left:16px">';
      groups[cat][sub].forEach(e => {
        const v = e.v;
        const hasVal = v && v.ok;
        const curVal = hasVal ? v.val : '';
        const isDiff = hasVal && v.diff;
        const valColor = isDiff ? '#fa0' : '#6f6';
        const addrHex = e.addr;
        html += '<tr style="border-bottom:1px solid #1a1a2e">';
        html += '<td style="padding:3px 6px;color:#ccc;width:30%">' + e.field + ' <span style="color:#555">(' + e.unit + ')</span></td>';
        html += '<td style="padding:3px 4px;color:#666;font-family:monospace;font-size:10px;width:60px">' + addrHex + '</td>';
        if (compareMode) {
          const diffAB = (e.a !== null && e.b !== null && e.a !== e.b);
          const colA = diffAB ? '#fa0' : '#0af';
          const colB = diffAB ? '#fa0' : '#f0a';
          html += '<td style="padding:3px 4px;color:' + colA + ';font-family:monospace;font-size:12px;width:80px">'
                + (e.a !== null ? e.a : '<span style="color:#444">-</span>') + '</td>';
          html += '<td style="padding:3px 4px;color:' + colB + ';font-family:monospace;font-size:12px;width:80px">'
                + (e.b !== null ? e.b : '<span style="color:#444">-</span>') + '</td>';
          html += '<td style="padding:3px 4px;color:#555;font-size:11px;width:60px">';
          if (diffAB) {
            const delta = e.b - e.a;
            html += (delta > 0 ? '+' : '') + delta;
          }
          html += '</td>';
          // Restore button — write A value (if available) to board
          html += '<td style="padding:3px 2px;width:60px">';
          if (hasVal && e.a !== null && e.a !== curVal) {
            html += '<button onclick="dfRestoreOne(this)" data-addr="' + addrHex + '" data-size="' + e.size + '" data-value="' + e.a + '" '
                  + 'style="padding:2px 6px;font-size:10px;background:#08a">→A</button>';
          }
          if (hasVal && e.b !== null && e.b !== curVal) {
            html += ' <button onclick="dfRestoreOne(this)" data-addr="' + addrHex + '" data-size="' + e.size + '" data-value="' + e.b + '" '
                  + 'style="padding:2px 6px;font-size:10px;background:#a08">→B</button>';
          }
          html += '</td></tr>';
        } else {
          html += '<td style="padding:3px 4px;width:30%">';
          if (hasVal) {
            html += '<input type="number" value="' + curVal + '" min="' + e.min + '" max="' + e.max + '" '
                  + 'data-addr="' + addrHex + '" data-size="' + e.size + '" data-orig="' + curVal + '" '
                  + 'style="width:80px;background:#0a0a14;color:' + valColor + ';border:1px solid #333;padding:2px 4px;font-family:monospace;font-size:12px" '
                  + 'onchange="dfMarkChanged(this)">';
          } else {
            html += '<span style="color:#555">-</span>';
          }
          html += '</td>';
          html += '<td style="padding:3px 4px;width:60px">';
          if (hasVal) html += '<span style="color:#555;font-size:10px">def:' + e.def + '</span>';
          html += '</td>';
          html += '<td style="padding:3px 2px;width:50px">';
          if (hasVal) {
            html += '<button onclick="dfWriteOne(this)" data-addr="' + addrHex + '" data-size="' + e.size + '" '
                  + 'style="padding:2px 6px;font-size:10px;background:#333;display:none">Write</button>';
          }
          html += '</td></tr>';
        }
      });
      html += '</table>';
    }
    html += '</div>';
  }
  if (!html) html = '<div style="color:#888;padding:10px">No entries. Click "Load Map" first.</div>';
  document.getElementById('dfTree').innerHTML = html;
}

function dfMarkChanged(input) {
  const orig = parseInt(input.dataset.orig);
  const cur = parseInt(input.value);
  const writeBtn = input.closest('tr').querySelector('button');
  if (cur !== orig) {
    input.style.color = '#f44';
    input.style.borderColor = '#f44';
    if (writeBtn) writeBtn.style.display = '';
  } else {
    input.style.color = '#6f6';
    input.style.borderColor = '#333';
    if (writeBtn) writeBtn.style.display = 'none';
  }
}

function dfWriteOne(btn) {
  const addr = btn.dataset.addr;
  const size = btn.dataset.size;
  const input = btn.closest('tr').querySelector('input[type=number]');
  const value = input.value;
  if (!confirm('Write ' + value + ' to DF ' + addr + '?\\nBattery must be unsealed!')) return;
  btn.disabled = true;
  btn.textContent = '...';
  const fd = new FormData();
  fd.append('addr', addr); fd.append('value', value); fd.append('size', size);
  fetch('/api/batt/df/write', {method:'POST', body:fd}).then(r=>r.json()).then(j=>{
    btn.disabled = false;
    if (j.ok) {
      btn.textContent = 'OK';
      btn.style.background = '#2a4';
      input.dataset.orig = value;
      input.style.color = '#6f6';
      input.style.borderColor = '#333';
      setTimeout(()=>{ btn.textContent = 'Write'; btn.style.background = '#333'; btn.style.display = 'none'; }, 1500);
    } else {
      btn.textContent = 'FAIL';
      btn.style.background = '#a42';
      setTimeout(()=>{ btn.textContent = 'Write'; btn.style.background = '#333'; }, 2000);
    }
  });
}

function dfFilterApply() { dfRenderTree(); }

function _dfSnapshotFromCurrent() {
  return _dfMap.map(e => {
    const v = _dfValues[e.addr];
    return {
      addr: e.addr, category: e.cat, subcat: e.sub, field: e.field,
      type: e.type, unit: e.unit, default: e.def,
      current: v && v.ok ? v.val : null,
      differs: v ? !!v.diff : null
    };
  });
}

function dfExport() {
  const blob = new Blob([JSON.stringify(_dfSnapshotFromCurrent(), null, 2)], {type:'application/json'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'dataflash_' + new Date().toISOString().slice(0,19).replace(/:/g,'-') + '.json';
  a.click();
}

function dfImportSnapshot(evt, slot) {
  const file = evt.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const data = JSON.parse(e.target.result);
      if (!Array.isArray(data)) throw new Error('Expected array');
      if (slot === 'A') _dfSnapA = data; else _dfSnapB = data;
      dfUpdateSnapshotStatus();
      // Auto-enable compare mode when both loaded
      if (_dfSnapA && _dfSnapB) document.getElementById('dfCompareMode').checked = true;
      dfRenderTree();
    } catch (err) {
      alert('Bad snapshot file: ' + err);
    }
  };
  reader.readAsText(file);
  evt.target.value = '';
}

function dfUseCurrentAs(slot) {
  if (!Object.keys(_dfValues).length) { alert('Read all values first'); return; }
  const snap = _dfSnapshotFromCurrent();
  if (slot === 'A') _dfSnapA = snap; else _dfSnapB = snap;
  dfUpdateSnapshotStatus();
  if (_dfSnapA && _dfSnapB) document.getElementById('dfCompareMode').checked = true;
  dfRenderTree();
}

function dfClearSnapshots() {
  _dfSnapA = null; _dfSnapB = null;
  document.getElementById('dfCompareMode').checked = false;
  dfUpdateSnapshotStatus();
  dfRenderTree();
}

function dfUpdateSnapshotStatus() {
  const el = document.getElementById('dfSnapshotStatus');
  const parts = [];
  if (_dfSnapA) parts.push('<span style="color:#0af">A loaded (' + _dfSnapA.length + ')</span>');
  if (_dfSnapB) parts.push('<span style="color:#f0a">B loaded (' + _dfSnapB.length + ')</span>');
  el.innerHTML = parts.join(' ');
}

function dfRestoreOne(btn) {
  const addr = btn.dataset.addr;
  const size = btn.dataset.size;
  const value = btn.dataset.value;
  if (!confirm('Restore ' + addr + ' to ' + value + '? Battery must be unsealed.')) return;
  btn.disabled = true;
  btn.textContent = '...';
  const fd = new FormData();
  fd.append('addr', addr); fd.append('value', value); fd.append('size', size);
  fetch('/api/batt/df/write', {method:'POST', body:fd}).then(r=>r.json()).then(j=>{
    btn.textContent = j.ok ? 'OK' : 'FAIL';
    btn.style.background = j.ok ? '#2a4' : '#a42';
    if (j.ok) setTimeout(()=>dfReadAll(), 500);
  });
}

function i2cPreflight() {
  const el = document.getElementById('preflightResult');
  el.style.display = 'block';
  el.textContent = 'Running preflight...';
  fetch('/api/i2c/preflight').then(r=>r.json()).then(j=>{
    let s = 'SDA: ' + (j.sdaOk ? 'OK' : 'STUCK LOW!') + '\n';
    s += 'SCL: ' + (j.sclOk ? 'OK' : 'STUCK LOW!') + '\n';
    s += 'Battery (0x0B): ' + (j.batteryAck ? 'ACK' : 'NO RESPONSE') + '\n';
    s += 'Devices found: ' + j.devCount;
    if (j.devices && j.devices.length) s += ' [' + j.devices.join(', ') + ']';
    el.textContent = s;
    el.style.color = (j.sdaOk && j.sclOk && j.batteryAck) ? '#0f0' : '#f44';
  });
}
function i2cScan() {
  const el = document.getElementById('i2cScanResult');
  el.style.display = 'block';
  el.textContent = 'Scanning...';
  fetch('/api/i2c/scan').then(r=>r.text()).then(t=>{ el.textContent = t; });
}

let _smbLogTimer = null;
function smbLogRefresh() {
  fetch('/api/smbus/log').then(r=>r.text()).then(t=>{
    document.getElementById('smbLog').textContent = t;
  });
}
function smbLogExport() {
  const text = document.getElementById('smbLog').textContent;
  const blob = new Blob([text], {type:'text/plain'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'smbus_log_' + new Date().toISOString().slice(0,19).replace(/:/g,'-') + '.txt';
  a.click();
}
function smbLogToggle() {
  fetch('/api/smbus/log/toggle', {method:'POST'}).then(r=>r.text()).then(t=>{
    document.getElementById('smbLogToggleBtn').textContent = t.includes('ON') ? 'Disable Logging' : 'Enable Logging';
    smbLogRefresh();
  });
}
function smbLogAutoToggle() {
  if (_smbLogTimer) { clearInterval(_smbLogTimer); _smbLogTimer = null; }
  if (document.getElementById('smbLogAuto').checked) {
    _smbLogTimer = setInterval(smbLogRefresh, 1000);
  }
}

function battSnapshot() {
  fetch('/api/batt/snapshot').then(r=>r.json()).then(j=>{
    const blob = new Blob([JSON.stringify(j, null, 2)], {type:'application/json'});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'battery_snapshot_' + new Date().toISOString().slice(0,19).replace(/:/g,'-') + '.json';
    a.click();
  });
}

// === CRSF ===
function crsfStart() {
  const inv = document.getElementById('crsfInverted').checked ? '1' : '0';
  fetch('/api/crsf/start?inverted='+inv, {method:'POST'})
    .then(r=>r.text()).then(t=>showCmdResult(t));
}
function crsfStop()  { fetch('/api/crsf/stop',  {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t)); }
function crsfPing()  { fetch('/api/crsf/ping',  {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t)); }
function crsfReadParams() { fetch('/api/crsf/params', {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t)); }
function crsfBind()   { if (confirm('Send bind command?')) fetch('/api/crsf/bind',   {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t)); }
function crsfReboot() { if (confirm('Reboot receiver?'))   fetch('/api/crsf/reboot', {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t)); }
function crsfEnterWifi() {
  if (!confirm('Switch RX to WiFi update mode? Link will drop; RX will start its own AP.')) return;
  fetch('/api/crsf/wifi', {method:'POST'}).then(r=>r.text()).then(t=>showCmdResult(t));
}

// Render CRSF parameter tree: group by parent_id, folders expand, commands are state-aware.
// ELRS COMMAND status codes: 0=READY, 1=START, 2=PROGRESS, 3=CONFIRM_NEEDED, 4=CONFIRM, 5=CANCEL, 6=QUERY.
function renderCrsfCommand(p) {
  const info = p.info || '';
  const s = p.status | 0;
  if (s === 2) { // PROGRESS
    return `<span style="color:#fc0">${info || 'Executing...'}</span> `
         + `<button onclick="crsfWriteParam(${p.id}, 5)">Abort</button>`;
  }
  if (s === 3) { // CONFIRMATION_NEEDED
    return `<span style="color:#f80">${info || 'Confirm?'}</span> `
         + `<button onclick="crsfWriteParam(${p.id}, 4)">Confirm</button> `
         + `<button onclick="crsfWriteParam(${p.id}, 5)">Cancel</button>`;
  }
  if (s === 4) return `<span style="color:#0f0">Done</span>`;
  if (s === 5) return `<span style="color:#888">Cancelled</span>`;
  // READY (0) / QUERY (6) / unknown → show Execute button
  return `<button onclick="crsfWriteParam(${p.id}, 1)">Execute</button>`
       + (info ? ` <span style="color:#888;font-size:11px">${info}</span>` : '');
}

function renderCrsfParamValue(p) {
  if (p.type === 9) { // TEXT_SELECTION
    const opts = (p.opts || '').split(';');
    let sel = `<select onchange="crsfWriteParam(${p.id}, this.value)" style="background:#0a0a14;color:#fff;border:1px solid #333;padding:4px;">`;
    opts.forEach((o,i) => {
      sel += `<option value="${i}"${i === p.idx ? ' selected' : ''}>${o}</option>`;
    });
    return sel + '</select>';
  }
  if (p.type === 10) return `<input type="text" value="${p.value || ''}" onchange="crsfWriteParam(${p.id}, this.value)" style="background:#0a0a14;color:#fff;border:1px solid #333;padding:4px;width:120px;">`;
  if (p.type === 12) return `<span style="color:#aaa">${p.value || ''}</span>`;
  if (p.type === 13) return renderCrsfCommand(p);
  // Numeric
  return `<input type="number" value="${p.value}" min="${p.min||0}" max="${p.max||255}" onchange="crsfWriteParam(${p.id}, this.value)" style="background:#0a0a14;color:#fff;border:1px solid #333;padding:4px;width:80px;">`;
}

function renderCrsfParams(params) {
  // Index by id, bucket children by parent
  const byId = {};
  const children = {};
  params.forEach(p => {
    byId[p.id] = p;
    const pp = p.parent | 0;
    (children[pp] = children[pp] || []).push(p);
  });

  // Depth-first rendering with indentation
  function renderGroup(parentId, depth) {
    const list = children[parentId] || [];
    let html = '';
    list.forEach(p => {
      const indent = depth * 14;
      const nameCol = `<b>${p.name}</b>` + (p.unit ? ` <span style="color:#888">(${p.unit})</span>` : '');
      if (p.type === 11) {
        // Folder header
        html += `<div class="row" style="padding-left:${indent}px;background:#1a1a2a;margin-top:4px;border-left:3px solid #55a;">`
              + `<span style="color:#8af">▾ ${p.name}</span></div>`;
        html += renderGroup(p.id, depth + 1);
      } else {
        html += `<div class="row" style="padding-left:${indent}px;">`
              + `<span class="label" style="flex:1">${nameCol}</span>`
              + `<span>${renderCrsfParamValue(p)}</span></div>`;
      }
    });
    return html;
  }

  // Roots: anything whose parent is 0 or not in byId
  // (ELRS uses parent_id=0 for root-level params)
  let html = renderGroup(0, 0);
  // Orphans — params pointing to an unknown parent
  Object.keys(children).forEach(pid => {
    const p = pid | 0;
    if (p !== 0 && !byId[p]) html += renderGroup(p, 0);
  });
  return html || '<div style="color:#888">No visible parameters.</div>';
}
function crsfWriteParam(id, value) {
  fetch(`/api/crsf/write?id=${id}&value=${encodeURIComponent(value)}`, {method:'POST'})
    .then(r=>r.text()).then(t=>showCmdResult(t));
}
function showCmdResult(msg) {
  const el = document.getElementById('crsfCmdResult');
  if (el) { el.textContent = msg; setTimeout(()=>el.textContent='', 3000); }
}

// === ELRS FLASH ===
let selectedFile = null;
function onFwSelect() {
  selectedFile = document.getElementById('fwFile').files[0];
  if (selectedFile) {
    document.getElementById('fwSize').textContent = (selectedFile.size/1024).toFixed(1) + ' KB';
    document.getElementById('uploadBtn').disabled = false;
  }
}
function uploadFw() {
  if (!selectedFile) return;
  const fd = new FormData();
  fd.append('firmware', selectedFile);
  document.getElementById('flashStage').textContent = 'Uploading...';
  document.getElementById('uploadBtn').disabled = true;
  fetch('/api/flash/upload', {method:'POST', body:fd})
    .then(r=>r.text()).then(t=>{
      document.getElementById('flashStage').textContent = 'Uploaded';
      document.getElementById('flashBtn').disabled = false;
      document.getElementById('flashResult').textContent = t;
    })
    .catch(e=>{
      document.getElementById('flashStage').textContent = 'Upload error';
      document.getElementById('flashResult').textContent = e;
      document.getElementById('uploadBtn').disabled = false;
    });
}
function startFlash() {
  if (!confirm('Убедись что приёмник в DFU режиме!\nПродолжить прошивку?')) return;
  document.getElementById('flashBtn').disabled = true;
  document.getElementById('flashResult').textContent = '';
  fetch('/api/flash/start', {method:'POST'})
    .then(r=>r.text()).then(t=>{
      document.getElementById('flashResult').textContent = t;
    });
}
function clearFw() {
  fetch('/api/flash/clear', {method:'POST'}).then(()=>{
    document.getElementById('fwFile').value = '';
    document.getElementById('fwSize').textContent = '-';
    document.getElementById('flashStage').textContent = 'idle';
    document.getElementById('flashBar').style.width = '0%';
    document.getElementById('flashResult').textContent = '';
    document.getElementById('uploadBtn').disabled = true;
    document.getElementById('flashBtn').disabled = true;
    selectedFile = null;
  });
}

// === WiFi ===
function saveWifi() {
  const ssid = document.getElementById('wifiSSID').value;
  const pass = document.getElementById('wifiPASS').value;
  if (!ssid) return alert('Enter SSID');
  fetch('/api/wifi/save', {method:'POST', body:JSON.stringify({ssid,pass})})
    .then(r=>r.text()).then(t=>alert(t));
}
function clearWifi() {
  if (!confirm('Reset WiFi to AP mode?')) return;
  fetch('/api/wifi/clear').then(r=>r.text()).then(t=>alert(t));
}

// ===== USB mode =====
function usbRefresh() {
  fetch('/api/usb/mode').then(r=>r.json()).then(j=>{
    document.getElementById('usbCurrent').textContent = j.current_name + ' (#' + j.current + ')';
    const c = document.getElementById('usbModes');
    c.innerHTML = '';
    j.modes.forEach(m => {
      const lab = document.createElement('label');
      lab.style.cssText = 'display:flex;align-items:center;gap:8px;cursor:pointer';
      const r = document.createElement('input');
      r.type = 'radio'; r.name = 'usbmode'; r.value = m.id;
      if (m.id === j.current) r.checked = true;
      lab.appendChild(r);
      lab.appendChild(document.createTextNode(m.name));
      c.appendChild(lab);
    });
  });
}
function _usbSelectedMode() {
  const r = document.querySelector('input[name=usbmode]:checked');
  return r ? r.value : null;
}
function usbApply(done) {
  const mode = _usbSelectedMode();
  if (mode === null) { document.getElementById('usbMsg').textContent = 'Выберите режим'; return; }
  const fd = new FormData(); fd.append('mode', mode);
  fetch('/api/usb/mode', {method:'POST', body:fd})
    .then(r => r.text()).then(t => {
      document.getElementById('usbMsg').textContent = t;
      if (done) done();
    });
}
let cpLogTimer = null;
function cpLogRefresh() {
  fetch('/api/cp2112/log').then(r=>r.text()).then(t=>{
    const el = document.getElementById('cpLog');
    el.textContent = t;
    // Count lines for stats
    const lines = t.split('\n').filter(l => l.trim().length > 0);
    const stats = document.getElementById('cpLogStats');
    if (stats) stats.textContent = lines.length > 1 ? (lines.length - 1) + ' entries' : '';
  });
}
function cpLogExport() {
  const text = document.getElementById('cpLog').textContent;
  const blob = new Blob([text], {type:'text/plain'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'cp2112_log_' + new Date().toISOString().slice(0,19).replace(/:/g,'-') + '.txt';
  a.click();
}
function cpLogAutoToggle() {
  if (cpLogTimer) { clearInterval(cpLogTimer); cpLogTimer = null; }
  if (document.getElementById('cpLogAuto').checked) {
    cpLogTimer = setInterval(cpLogRefresh, 1000);
  }
}

function usbReboot() {
  if (!confirm('Сохранить новый USB-режим и перезагрузить плату?')) return;
  usbApply(() => {
    fetch('/api/usb/reboot', {method:'POST'}).then(()=>{
      document.getElementById('usbMsg').textContent = 'Перезагружается...';
    });
  });
}

// ===== OTA =====
function fmtBytes(b) {
  if (b >= 1048576) return (b/1048576).toFixed(2) + ' MB';
  if (b >= 1024) return (b/1024).toFixed(1) + ' KB';
  return b + ' B';
}
function otaRefresh() {
  fetch('/api/ota/info').then(r=>r.json()).then(j=>{
    document.getElementById('otaFwVer').textContent   = j.fw_version || '?';
    document.getElementById('otaRunning').textContent = j.running || '?';
    document.getElementById('otaNext').textContent    = j.next    || '?';
    document.getElementById('otaAppSize').textContent = fmtBytes(j.app_size || 0);
    document.getElementById('otaFree').textContent    = fmtBytes(j.app_free || 0);
    document.getElementById('otaSdk').textContent     = j.sdk     || '?';
    document.getElementById('otaRepo').textContent    = j.github_repo || '(не задан)';
    if (j.latest) {
      document.getElementById('otaLatest').textContent = j.latest;
      const outdated = j.latest !== j.fw_version;
      document.getElementById('otaCompare').textContent =
        outdated ? 'доступна новая версия' : 'актуальная';
      document.getElementById('otaCompare').style.color = outdated ? '#fa0' : '#0f0';
      document.getElementById('otaPullBtn').disabled = !outdated || !j.latest_url;
    }
    if (j.pull_running) {
      document.getElementById('otaPullStage').textContent = j.pull_message + ' (' + j.pull_progress + '%)';
      document.getElementById('otaPullBar').style.width = j.pull_progress + '%';
    } else if (j.pull_message) {
      document.getElementById('otaPullStage').textContent = j.pull_message;
    }
  }).catch(e=>{
    document.getElementById('otaResult').textContent = 'Info error: ' + e;
  });
}

function otaCheck() {
  const btn = document.getElementById('otaCheckBtn');
  btn.disabled = true;
  document.getElementById('otaCompare').textContent = 'проверяю...';
  fetch('/api/ota/check', {method:'POST'})
    .then(r => r.text().then(body => ({ok: r.ok, status: r.status, body})))
    .then(res => {
      btn.disabled = false;
      if (!res.ok) {
        document.getElementById('otaCompare').textContent = 'ошибка HTTP ' + res.status + ': ' + res.body;
        document.getElementById('otaCompare').style.color = '#f44';
        return;
      }
      otaRefresh();
    })
    .catch(e => {
      btn.disabled = false;
      document.getElementById('otaCompare').textContent = 'Network error: ' + e;
    });
}

let otaPullPoll = null;
function otaPull() {
  if (!confirm('Скачать и прошить последнюю версию из GitHub?\nПлата перезагрузится.')) return;
  const stage = document.getElementById('otaPullStage');
  const bar = document.getElementById('otaPullBar');
  stage.textContent = 'starting';
  bar.style.width = '0%';
  bar.style.background = '#0af';
  document.getElementById('otaPullBtn').disabled = true;

  fetch('/api/ota/pull', {method:'POST'}).then(r => r.text()).then(t => {
    stage.textContent = t;
    if (otaPullPoll) clearInterval(otaPullPoll);
    otaPullPoll = setInterval(() => {
      fetch('/api/ota/info').then(r => r.json()).then(j => {
        bar.style.width = (j.pull_progress || 0) + '%';
        stage.textContent = (j.pull_message || '') + ' (' + (j.pull_progress || 0) + '%)';
        if (!j.pull_running) {
          clearInterval(otaPullPoll);
          otaPullPoll = null;
          if ((j.pull_message || '').startsWith('OK')) {
            bar.style.background = '#0f0';
            setTimeout(() => location.reload(), 10000);
          } else {
            bar.style.background = '#f44';
            document.getElementById('otaPullBtn').disabled = false;
          }
        }
      }).catch(() => { /* during reboot fetch fails — that's OK */ });
    }, 1000);
  });
}
function otaAbort() {
  fetch('/api/ota/abort', {method:'POST'}).then(r=>r.text()).then(t=>{
    document.getElementById('otaResult').textContent = t;
    document.getElementById('otaStage').textContent = 'aborted';
  });
}
function otaUpload() {
  const f = document.getElementById('otaFile').files[0];
  if (!f) return alert('Выбери firmware.bin');
  if (!confirm('Прошить ' + f.name + ' (' + fmtBytes(f.size) + ')?\nПлата перезагрузится.')) return;

  const fd = new FormData();
  fd.append('update', f, f.name);

  const xhr = new XMLHttpRequest();
  xhr.open('POST', '/api/ota');
  const bar = document.getElementById('otaBar');
  const stage = document.getElementById('otaStage');
  const res = document.getElementById('otaResult');
  const btn = document.getElementById('otaBtn');

  btn.disabled = true;
  res.textContent = '';
  stage.textContent = 'uploading...';
  bar.style.width = '0%';
  bar.style.background = '#0af';

  xhr.upload.onprogress = (e) => {
    if (e.lengthComputable) {
      const pct = Math.round(e.loaded * 100 / e.total);
      bar.style.width = pct + '%';
      stage.textContent = 'uploading ' + pct + '% (' + fmtBytes(e.loaded) + '/' + fmtBytes(e.total) + ')';
    }
  };
  xhr.onload = () => {
    btn.disabled = false;
    if (xhr.status === 200) {
      bar.style.width = '100%';
      bar.style.background = '#0f0';
      stage.textContent = 'done — rebooting';
      res.style.color = '#0f0';
      res.textContent = xhr.responseText + ' — страница обновится автоматически через 8 с';
      setTimeout(() => location.reload(), 8000);
    } else {
      bar.style.background = '#f44';
      stage.textContent = 'error';
      res.style.color = '#f44';
      res.textContent = 'HTTP ' + xhr.status + ': ' + xhr.responseText;
    }
  };
  xhr.onerror = () => {
    btn.disabled = false;
    stage.textContent = 'network error';
    res.style.color = '#f44';
    res.textContent = 'Network error';
  };
  xhr.send(fd);
}

// Scan is async on the ESP side — HTTP returns right away, we poll for results.
// Expect a 1-3s AP hiccup during the scan; WebSocket keepalive rides it out.
function scanWifi() {
  const btn = document.getElementById('wifiScanBtn');
  const stat = document.getElementById('wifiScanStatus');
  const list = document.getElementById('wifiScanList');
  btn.disabled = true;
  stat.textContent = 'scanning... (brief AP lag)';
  list.innerHTML = '';
  fetch('/api/wifi/scan', {method:'POST'})
    .then(() => pollWifiScan(0))
    .catch(e => { stat.textContent = 'scan error'; btn.disabled = false; });
}
function pollWifiScan(tries) {
  if (tries > 30) {  // ~15s cap
    document.getElementById('wifiScanStatus').textContent = 'timeout';
    document.getElementById('wifiScanBtn').disabled = false;
    return;
  }
  setTimeout(() => {
    fetch('/api/wifi/scan_results').then(r=>r.json()).then(j => {
      if (!j.done) return pollWifiScan(tries + 1);
      renderWifiScan(j.nets || []);
      document.getElementById('wifiScanStatus').textContent = (j.nets||[]).length + ' networks';
      document.getElementById('wifiScanBtn').disabled = false;
    }).catch(() => pollWifiScan(tries + 1));
  }, 500);
}
function renderWifiScan(nets) {
  nets.sort((a,b) => b.rssi - a.rssi);
  const list = document.getElementById('wifiScanList');
  if (!nets.length) { list.innerHTML = '<div style="color:#888">no networks found</div>'; return; }
  list.innerHTML = nets.map(n => {
    const bars = n.rssi > -55 ? '▂▄▆█' : n.rssi > -70 ? '▂▄▆_' : n.rssi > -80 ? '▂▄__' : '▂___';
    const lock = n.enc ? '🔒' : ' ';
    const ssid = (n.ssid || '<hidden>').replace(/</g,'&lt;');
    return `<div class="row" style="cursor:pointer;padding:4px;border-bottom:1px solid #222" onclick="pickSsid(${JSON.stringify(n.ssid||'').replace(/"/g,'&quot;')})">`
         + `<span style="flex:1">${lock} ${ssid}</span>`
         + `<span style="color:#8af;font-family:monospace">${bars}</span>`
         + `<span style="color:#888;margin-left:8px;width:60px;text-align:right">${n.rssi} dBm</span>`
         + `<span style="color:#666;margin-left:8px;width:30px;text-align:right">ch${n.ch}</span>`
         + `</div>`;
  }).join('');
}
function pickSsid(ssid) {
  document.getElementById('wifiSSID').value = ssid;
  document.getElementById('wifiPASS').focus();
}

// === Incoming messages ===
function handleMsg(m) {
  if (m.type === 'batt') {
    const c = m.connected;
    const bc = document.getElementById('battConn');
    bc.className = 'status ' + (c ? 'on' : 'off');
    bc.textContent = c ? 'YES' : 'NO';
    if (!c) return;

    // Device type badge
    const dtEl = document.getElementById('battDevType');
    if (m.devType === 1) { dtEl.style.display='inline-block'; dtEl.textContent='DJI'; dtEl.className='status on'; }
    else if (m.devType === 2) { dtEl.style.display='inline-block'; dtEl.textContent='SBS'; dtEl.className='status on'; }
    else dtEl.style.display='none';

    document.getElementById('battSOC').textContent = m.soc + ' %';
    document.getElementById('battBar').style.width = m.soc + '%';
    document.getElementById('battVolt').textContent = (m.voltage/1000).toFixed(2) + ' V';
    document.getElementById('battCurr').textContent = m.current + ' mA';
    document.getElementById('battAvgCurr').textContent = m.avgCurrent + ' mA';
    document.getElementById('battTemp').textContent = m.temp.toFixed(1) + ' °C';
    document.getElementById('battSOH').textContent = (m.soh && m.soh < 0xFFFF) ? m.soh + ' %' : '-';
    document.getElementById('battCycle').textContent = m.cycles;
    document.getElementById('battCap').textContent = m.remain + '/' + m.full + ' mAh';
    document.getElementById('battDesign').textContent = m.design + ' mAh';

    // Time estimates
    const fmtMin = v => (v && v < 0xFFFF) ? v + ' min' : '-';
    document.getElementById('battTTE').textContent = fmtMin(m.ate);
    document.getElementById('battTTF').textContent = fmtMin(m.ttf);
    document.getElementById('battChg').textContent = (m.chgI || '-') + ' mA / ' + (m.chgV ? (m.chgV/1000).toFixed(2)+'V' : '-');
    document.getElementById('battStatusBits').textContent = m.statusDecoded || '-';

    document.getElementById('battMfr').textContent = m.mfr;
    document.getElementById('battDev').textContent = m.dev;
    document.getElementById('battChem').textContent = m.chem || '-';
    document.getElementById('battConfig').textContent = m.cellCount + 'S / ' + m.design + 'mAh / ' + (m.designV ? (m.designV/1000).toFixed(1)+'V' : '-');

    // DJI serial
    const djiSnEl = document.getElementById('battDjiSN');
    if (m.djiSN) { djiSnEl.textContent = m.djiSN; djiSnEl.style.display = ''; djiSnEl.parentElement.style.display = ''; }
    else { djiSnEl.parentElement.style.display = 'none'; }

    // Decode manufacture date (SBS format: bits 15:9=year+1980, 8:5=month, 4:0=day)
    if (m.mfgDate) {
      const y = ((m.mfgDate >> 9) & 0x7F) + 1980;
      const mo = (m.mfgDate >> 5) & 0x0F;
      const d = m.mfgDate & 0x1F;
      document.getElementById('battSN').textContent = '#' + m.sn + ' (' + y + '-' + String(mo).padStart(2,'0') + '-' + String(d).padStart(2,'0') + ')';
    } else {
      document.getElementById('battSN').textContent = '#' + m.sn;
    }
    document.getElementById('battModel').textContent = m.model || '-';

    // Chip info — human-readable
    const chipName = m.chipType === 0x4307 ? 'BQ40Z307' :
                     m.chipType === 0x0550 ? 'BQ30Z55' :
                     m.chipType === 0 ? 'Clone (MAC not supported)' : 'ID: 0x' + m.chipType.toString(16).toUpperCase();
    document.getElementById('battChip').textContent = chipName;
    document.getElementById('battFwHw').textContent = m.fwVer ? ('FW ' + m.fwVer + ' / HW ' + m.hwVer) : 'Not available';

    // Seal state
    const sealEl = document.getElementById('battSealStatus');
    if (m.sealed) {
      sealEl.style.display = 'inline-block';
      sealEl.textContent = 'SEALED';
      sealEl.className = 'status warn';
    } else {
      sealEl.style.display = 'inline-block';
      sealEl.textContent = 'UNSEALED';
      sealEl.className = 'status on';
    }

    // Key warning — suppress for clones (they use standard TI keys)
    const isClone = (m.mfr === 'PTL' || m.chipType === 0);
    document.getElementById('keyWarning').style.display = (m.needsKey && !isClone) ? 'block' : 'none';

    // Extended status — show decoded first, hex as secondary
    const hex8 = v => '0x' + v.toString(16).toUpperCase().padStart(8, '0');
    document.getElementById('opStatus').textContent = m.opDecoded || 'N/A';
    document.getElementById('opDecoded').textContent = hex8(m.operationStatus);
    document.getElementById('safetyStatus').textContent = m.safetyDecoded || 'OK';
    document.getElementById('safetyDecoded').textContent = hex8(m.safetyStatus);
    const pfEl = document.getElementById('pfDecoded');
    document.getElementById('pfStatus').textContent = m.pfDecoded || 'OK';
    pfEl.textContent = hex8(m.pfStatus);
    pfEl.style.color = m.hasPF ? '#f44' : '#6f6';
    document.getElementById('mfgStatus').textContent = m.mfgDecoded || 'N/A';
    document.getElementById('mfgDecoded').textContent = hex8(m.manufacturingStatus);

    document.getElementById('cellsSync').textContent = (m.cellsSync ? 'sync' : 'async') + ', ' + (m.cellCount || '?') + 'S';
    document.getElementById('packV').textContent = m.packV ? (m.packV/1000).toFixed(2) + ' V' : '-';

    let cellsHtml = '';
    const cells = m.cells || [];
    let minV = 9999, maxV = 0;
    cells.forEach((v, i) => {
      if (v > 0 && v < 5000) {
        if (v < minV) minV = v;
        if (v > maxV) maxV = v;
        const pct = Math.max(0, Math.min(100, (v-2500)/(4200-2500)*100));
        const col = v < 3300 ? '#f44' : v < 3600 ? '#fa0' : '#4f4';
        cellsHtml += `<div class="row"><span class="label">Cell ${i+1}</span><span class="value" style="color:${col}">${(v/1000).toFixed(3)} V</span></div>`;
        cellsHtml += `<div class="bar"><div class="bar-fill" style="width:${pct}%;background:${col}"></div></div>`;
      }
    });
    document.getElementById('cellsGrid').innerHTML = cellsHtml;
    const delta = (maxV > 0 && minV < 9999) ? (maxV - minV) : 0;
    const dEl = document.getElementById('cellDelta');
    dEl.textContent = delta + ' mV' + (delta > 50 ? ' UNBALANCED' : '');
    dEl.style.color = delta > 50 ? '#f44' : '#6f6';
  }
  else if (m.type === 'sys') {
    document.getElementById('sysIP').textContent = m.ip;
    document.getElementById('sysUptime').textContent = Math.floor(m.uptime/1000) + ' s';
    document.getElementById('sysHeap').textContent = (m.heap/1024).toFixed(1) + ' KB';
    document.getElementById('sysClients').textContent = m.clients;
  }
  else if (m.type === 'motor') {
    armed = m.armed;
    const s = document.getElementById('motorStatus');
    s.className = 'status ' + (armed ? 'on' : 'off');
    s.textContent = armed ? 'ARMED' : 'DISARMED';
    document.getElementById('throttleSlider').disabled = !armed;
    document.getElementById('armBtn').textContent = armed ? 'Re-arm' : 'ARM';
  }
  else if (m.type === 'crsf') {
    // Status badges
    const st = document.getElementById('crsfStatus');
    st.textContent = m.enabled ? 'ON' : 'OFF';
    st.className = 'status ' + (m.enabled ? 'on' : 'off');
    const co = document.getElementById('crsfConnected');
    co.textContent = m.connected ? 'LINK' : 'NO LINK';
    co.className = 'status ' + (m.connected ? 'on' : 'off');

    document.getElementById('crsfFrames').textContent = (m.frames || 0) + ' / ' + (m.badCrc || 0);

    // Link
    if (m.link) {
      document.getElementById('crsfRssi').textContent = m.link.rssi1 + ' dBm';
      document.getElementById('crsfLQ').textContent = m.link.lq + ' %';
      document.getElementById('crsfLqBar').style.width = m.link.lq + '%';
      document.getElementById('crsfSnr').textContent = m.link.snr + ' dB';
      document.getElementById('crsfRf').textContent = m.link.rf;
      document.getElementById('crsfPower').textContent = m.link.power + ' (idx)';
      document.getElementById('crsfDl').textContent = `RSSI ${m.link.dlRssi} dBm, LQ ${m.link.dlLq}%`;
    }

    // Channels
    if (m.ch) {
      let html = '';
      m.ch.forEach((v,i) => {
        // CRSF range 172-1811, center=992
        const pct = Math.max(0, Math.min(100, (v-172)/(1811-172)*100));
        const us = Math.round(((v - 992) * 5) / 8 + 1500); // convert to us approx
        html += `<div class="row"><span class="label">Ch ${i+1}</span><span class="value">${us}μs</span></div>`;
        html += `<div class="bar"><div class="bar-fill" style="width:${pct}%"></div></div>`;
      });
      document.getElementById('channelsGrid').innerHTML = html;
    }

    // FC telemetry
    if (m.mode) document.getElementById('crsfMode').textContent = m.mode;
    if (m.battery) {
      document.getElementById('crsfBatt').textContent =
        `${m.battery.v.toFixed(2)}V ${m.battery.i.toFixed(2)}A ${m.battery.mah}mAh (${m.battery.pct}%)`;
    }
    if (m.att) {
      document.getElementById('crsfAtt').textContent =
        `P:${m.att.p.toFixed(1)}° R:${m.att.r.toFixed(1)}° Y:${m.att.y.toFixed(1)}°`;
    }
    if (m.gps) {
      document.getElementById('crsfGPS').textContent =
        `${m.gps.lat.toFixed(6)}, ${m.gps.lon.toFixed(6)} alt=${m.gps.alt}m sats=${m.gps.sats}`;
    }

    // Device info
    if (m.device) {
      document.getElementById('crsfDevName').textContent = m.device.name;
      document.getElementById('crsfDevFw').textContent = '0x' + m.device.fw.toString(16);
      document.getElementById('crsfDevSerial').textContent = m.device.serial;
      document.getElementById('crsfDevFields').textContent = m.device.fields;
    }

    // Parameters (hierarchical by parent_id, state-aware COMMAND)
    if (m.params && m.params.length > 0) {
      document.getElementById('crsfParams').innerHTML = renderCrsfParams(m.params);
    }
  }
  else if (m.type === 'flash') {
    if (m.size > 0) {
      document.getElementById('fwSize').textContent = (m.size/1024).toFixed(1) + ' KB';
    }
    if (m.in_progress || m.progress > 0) {
      document.getElementById('flashStage').textContent = m.stage + ' (' + m.progress + '%)';
      document.getElementById('flashBar').style.width = m.progress + '%';
    }
    if (m.result && m.result !== '' && !m.in_progress) {
      document.getElementById('flashResult').textContent = 'Result: ' + m.result;
      document.getElementById('flashBtn').disabled = (m.size === 0);
    }
  }
}

connect();

// Initialize default workspace (Battery Lab)
showTab(_wsDefTab[_curWs]);

// Fetch and display firmware version in footer
fetch('/api/ota/info').then(r=>r.json()).then(j=>{
  const el = document.getElementById('fwFooter');
  if (el) el.textContent = 'FPV MultiTool ' + (j.fw_version || '?') + ' | heap ' + (j.app_size ? (j.app_size/1024/1024).toFixed(1)+'MB' : '?');
}).catch(()=>{});
</script>
<div id="fwFooter" style="text-align:center;color:#444;font-size:11px;margin:20px 0 8px;font-family:monospace"></div>
</body>
</html>
)HTML";

// WEB_INDEX_HTML / _LEN exports removed — we now serve WEB_INDEX_HTML_GZ only.
// The raw HTML above is static and stripped by the linker.
// Stub symbols kept to satisfy the extern in web_ui.h (ABI compat).
const char WEB_INDEX_HTML[] = "";
const size_t WEB_INDEX_HTML_LEN = 0;
