#include "web_server.h"
#include "web_ui.h"
#include "web_state.h"
#include "wifi_manager.h"
#include "pin_config.h"
#include <Wire.h>
#include "battery/dji_battery.h"
#include "battery/smbus.h"
#include "motor/dshot.h"
#include "servo/servo_pwm.h"
#include "bridge/esp_rom_flasher.h"
#include "bridge/firmware_unpack.h"
#include "crsf/crsf_service.h"
#include "crsf/crsf_config.h"
#include "core/usb_mode.h"
#include "core/pin_port.h"
#include "battery/battery_profiles.h"
#include "battery/dataflash_map.h"
#include "rc_sniffer/rc_sniffer.h"
#include "fpv/esc_telem.h"
#include "http/routes_flash.h"
#include "http/routes_ota.h"
#include "http/routes_battery.h"
#include "http/routes_crsf.h"
#include "http/routes_wifi.h"
#include "http/routes_usb.h"
#include "http/routes_port.h"
#include "http/routes_diag.h"
#include "http/routes_telemetry.h"

extern "C" int cp2112_log_dump(char *out, int cap);
extern "C" uint32_t cp2112_log_seq();
extern "C" int cp2112_ep_info(char *out, int cap);

#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <AsyncTCP.h>
#include <ArduinoJson.h>
#include <Update.h>
#include <esp_ota_ops.h>
#include <HTTPClient.h>
#include <HTTPUpdate.h>
#include <WiFiClientSecure.h>

// Build info header is generated by scripts/inject_version.py at every
// `pio run` — include it so this TU rebuilds whenever the git sha changes.
#if __has_include("core/build_info.h")
#  include "core/build_info.h"
#endif
#ifndef FW_VERSION
#define FW_VERSION "dev"
#endif
#ifndef GITHUB_REPO
#define GITHUB_REPO ""
#endif

// OTA pull state — moved to src/web/http/routes_ota.cpp

static AsyncWebServer *s_server = nullptr;
static AsyncWebSocket *s_ws = nullptr;
static bool s_running = false;
static uint32_t s_lastBroadcast = 0;

// Guards the shared `String` fields in the clone-research endpoints
// (s_brute.hits, s_macResp.hits / baselineHex, s_logger.entries). The
// Arduino String class is not thread-safe — a background FreeRTOS task
// appends while the HTTP status handler reads .c_str(), so we need a lock
// to avoid use-after-free if the producer reallocates mid-read.

static void handleWsMsg(AsyncWebSocketClient *client, uint8_t *data, size_t len) {
    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, data, len);
    if (err) return;

    const char* cmd = doc["cmd"];
    if (!cmd) return;

    // State-only commands: update shared state under lock, nothing else.
    // Hardware side-effects happen in later blocks AFTER the lock is dropped.
    enum ServoHwAction { SH_NONE, SH_SET_PULSE, SH_SET_FREQ, SH_STOP, SH_START_SWEEP };
    ServoHwAction servoHw = SH_NONE;
    int servoHwArg = 0;

    {
        WebState::Lock lock;

        if (strcmp(cmd, "servo") == 0) {
            int us = constrain((int)(doc["us"] | 1500), 100, 20000);
            WebState::servo.pulseUs = us;
            WebState::servo.active = true;
            WebState::servo.sweep = false;  // manual move cancels sweep
            if (WebState::servo.observedMinUs == 0 || us < WebState::servo.observedMinUs)
                WebState::servo.observedMinUs = us;
            if (us > WebState::servo.observedMaxUs) WebState::servo.observedMaxUs = us;
            servoHw = SH_SET_PULSE; servoHwArg = us;
        } else if (strcmp(cmd, "servoFreq") == 0) {
            int hz = doc["hz"] | 50;
            if (hz != WebState::servo.freq) {
                WebState::servo.freq = hz;
                servoHw = SH_SET_FREQ; servoHwArg = hz;
            }
        } else if (strcmp(cmd, "servoStop") == 0) {
            WebState::servo.active = false;
            WebState::servo.sweep = false;
            servoHw = SH_STOP;
        } else if (strcmp(cmd, "servoSweep") == 0) {
            bool on = doc["on"] | false;
            WebState::servo.sweep = on;
            if (on && !WebState::servo.active) {
                servoHw = SH_START_SWEEP; servoHwArg = WebState::servo.freq;
                WebState::servo.active = true;
            }
        } else if (strcmp(cmd, "servoSweepCfg") == 0) {
            int mn = doc["minUs"] | WebState::servo.sweepMinUs;
            int mx = doc["maxUs"] | WebState::servo.sweepMaxUs;
            int pr = doc["periodMs"] | WebState::servo.sweepPeriodMs;
            WebState::servo.sweepMinUs = constrain(mn, 500, 2500);
            WebState::servo.sweepMaxUs = constrain(mx, 500, 2500);
            if (WebState::servo.sweepMaxUs <= WebState::servo.sweepMinUs)
                WebState::servo.sweepMaxUs = WebState::servo.sweepMinUs + 100;
            WebState::servo.sweepPeriodMs = constrain(pr, 200, 20000);
        } else if (strcmp(cmd, "servoMarkMin") == 0) {
            WebState::servo.markedMinUs = WebState::servo.pulseUs;
        } else if (strcmp(cmd, "servoMarkMax") == 0) {
            WebState::servo.markedMaxUs = WebState::servo.pulseUs;
        } else if (strcmp(cmd, "servoResetMarks") == 0) {
            WebState::servo.markedMinUs = 0;
            WebState::servo.markedMaxUs = 0;
            WebState::servo.observedMinUs = 0;
            WebState::servo.observedMaxUs = 0;
        } else if (strcmp(cmd, "servoApplyMarks") == 0) {
            if (WebState::servo.markedMinUs > 0 && WebState::servo.markedMaxUs > WebState::servo.markedMinUs) {
                WebState::servo.sweepMinUs = WebState::servo.markedMinUs;
                WebState::servo.sweepMaxUs = WebState::servo.markedMaxUs;
            }
        } else if (strcmp(cmd, "motorArm") == 0) {
            WebState::motor.armRequest = true;
        } else if (strcmp(cmd, "motorDisarm") == 0) {
            WebState::motor.disarmRequest = true;
        } else if (strcmp(cmd, "throttle") == 0) {
            int req = constrain((int)(doc["value"] | 0), 0, 2000);
            if (req > WebState::motor.maxThrottle) req = WebState::motor.maxThrottle;
            WebState::motor.throttle = req;
        } else if (strcmp(cmd, "dshotSpeed") == 0) {
            WebState::motor.dshotSpeed = doc["speed"] | 300;
        } else if (strcmp(cmd, "motorBeep") == 0) {
            int b = doc["n"] | 1;
            if (b < 1 || b > 5) b = 1;
            WebState::motor.beepCmd = b;
            WebState::motor.beepRequest = true;
        } else if (strcmp(cmd, "motorMaxThrottle") == 0) {
            int v = constrain((int)(doc["value"] | 2000), 100, 2000);
            WebState::motor.maxThrottle = v;
            if (WebState::motor.throttle > v) WebState::motor.throttle = v;
        } else if (strcmp(cmd, "motorDirCW") == 0) {
            WebState::motor.dirCwRequest = true;
        } else if (strcmp(cmd, "motorDirCCW") == 0) {
            WebState::motor.dirCcwRequest = true;
        } else if (strcmp(cmd, "motor3DOn") == 0) {
            WebState::motor.mode3DOnRequest = true;
        } else if (strcmp(cmd, "motor3DOff") == 0) {
            WebState::motor.mode3DOffRequest = true;
        }
    }  // lock released

    // Hardware side effects (lock released — these can block or call
    // PinPort::acquire without deadlocking).
    switch (servoHw) {
        case SH_SET_PULSE:   ServoPWM::setPulse(servoHwArg); break;
        case SH_SET_FREQ:    ServoPWM::setFrequency(servoHwArg); break;
        case SH_STOP:        ServoPWM::stop(); break;
        case SH_START_SWEEP: ServoPWM::start(SIGNAL_OUT, servoHwArg); break;
        case SH_NONE:        break;
    }
}

static void onWsEvent(AsyncWebSocket *server, AsyncWebSocketClient *client,
                      AwsEventType type, void *arg, uint8_t *data, size_t len) {
    if (type == WS_EVT_CONNECT) {
        Serial.printf("[WS] client #%u connected\n", client->id());
    } else if (type == WS_EVT_DISCONNECT) {
        Serial.printf("[WS] client #%u disconnected\n", client->id());
    } else if (type == WS_EVT_DATA) {
        AwsFrameInfo *info = (AwsFrameInfo*)arg;
        if (info->final && info->index == 0 && info->len == len && info->opcode == WS_TEXT) {
            handleWsMsg(client, data, len);
        }
    }
}

static void broadcastTelemetry() {
    if (s_ws->count() == 0) return;

    // Battery data
    BatteryInfo info = DJIBattery::readAll();
    JsonDocument doc;
    doc["type"] = "batt";
    doc["connected"] = info.connected;
    if (info.connected) {
        doc["devType"] = (int)info.deviceType;  // 0=none,1=DJI,2=generic SBS
        doc["voltage"] = info.voltage_mV;
        doc["current"] = info.current_mA;
        doc["avgCurrent"] = info.avgCurrent_mA;
        doc["temp"] = info.temperature_C;
        doc["soc"] = info.stateOfCharge;
        doc["absSOC"] = info.absoluteSOC;
        doc["soh"] = info.stateOfHealth;
        doc["remain"] = info.remainCapacity_mAh;
        doc["full"] = info.fullCapacity_mAh;
        doc["design"] = info.designCapacity_mAh;
        doc["designV"] = info.designVoltage_mV;
        doc["cycles"] = info.cycleCount;
        doc["status"] = info.batteryStatus;
        doc["statusDecoded"] = DJIBattery::decodeBatteryStatus(info.batteryStatus);
        doc["sn"] = info.serialNumber;
        doc["mfgDate"] = info.manufactureDate;
        doc["mfr"] = info.manufacturerName;
        doc["dev"] = info.deviceName;
        doc["chem"] = info.chemistry;
        doc["cellCount"] = info.cellCount;

        // Time estimates
        doc["rte"] = info.runTimeToEmpty_min;
        doc["ate"] = info.avgTimeToEmpty_min;
        doc["ttf"] = info.timeToFull_min;
        doc["chgI"] = info.chargingCurrent_mA;
        doc["chgV"] = info.chargingVoltage_mV;

        // DJI-specific
        if (info.deviceType == DEV_DJI_BATTERY) {
            if (info.djiSerial.length() > 0) doc["djiSN"] = info.djiSerial;
            doc["djiPF2"] = info.djiPF2;
        }

        // Cells (sync if available)
        JsonArray cells = doc["cells"].to<JsonArray>();
        for (int i = 0; i < info.cellCount; i++) {
            uint16_t v = info.daStatus1Valid ? info.cellVoltSync[i] : info.cellVoltage[i];
            cells.add(v);
        }
        doc["cellsSync"] = info.daStatus1Valid;
        doc["packV"] = info.packVoltage;

        // Extended status
        doc["safetyStatus"] = info.safetyStatus;
        doc["pfStatus"] = info.pfStatus;
        doc["operationStatus"] = info.operationStatus;
        doc["manufacturingStatus"] = info.manufacturingStatus;
        doc["sealed"] = info.sealed;
        doc["hasPF"] = info.hasPF;

        // Decoded
        doc["pfDecoded"] = DJIBattery::decodePFStatus(info.pfStatus);
        doc["safetyDecoded"] = DJIBattery::decodeSafetyStatus(info.safetyStatus);
        doc["opDecoded"] = DJIBattery::decodeOperationStatus(info.operationStatus);
        doc["mfgDecoded"] = DJIBattery::decodeManufacturingStatus(info.manufacturingStatus);

        // Chip/model
        doc["chipType"] = info.chipType;
        doc["fwVer"] = info.firmwareVersion;
        doc["hwVer"] = info.hardwareVersion;
        doc["model"] = DJIBattery::modelName(info.model);
        doc["needsKey"] = DJIBattery::modelNeedsDjiKey(info.model);
    }
    String msg;
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // System info
    doc.clear();
    doc["type"] = "sys";
    doc["ip"] = WifiManager::getIP();
    doc["uptime"] = millis();
    doc["heap"] = ESP.getFreeHeap();
    doc["clients"] = s_ws->count();
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // Motor status
    doc.clear();
    doc["type"] = "motor";
    doc["armed"] = WebState::motor.armed;
    doc["throttle"] = WebState::motor.throttle;
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // Flash status
    doc.clear();
    doc["type"] = "flash";
    doc["size"] = WebState::flashState.fw_size;
    doc["in_progress"] = WebState::flashState.in_progress;
    doc["progress"] = WebState::flashState.progress_pct;
    doc["stage"] = WebState::flashState.stage;
    doc["result"] = WebState::flashState.lastResult;
    msg = "";
    serializeJson(doc, msg);
    s_ws->textAll(msg);

    // CRSF telemetry (if enabled)
    if (WebState::crsf.isEnabled() && CRSFService::isRunning()) {
        const auto &st = CRSFService::state();
        doc.clear();
        doc["type"] = "crsf";
        doc["enabled"] = true;
        doc["connected"] = st.connected;
        doc["frames"] = st.total_frames;
        doc["badCrc"] = st.bad_crc;

        // Link stats
        if (st.link.valid) {
            JsonObject link = doc["link"].to<JsonObject>();
            link["rssi1"] = (int8_t)st.link.uplink_rssi1 * -1;
            link["rssi2"] = (int8_t)st.link.uplink_rssi2 * -1;
            link["lq"]    = st.link.uplink_link_quality;
            link["snr"]   = st.link.uplink_snr;
            link["rf"]    = st.link.rf_mode;
            link["power"] = st.link.uplink_tx_power;
            link["dlRssi"] = (int8_t)st.link.downlink_rssi * -1;
            link["dlLq"] = st.link.downlink_link_quality;
        }

        // Battery telemetry
        if (st.battery.valid) {
            JsonObject b = doc["battery"].to<JsonObject>();
            b["v"]    = st.battery.voltage_dV / 10.0f;
            b["i"]    = st.battery.current_dA / 10.0f;
            b["mah"]  = st.battery.capacity_mAh;
            b["pct"]  = st.battery.remaining_pct;
        }

        // GPS
        if (st.gps.valid) {
            JsonObject g = doc["gps"].to<JsonObject>();
            g["lat"] = st.gps.latitude_e7 / 1e7;
            g["lon"] = st.gps.longitude_e7 / 1e7;
            g["spd"] = st.gps.speed_cms / 27.78f; // cm/s → km/h
            g["hdg"] = st.gps.heading_cd / 100.0f;
            g["alt"] = (int)st.gps.altitude_m - 1000;
            g["sats"] = st.gps.satellites;
        }

        // Attitude
        if (st.attitude.valid) {
            JsonObject a = doc["att"].to<JsonObject>();
            a["p"] = st.attitude.pitch_10krad / 174.53f; // rad*10000 → degrees
            a["r"] = st.attitude.roll_10krad  / 174.53f;
            a["y"] = st.attitude.yaw_10krad   / 174.53f;
        }

        if (st.mode.valid) doc["mode"] = st.mode.name;

        // Channels
        if (st.channels.valid) {
            JsonArray ch = doc["ch"].to<JsonArray>();
            for (int i = 0; i < 16; i++) ch.add(st.channels.ch[i]);
        }

        // Device info
        const auto &dev = CRSFConfig::deviceInfo();
        if (dev.valid) {
            JsonObject d = doc["device"].to<JsonObject>();
            d["name"]   = dev.name;
            d["fw"]     = dev.sw_ver;
            d["hw"]     = dev.hw_ver;
            d["serial"] = dev.serial;
            d["fields"] = dev.field_count;
        }

        // Parameters
        if (CRSFConfig::paramCount() > 0) {
            JsonArray params = doc["params"].to<JsonArray>();
            for (int i = 0; i < CRSFConfig::paramCount(); i++) {
                const auto &p = CRSFConfig::param(i);
                if (!p.complete) continue;
                if (p.hidden) continue;  // skip debug/internal entries
                JsonObject o = params.add<JsonObject>();
                o["id"]     = p.id;
                o["parent"] = p.parent_id;
                o["type"]   = p.type;
                o["name"]   = p.name;
                o["unit"]   = p.unit;
                if (p.type == 9) {  // TEXT_SELECTION
                    o["opts"] = p.options;
                    o["idx"]  = p.option_index;
                } else if (p.type == 10 || p.type == 12) {  // STRING/INFO
                    o["value"] = p.value_text;
                } else if (p.type == 11) {  // FOLDER
                    // no value
                } else if (p.type == 13) {  // COMMAND
                    // ELRS lifecycle: status + info, rendered as state-aware button(s).
                    o["status"]  = p.value_num;   // 0=READY,2=PROG,3=CONFIRM_NEEDED,...
                    o["timeout"] = p.max_val;     // in 10ms units
                    o["info"]    = p.value_text;
                } else {
                    o["value"] = p.value_num;
                    o["min"] = p.min_val;
                    o["max"] = p.max_val;
                }
            }
        }

        msg = "";
        serializeJson(doc, msg);
        s_ws->textAll(msg);
    }
}

// Flash progress callback (called from flasher)

// Execute flashing (called from main loop when flash_request = true)

void WebServer::start() {
    if (s_running) return;

    s_server = new AsyncWebServer(80);
    RoutesFlash::registerRoutesFlash(s_server);
    RoutesOta::registerRoutesOta(s_server);
    RoutesBattery::registerRoutesBattery(s_server);
    RoutesCrsf::registerRoutesCrsf(s_server);
    RoutesWifi::registerRoutesWifi(s_server);
    RoutesUsb::registerRoutesUsb(s_server);
    RoutesPort::registerRoutesPort(s_server);
    RoutesDiag::registerRoutesDiag(s_server);
    RoutesTelemetry::registerRoutesTelemetry(s_server);
    s_ws = new AsyncWebSocket("/ws");
    s_ws->onEvent(onWsEvent);
    s_server->addHandler(s_ws);

    // Root — gzipped HTML from PROGMEM (~4x smaller over the wire)
    // Browser transparently decompresses via Content-Encoding: gzip.
    s_server->on("/", HTTP_GET, [](AsyncWebServerRequest *req) {
        AsyncWebServerResponse *r = req->beginResponse_P(
            200, "text/html", WEB_INDEX_HTML_GZ, WEB_INDEX_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "max-age=3600");
        req->send(r);
    });

    // Battery service actions

    // ===== Clone Explorer =====
    // Batch scan of SBS register space — reports which registers respond and what they return.
    // Runs mostly 0xFF-returning reads for sealed/non-existent regs; useful to find
    // vendor-specific regs on clone chips that don't implement TI MAC commands.

    // ===== Clone Deep Probe =====

    // Challenge Harvester — write value N times, record response after each write.
    // For studying pseudo-random challenge generators (e.g. reg 0xEE on PTL clone).
    //   GET /api/batt/clone/harvest?reg=0xEE&writeVal=0x0000&count=100&readLen=16
    // Returns compact JSON: [{"w":"0xNNNN","r":"hex"}, ...]

    // Raw block-write to any SBS register (bypasses the standard SMBus block format
    // which prepends a length byte). Use for clones that expect raw payload.
    //   POST reg=0xNN&data=HEX&len=N

    // PEC-enabled variant of SBS writes — some strict SMBus devices/clones
    // silently drop non-PEC writes. Retry unseal keys + anything else with PEC.
    //   POST reg=0xNN&type=word&value=0xNNNN
    //   POST reg=0xNN&type=block&data=HEX

    // =====================================================================
    // MAC Response Brute — different angle: TI-standard flow is
    //   writeWord(0x00, cmd); then readBlock(0x00) — reads cmd-specific data.
    // For each MAC value 0x0000..0xFFFF: write cmd, read block back from 0x00,
    // log ANY response whose content is non-default.
    // Default response is what we get with MAC 0x0000 (reading current cmd latch).
    // Any MAC returning DIFFERENT data = a real command that returns something.
    // =====================================================================

    // MAC Transition Brute — writes MAC_A, then MAC_B, reads between them.
    // Hypothesis: clone's "publish cell voltage" response only appears after
    // a TRANSITION between specific MAC values. Scan N combinations fast.
    //   GET /api/batt/clone/trans_brute?macA=0x0000&from=0x0000&to=0x00FF
    //       For each B in [from..to], sequence: write(A), read#1, write(B), read#2.
    //       Report only responses where bytes 2+ are non-0xFF.

    // Read reg 0x00 rapidly N times onboard, return only unique non-echo responses.
    //   GET /api/batt/clone/async_catch?count=1000&intervalUs=0
    // Broader transition brute — sweep both macA AND macB, catch all publish packets.
    // macA varies in small range while macB does full sweep. Logs every
    // distinct publish packet (by first 4 bytes after 81 F0 marker).
    //   GET /api/batt/clone/broad_brute?macA_from=0x0000&macA_to=0x0100&macA_step=0x10&macB_to=0x03FF

    // Inject frame test — write a 81F0-formatted frame to reg 0x44 (ManufacturerBlockAccess)
    // or arbitrary reg, then read back from 0x44 and 0x00 to see if the chip
    // interpreted it as a valid command.
    //   POST reg=0x44&frame=81F00001000012345678AABB

    // Persistent background publish logger — runs a low-priority task that
    // does a small transition-brute every pollSec seconds, captures any new
    // publish packet, logs to circular buffer for later download.
    //   POST /api/batt/clone/logger_start?pollSec=30
    //   GET  /api/batt/clone/logger_dump
    //   POST /api/batt/clone/logger_stop

    // DataFlash dump: sweep all DF addresses 0x4000-0x7FFF in ranges, try to read
    // each via MAC 0x44 (ManufacturerBlockAccess). Even if sealed, some DF areas
    // may be readable on clone chips (PTL may have incomplete seal enforcement).
    //   GET /api/batt/clone/dfdump?from=0x4000&to=0x40FF

    // SH366000 family commands test — PTL clone may use SH366000 silicon which
    // mimicks BQ40Z307 surface. These are non-TI MAC subcommands specific to SH.
    //   GET /api/batt/clone/sh366000_test

    // HMAC timing attack — measure response time for MAC 0x0000 challenge + HMAC.
    // If chip does non-constant-time HMAC verify, first-byte-wrong vs last-byte-wrong
    // will differ in timing. Report median and stddev of response delay per key.
    //   POST /api/batt/clone/timing_attack?samples=100

    // Periodic-publish watcher — poll reg 0x00 every intervalMs for count samples,
    // log any distinct packet seen. Good for catching time-based publishes.
    //   GET /api/batt/clone/watch?count=500&intervalMs=50

    // (Original synchronous brute retained for small ranges)
    // Brute-force writes to reg 0x00 (ManufacturerAccess) and monitor for
    // state changes in vendor regs.
    //   GET /api/batt/clone/mac_brute?from=0x0000&to=0x0010&probe=0xEE,0xF0

    // HMAC-SHA1 challenge-response unseal (newer bq40z30x firmware).
    // POST ?key=<64-hex-chars> (32 bytes)
    // Returns: {ok, challenge:hex, result:"Unsealed OK"/"Rejected"/...}

    // Diagnostic endpoint — raw SBS / MAC reads + arbitrary unseal keys.
    // Examples:
    //   /api/batt/diag?mac=0x0070                     -> MAC block read (ChemID)
    //   /api/batt/diag?sbs=0x20&type=string           -> ManufacturerName
    //   /api/batt/diag?sbs=0x54&type=dword            -> OperationStatus
    //   /api/batt/diag?unseal=0xABCD,0x1234           -> custom key pair
    // /api/wifi/* split into routes_wifi.cpp.

    s_server->on("/status", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument doc;
        doc["mode"] = WifiManager::currentMode();
        doc["ssid"] = WifiManager::getSSID();
        doc["ip"] = WifiManager::getIP();
        doc["heap"] = ESP.getFreeHeap();
        doc["uptime"] = millis();
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    });

    // ELRS firmware upload
    // Max accepted firmware size (ELRS is ~400KB, headroom for big builds)
    static const size_t MAX_FW_SIZE = 2 * 1024 * 1024;

    // Diagnostic: heap + PSRAM + flash state. Helps isolate upload failures.
    s_server->on("/api/sys/mem", HTTP_GET, [](AsyncWebServerRequest *req) {
        JsonDocument d;
        d["heap_free"]     = ESP.getFreeHeap();
        d["heap_min"]      = ESP.getMinFreeHeap();
        d["heap_total"]    = ESP.getHeapSize();
        d["psram_free"]    = ESP.getFreePsram();
        d["psram_total"]   = ESP.getPsramSize();
        d["psram_min"]     = ESP.getMinFreePsram();
        d["largest_block"] = ESP.getMaxAllocHeap();
        d["largest_psram"] = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
        d["flash_fw_size"] = WebState::flashState.fw_size;
        d["flash_fw_recv"] = WebState::flashState.fw_received;
        d["flash_fw_buf"]  = WebState::flashState.fw_data ? "allocated" : "null";
        d["flash_stage"]   = WebState::flashState.stage;
        d["flash_offset"]  = WebState::flashState.flash_offset;
        d["flash_progress"] = WebState::flashState.progress_pct;
        d["flash_in_progress"] = WebState::flashState.in_progress;
        d["flash_last_result"] = WebState::flashState.lastResult;
        String out; serializeJson(d, out);
        req->send(200, "application/json", out);
    });

    // Start flashing (after upload)

    // GET /api/flash/status — lets the UI poll progress over HTTP without
    // relying on the WebSocket broadcast (which only runs every second and
    // only updates the main flash card's DOM ids).

    // ===== Receiver firmware DUMP (READ_FLASH via ROM bootloader) =====
    // Reads the attached ESP32-C3 / S2 / S3 receiver's SPI flash over UART1
    // through the same physical Port B pins that the upload flow uses.
    // User must have the receiver in DFU/bootloader mode (hold BOOT + power
    // cycle). Runs in a background task; poll status and then GET the
    // binary.

    // Erase a flash region on the attached RX (RX must be in ROM bootloader).
    // Intended use: wipe OTA-select sector to force boot into secondary app,
    // wipe NVS to factory-reset, etc. Caller MUST power-cycle the RX afterwards
    // (we leave the ROM in a "ready to reboot" state but don't send the reboot).

    // Fast flash-region integrity check. ROM computes MD5 over the
    // requested range and returns 16 raw bytes (or 32 ASCII hex from
    // some ROMs — ESPFlasher::spiFlashMd5 handles both). ~600x faster
    // than readback for verifying writes.
    //
    //  POST /api/flash/md5  form: offset=<hex>&size=<hex>
    //  -> {"md5": "ab12…", "offset": 0x10000, "size": 0x130000}
    // Synchronous small-region flash read. Returns hex (2 chars/byte) in the
    // response body. No background task, no polling — the entire read happens
    // inside the request handler so you can verify a freshly-flashed image
    // within a single DFU session (the async /api/flash/dump/* path requires
    // multiple round-trips and often loses DFU between them).
    //  POST /api/flash/read_bytes  form: offset=<hex>&size=<hex, max 2048>
    // Passive UART sniffer for RX boot diagnostics. Opens Serial1 at the
    // requested baud, reads bytes for `ms` milliseconds, returns hex + ASCII
    // rendering. Used to catch ESP-IDF ROM boot banner (74880 baud default
    // on ESP32-C3) or ELRS app-level output. Does NOT transmit — so RX is
    // undisturbed, user just power-cycles RX while we listen.
    //   POST /api/bridge/listen  form: baud=<int>&ms=<int, max 8000>

    // Erase a full partition by looping erase_region chunks. Use to wipe
    // the entire app1 (MILELRS) partition which is 1.88 MB — exceeds
    // the single-call 64 KB cap. Blocking, ~5-10 s total.
    //
    //  POST /api/flash/erase_partition  form: offset=<hex>&size=<hex>&chunk=0x10000

    // Chip detection — reads CHIP_DETECT_MAGIC_VALUE + MAC over the same
    // Port B UART. RX must be in ROM DFU (hold BOOT + power-cycle). Cheap
    // one-round-trip sanity check before any flash op.

    // Full dual-slot receiver identity in ONE DFU session. Chip info + OTADATA
    // + app0 scan + app1 scan. Frontend uses this to render the Receiver
    // overview + Slots cards without burning N separate DFU cycles.
    //   POST /api/elrs/receiver_info

    // Send MSP-over-CRSF "set RX WiFi mode" (MSP function 0x0E). Mirrors what
    // the ELRS Configurator / OpenTX Lua script sends. RX handler at
    // [rx_main.cpp:1228] defers by 500 ms then flips connectionState to
    // wifiUpdate → SoftAP "ExpressLRS RX" at 10.0.0.1.
    //
    // Actual packet layout derived from
    // [hardware/bayckrc_c3_dual/elrs_3_6_3_src/src/lib/Handset/CRSF.cpp:79]
    // (SetMspV2Request): the MSP header byte is 0x50 (NOT 0x30 as some 3rd-
    // party docs say), with length field being 2 bytes LE.
    //   Frame: C8 0B 7A EC EA  50 00 0E 00 00 00  <mspCRC>  <crsfCRC>
    //          addr len type dest orig  status flags func_lo func_hi len_lo len_hi  crc  crc
    //   mspCRC  = CRC8-DVB-S2(0xD5, init 0) over [flags..payload] i.e. bytes[1..5+0]
    //   crsfCRC = CRC8-DVB-S2(0xD5, init 0) over [type..mspCRC] i.e. frameSize-1 bytes
    //
    //   POST /api/elrs/enable_wifi  [form: inverted=0|1]

    // Exit stub / ROM cleanly — sends CMD_RUN_USER_CODE (0xD3).
    // Use this when RX is stuck in the in-app stub (from a prior CRSF-bl
    // trigger) or in ROM DFU and we want it to jump to the OTADATA-selected
    // app without requiring a physical power-cycle.

    // Send the CRSF "reboot to bootloader" command (the 5-byte "bl" frame
    // `EC 04 32 62 6C <crc>`). ELRS 3.x firmware on ESP32 handles this by
    // NOT rebooting to ROM — it enters an in-app esptool stub that speaks
    // the SYNC/FLASH_BEGIN/DATA/END/READ_FLASH/SPI_FLASH_MD5 protocol on
    // the SAME UART at the SAME baud. No hardware DFU, no power-cycle.
    //
    // After calling this: the plate must switch into ESPFlasher mode on
    // Port B UART without renegotiating baud. Then every existing flash /
    // dump / otadata endpoint just works.
    //
    // Works on vanilla ELRS 3.x AND MILELRS (MILELRS inherits the handler).

    // ===== OTADATA atomic select =====
    // ESP-IDF OTADATA record format (32 bytes):
    //   0..3  ota_seq      u32  (highest wins)
    //   4..23 seq_label    char[20]
    //   24..27 ota_state   u32  (0xFFFFFFFF = undefined = valid-on-next-boot)
    //   28..31 crc         u32  (crc32_le over ota_seq, init 0xFFFFFFFF)
    //
    // Active slot = (max_seq - 1) & 1. So:
    //   slot 0 requires max_seq ∈ {1, 3, 5, ...} (odd)
    //   slot 1 requires max_seq ∈ {2, 4, 6, ...} (even)
    //
    // Safe update algorithm: pick new_seq = max(seq0, seq1) + 1, bump parity
    // if needed, write the record to the sector that currently holds the
    // LOWER seq (alternating-sector write). RX must be in DFU mode.

    // Read current OTADATA state (RX must be in DFU).

    // CRSF telemetry service endpoints split into routes_crsf.cpp.

    // Clear uploaded firmware

    // ===== OTA firmware update =====

    // Query GitHub releases/latest API; cache asset URL + tag for subsequent pull.

    // Start background download + flash from the previously checked asset URL.

    // /api/usb/* split into routes_usb.cpp.

    // /api/port/* + /api/setup/* split into routes_port.cpp.

    // /api/cp2112/* + /api/i2c/* split into routes_diag.cpp.

    // BLHeli 4way passthrough + OneWire ESC probe were removed in v0.28.3.
    // 4way TCP server only forwarded commands to a stub OneWire bit-bang
    // that was never timing-calibrated on real ESC silicon — it returned
    // 0xFF for nearly every command and misled users into thinking
    // BLHeliSuite32 was talking to their ESC. KISS / BLHeli_32 ESC
    // telemetry decoding (read-only, /api/esc/telem/state) is still here
    // and works. If 4way passthrough is needed in the future, redo from
    // scratch with bench-validated bit-bang timing.

    // /api/servo/state + /api/esc/telem/* + /api/rc/* split into routes_telemetry.cpp.

    // /api/usb/reboot moved to routes_usb.cpp alongside /api/usb/mode.

    // HTTP fallback for UI `send()` when the WebSocket is down. Accepts the
    // same JSON body that would be sent through WS and dispatches to the
    // shared handler. Prevents commands from silently 404-ing when the user
    // momentarily lost WS (mobile suspend, AP hop).
    s_server->on("/api/ws", HTTP_POST,
        [](AsyncWebServerRequest *req) {
            // Unused final handler — body is consumed in onBody below.
        },
        nullptr,
        [](AsyncWebServerRequest *req, uint8_t *data, size_t len, size_t index, size_t total) {
            if (index == 0 && len == total) {
                handleWsMsg(nullptr, data, len);
                req->send(200, "text/plain", "OK");
            } else if (total > 0 && index + len == total) {
                // Multi-chunk body — unlikely for WS commands (<1KB), but accept anyway.
                handleWsMsg(nullptr, data, len);
                req->send(200, "text/plain", "OK");
            }
        });

    s_server->onNotFound([](AsyncWebServerRequest *req) {
        req->send(404, "text/plain", "Not found");
    });

    s_server->begin();
    s_running = true;
    Serial.println("[Web] Server started on :80");
}

void WebServer::stop() {
    if (!s_running) return;
    if (s_server) { s_server->end(); delete s_server; s_server = nullptr; }
    if (s_ws) { delete s_ws; s_ws = nullptr; }
    s_running = false;
    Serial.println("[Web] Server stopped");
}

bool WebServer::isRunning() { return s_running; }

void WebServer::loop() {
    if (!s_running) return;

    // CRSF loop (parse incoming, handle params)
    if (CRSFService::isRunning()) {
        CRSFService::loop();
        CRSFConfig::loop();
    }

    uint32_t now = millis();
    if (now - s_lastBroadcast > 1000) {
        broadcastTelemetry();
        s_lastBroadcast = now;
        s_ws->cleanupClients();
    }

    // Execute flash request on a dedicated task. Running RoutesFlash::executeFlash() on
    // the main loop blocks every other main-loop consumer (CRSF, WS broadcast,
    // battery service) for ~3 minutes; worse, the idle-task watchdog on core 0
    // fired mid-flash and rebooted the plate. The dump path already uses a
    // task for the same reason.
    // consumeFlashRequest is atomic test-and-clear — guarantees the task is
    // never spawned twice for the same request. Re-entrancy guard via
    // in_progress: don't dequeue while a previous flash is still running.
    if (!WebState::flashState.in_progress &&
        WebState::flashState.consumeFlashRequest()) {
        xTaskCreate([](void *){
            RoutesFlash::executeFlash();
            vTaskDelete(nullptr);
        }, "elrs_flash", 8192, nullptr, 1, nullptr);
    }

    // Sticky DFU session idle-timeout watchdog. Cheap (single millis() compare).
    RoutesFlash::tick();

    // Execute pending battery service actions from web thread.
    // takePending atomically pops + clears, so the action handler sees a
    // consistent snapshot and HTTP polls don't observe a stale "pending"
    // after the action returned.
    WebState::BattServiceAction pending = WebState::battSvc.takePending();
    if (pending != WebState::BS_NONE) {
        bool ok = false;
        switch (pending) {
            case WebState::BS_UNSEAL:  ok = DJIBattery::unseal(); break;
            case WebState::BS_CLEARPF: ok = DJIBattery::clearPFProper(); break;
            case WebState::BS_SEAL:    ok = DJIBattery::seal(); break;
            default: break;
        }
        WebState::battSvc.markResult(ok ? "OK" : "FAILED");
    }
}
