#pragma once
#include <Arduino.h>

// HTML/CSS/JS for web UI (embedded in PROGMEM)
extern const char WEB_INDEX_HTML[];
extern const size_t WEB_INDEX_HTML_LEN;

// Gzipped HTML/CSS/JS — auto-generated by scripts/gzip_web_ui.py from
// data/{index.html,style.css,ui.js}. Served with Content-Encoding: gzip.
// Three separate resources so the browser can cache them independently
// and so HTML parse doesn't block on the JS download.
extern const uint8_t WEB_INDEX_HTML_GZ[];
extern const size_t  WEB_INDEX_HTML_GZ_LEN;
extern const uint8_t WEB_STYLE_CSS_GZ[];
extern const size_t  WEB_STYLE_CSS_GZ_LEN;
extern const uint8_t WEB_UI_JS_GZ[];
extern const size_t  WEB_UI_JS_GZ_LEN;
