#!/usr/bin/env python3
# Convert esptool stub_flasher_*.json files into a PROGMEM C header.
#
# Output: src/bridge/esp_rom_stubs.h — table of {magic, name, text/data
# blobs + start addrs, entry} so the flasher can pick the right stub for
# the chip detected via READ_REG.
#
# The JSONs come from esptool.py — already vendored under
# hardware/bayckrc_c3_dual/elrs_3_6_3_src/src/python/external/esptool/.
import base64, json, os, textwrap

REPO = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
# Prefer PlatformIO's tool-esptoolpy — the bundled JSONs there ship with the
# active toolchain and tend to be newer than the ELRS-vendored copy. Fallback
# to ELRS path so the script still works if PIO isn't available.
PIO_DIR = os.path.expanduser(
    "~/.platformio/packages/tool-esptoolpy/esptool/targets/stub_flasher")
ELRS_DIR = os.path.join(REPO, "hardware", "bayckrc_c3_dual",
                       "elrs_3_6_3_src", "src", "python", "external",
                       "esptool", "esptool", "targets", "stub_flasher")
SRC_DIR = PIO_DIR if os.path.isdir(PIO_DIR) else ELRS_DIR
OUT = os.path.join(REPO, "src", "bridge", "esp_rom_stubs.h")

# (target, chip-name, magic_value(s) returned by READ_REG 0x40001000)
# Magics from esptool.py: ESPLoader.CHIP_DETECT_MAGIC_VALUE per family.
TARGETS = [
    # filename suffix    friendly       magic values that map to it
    ("8266",       "ESP8266",   [0xfff0c101]),
    ("32",         "ESP32",     [0x00f01d83]),
    ("32s2",       "ESP32-S2",  [0x000007c6]),
    ("32s3",       "ESP32-S3",  [0x00000009, 0xeb004136]),
    ("32c2",       "ESP32-C2",  [0x6f51306f, 0x7c41a06f]),
    ("32c3",       "ESP32-C3",  [0x6921506f, 0x1b31506f]),
    ("32c6",       "ESP32-C6",  [0x2ce0806f, 0x0da1806f]),
    ("32h2",       "ESP32-H2",  [0xd7b73e80, 0xca26cc22]),
]

def to_c_array(name, blob):
    PER_LINE = 16
    out = [f"static const uint8_t {name}[] PROGMEM = {{\n"]
    for i in range(0, len(blob), PER_LINE):
        chunk = blob[i:i+PER_LINE]
        out.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.append("};\n")
    return "".join(out)

def main():
    out = []
    out.append("// AUTO-GENERATED by tools/gen_stubs.py — do not edit by hand.\n")
    out.append("// Embedded esptool stub binaries for ESP-family ROMs. Loaded into RX RAM\n")
    out.append("// via MEM_BEGIN/MEM_DATA/MEM_END from the ROM bootloader so that\n")
    out.append("// subsequent SLIP commands talk to the stub (robust mixed commands)\n")
    out.append("// instead of the ROM (autobauder fragile after READ_FLASH_SLOW chains).\n")
    out.append("//\n")
    out.append("// Source JSONs from esptool 4.x targets/stub_flasher/. Decoded once at\n")
    out.append("// codegen time — keeps the firmware self-contained (no SD/SPIFFS lookup).\n")
    out.append("#pragma once\n")
    out.append("#include <Arduino.h>\n")
    out.append("#include <pgmspace.h>\n\n")
    out.append("namespace ESPRomStub {\n\n")

    summary_rows = []
    for suffix, friendly, magics in TARGETS:
        path = os.path.join(SRC_DIR, f"stub_flasher_{suffix}.json")
        d = json.load(open(path))
        text = base64.b64decode(d["text"])
        data = base64.b64decode(d["data"])
        prefix = f"stub_{suffix.replace('beta1','b1').replace('beta2','b2').replace('beta','b')}"
        out.append(f"// {friendly} stub — entry=0x{d['entry']:08x} "
                   f"text_start=0x{d['text_start']:08x} ({len(text)} B)\n")
        out.append(to_c_array(prefix + "_text", text))
        out.append(to_c_array(prefix + "_data", data))
        out.append("\n")
        summary_rows.append((friendly, magics, prefix, d["entry"], d["text_start"],
                             len(text), d["data_start"], len(data)))

    out.append("struct StubBin {\n")
    out.append("    const char    *chip_name;\n")
    out.append("    uint32_t       magic;          // matches READ_REG 0x40001000\n")
    out.append("    const uint8_t *text;\n")
    out.append("    uint32_t       text_start;\n")
    out.append("    uint32_t       text_len;\n")
    out.append("    const uint8_t *data;\n")
    out.append("    uint32_t       data_start;\n")
    out.append("    uint32_t       data_len;\n")
    out.append("    uint32_t       entry;\n")
    out.append("};\n\n")

    out.append("static const StubBin kStubs[] = {\n")
    for friendly, magics, prefix, entry, ts, tl, ds, dl in summary_rows:
        for m in magics:
            out.append(f"    {{ \"{friendly}\", 0x{m:08x}u, {prefix}_text, "
                       f"0x{ts:08x}u, {tl}, {prefix}_data, 0x{ds:08x}u, {dl}, "
                       f"0x{entry:08x}u }},\n")
    out.append("};\n")
    out.append("static const size_t kStubsCount = sizeof(kStubs) / sizeof(kStubs[0]);\n\n")

    out.append("// Lookup by chip-magic returned from READ_REG. Returns nullptr if\n")
    out.append("// the magic doesn't match any embedded stub (caller should fall back\n")
    out.append("// to plain-ROM mode).\n")
    out.append("static inline const StubBin* findStubByMagic(uint32_t magic) {\n")
    out.append("    for (size_t i = 0; i < kStubsCount; i++) {\n")
    out.append("        if (kStubs[i].magic == magic) return &kStubs[i];\n")
    out.append("    }\n")
    out.append("    return nullptr;\n")
    out.append("}\n\n")
    out.append("} // namespace ESPRomStub\n")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(out))
    print(f"Wrote {OUT}")
    total_text = sum(r[5] for r in summary_rows)
    total_data = sum(r[7] for r in summary_rows)
    print(f"Stubs: {len(summary_rows)} chips, {sum(len(r[1]) for r in summary_rows)} magics")
    print(f"Total embedded: {total_text} text + {total_data} data = {total_text+total_data} bytes")

if __name__ == "__main__":
    main()
